### PR TITLE
address `attackofthefanboy.com` anti-adb

### PR DESCRIPTION
**Pull request by huyszn**
`https://attackofthefanboy.com/guides/remnant-2-zohees-ring-location-stats-effects-and-best-builds/`

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
@Yuki2718 admiral `steepscale.com`

**Comment by huyszn** [comment]
@JobcenterTycoon Should I also report admiral domains like `steepscale.com` for sites with admiral anti-adb in the future?

**Comment by JobcenterTycoon** [comment]
Yes ping Yuki2718 when you see unblocked admiral domains. Yuki2718 will add admiral domains to EasyPrivacy.

**Comment by Yuki2718** [comment]
Please also notify @pgl

**Comment by pgl** [comment]
Thanks, added `steepscale.com`.

**Pull request merged**
