### PR TITLE
Update latimes.com filters

### PR DESCRIPTION
**Pull request by ryanbr**
`https://www.latimes.com` google funding and metering fix.

### URL(s) where the issue occurs

Updates 2 issues with latimes, googlefunding warning and the metering script.

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Brave
- uBlock Origin version: 1.29.2

### Notes

Can adjust the commit, just modifying existing placeholders.

### CODE REVIEW

**Comment by mapx-** [comment]
Did you get `visibility, 1000` logging the scriptlet ?
`latimes.com##+js(nosiif)`

**Comment by ryanbr** [comment]
Sure, that'll work. I just used existing GF snippets.

**Comment by okiehsch** [comment]
Thx.

**Comment by llacb47** [comment]
`metering fix`

We don't fix article metering in uAssets...

**Pull request merged**
