### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by MasterKia**

### CODE REVIEW

**Comment by MasterKia** [comment]
@JobcenterTycoon

**Comment by JobcenterTycoon** [comment]
This fix not fully prevent the anti adblock message

Unbenannt

**Comment by JobcenterTycoon** [comment]
Please ignore my last commit. Lol pretty new idea to place

`soft98.ir###header:after:style(content: "در صورت دیدن هرگونه مشکل در سایت و یا پیغامی برای غیرفعال کردن افزونه حذف تبلیغات، کافیست به تنظیمات افزونه مسدودسازتان بروید و لیست PersianBlocker و Quick-Fixes را بروز کنید." !important; color: #ffffff !important; visibility: visible; font-size: large !important;)`

**Comment by MasterKia** [comment]
I got that idea from @DandelionSprout's [RickrollLinkIdentifier](https://github.com/DandelionSprout/adfilt/blob/master/RickrollLinkIdentifier.txt#L8).

**Comment by MasterKia** [comment]
The problem is, I'm yet to find a **_stable_** place to attach that to (meaning they could change "header" to "hea1der").

I tried attaching it to `##[src*="file.soft98.ir"]` but the ":remove()" makes that pointless.

Maybe I should try "xpath".

**Comment by JobcenterTycoon** [comment]
Instead of using the id you can attach it to the `<header>` element

**Comment by MasterKia** [comment]
That sounds awesome.

**Comment by JobcenterTycoon** [comment]
To select a html tag do `example.com##tag`

**Comment by MasterKia** [comment]
But there is no `<header>` in site source.

**Comment by JobcenterTycoon** [comment]
Search for `<header` without `>` because many times tags contains attributes.

I see there are multiply header tags. To limit the selection to the header you want `soft98.ir##header[id]` works or `soft98.ir##header:not([class="card-header"])`

**Comment by MasterKia** [comment]
It's going to the background.
I can't bring it to front even using "overflow: visible !important; z-index: -1 !important; position: relative !important;".

`soft98.ir##header[id]:before:style(content: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" !important; color: #ffffff !important; visibility: visible; font-size: large !important; overflow: visible !important; z-index: -1 !important; position: relative !important;)`

**Comment by JobcenterTycoon** [comment]
because you used `:before` instead of `:after`

**Comment by MasterKia** [comment]
Yes that works fine.
But one of my ":remove()" is removing this attachment, I'm gonna investigate now.

**Comment by MasterKia** [comment]
No it's not.

**Comment by MasterKia** [comment]
Get rid of all my filters and add `||file.soft98.ir^$all` to get this [ugly black anti-adb rectangle](https://user-images.githubusercontent.com/17685483/183081209-4be85f1f-7276-4cfc-ad19-5076090fad15.png).

The tag is `##.show.t3oast-lg.fade.t3oast`.
I want to attach a message to this so I need an stable filter (`##.show.t3oast` is unstable).

I used xpath and made:
`soft98.ir##:xpath(/html/body/div[8][contains(text(),"F5")])`

The problem is, this rule doesn't accept `:before:style(content: "...")`.


==============
https://user-images.githubusercontent.com/17685483/183081978-b4a788c8-e164-4f1d-814f-61bca6852a5b.png
I have another idea: using `:matches-css(transition: ...)`.

But it doesn't aceept `:after:style(content: "...")` either.

**Comment by JobcenterTycoon** [comment]
There is no stable filter. Better to wait until they react

**Comment by MasterKia** [comment]
Their reaction so far was changing "t2oast" to "t3oast".

There other filters are stable because they can't change "file.soft98.ir" or "instagram.com".

**Comment by JobcenterTycoon** [comment]
There is already a message for the users

**Comment by MasterKia** [comment]
You're right.
I'm preparing for when they pull a trick for removing that message.

**Comment by MasterKia** [comment]
They circumvented the message.

**Comment by MasterKia** [comment]
<details><summary>Code</summary>

```js
, 1e4))
}
);
setInterval(function() {
    t(".c1e1y2-link img,.c1e1y2 a,.text-center a,.text-center,.col-13 a,.col-14 a,.card,.card-header").each(function() {
        for (var i = this.attributes, n = i.length - 1; n >= 0; n--) "" !== i[n].value && "style" !== i[n].name || t(this).r3moveAttr(i[n].name)
    });
    t(".c1e1y2-min,header").each(function() {
        (getComputedStyle(this, "::before").getPropertyValue("content") || getComputedStyle(this, "::after").getPropertyValue("content")) && t(this).addClass("he2ader", "he2ader")
    })
}, 100);
u.set("query", t);
u.set("$", function() {});
n.Ajax = g;
n.Captcha = or;
n.Config = f;
n.Cookie = ei;
n.Loading = sr;
n.t4oast = p;
n.Viewport = ht;
```
</details>

How can I defuse "setInterval" or "getComputedStyle"?
`##+js(nosiif)` does log that to console but these don't work:
`##+js(nosiif, , 100)`
`##+js(nosiif, (), 100) `
`##+js(nosiif, function(), 100)`
`##+js(nosiif, /^/, 100)`

**Comment by MasterKia** [comment]
Investigating into their anti-adb, I saw that they have made a class named "clean" and have added it to serveral attach points to prevent my attachments.

`##+js(rc, clean, *, stay)` results in a funny arm race, if you open Inspect element you can see the "clean" class getting removed by uBO then instantly getting added again by their anti-adb.

**Pull request merged**
