### PR TITLE
Add fingerprinting honeypots to privacy list

### PR DESCRIPTION
**Pull request by Kurtoid**
### URL(s) where the issue occurs
copyhomework.com
coursecopy.com
quiztoolbox.com
quizlookup.com
studyeffect.com
testbooksolutions.com

#### example URL
`https://studyeffect.com/qscjmrtzrt-2018-10-27-corpus-study-13-14-for-computer-engineering/`
### Describe the issue
No major visual issues. Sites track users with server-side code and Inspectlet, **without any visible disclaimer or privacy policy!** Since tracking is done server side, the best mitigation is to prevent the site from loading in the first place, hence the proposed list items.
Minor annoyances: Sites auto-play sounds on button press, depending on how the site was accessed (depends if accessed through Google Search or direct link)
 
These honeypot sites are run by Honorlock, and are implementations of patent US9881516B1. By statements from the company and the patent, the sites intent to collect as much client information as possible with the intention of **matching users to personally identifiable information.**
### Screenshot(s)

Imgur screenshot https://imgur.com/a/GPvc7jF
### Versions

- Browser/version: Firefox 81.0.2, Ubuntu 18.04
- uBlock Origin version:  1.30.6

### Settings

- added above sites to user list

### CODE REVIEW

**Comment by ryanbr** [comment]
@Kurtoid  how did you find these sites? and is there more?

**Comment by Kurtoid** [comment]
We initially found them by looking up the listed domains from their patent with archive.org, then used Google to find the new domains. We found the rest by making a Google dork that looks for some of their custom JS. We later found that you can confirm their Honorlock ownership by querying the wordpress author (eg: https://coursecopy.com/author/honorlock/ - this takes about 2 minutes to load though. IDK where the bottleneck is).

https://github.com/Kurtoid/honorlock-honeypot-list

**Comment by Kurtoid** [comment]
They don't strictly _need_ to be added to any lists, but I just wanted to get the word out there that they do this without warning unsuspecting users.

**Comment by ryanbr** [comment]
I think this would be more appropriate in the malware domains list

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d81149b11306bb1424fc11cd6668d454433a73c1

**Comment by gwarser** [comment]
Does it work at all without soft/add-on being installed on user computers?

**Pull request closed without merging**
