### PR TITLE
Update https://github.com/uBlockOrigin/uAssets/issues/11667

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`https://chillx.top/v/E0lUaqOEyLBb/`

### Describe the issue

popup ads

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox desktop stable
- uBlock Origin version: 1.41.8

### Settings

-  uBO's default settings

### CODE REVIEW

**Comment by Yuki2718** [comment]
@ghajini It seems at least `||duellosheliced.com^` is for badware. What about the rest two I don't see?

**Comment by ghajini** [comment]
those were revolving adservers &
they are blocked by my av realtime protection,so added

**Comment by Yuki2718** [comment]
I see `duellosheliced.com` only in popup. I'll move them to badware with `$all` added.

**Comment by ghajini** [comment]
`popup` request `duellosheliced.com` can be prevented by filtering popup request for
regex added to fix `https://github.com/easylist/easylist/issues/6476`

**Comment by ghajini** [comment]
i have seen some cases where i fixed using `nowoif` filter but some unknown websites really has fake buttons which when clicked leads to ads(regex rule can prevent that)
(i have not saved those websites)

**Comment by ghajini** [comment]
@Yuki2718 sorry to disturb you
`https://ww13.online123movies.live/watch-the-cursed-2022-full-movie-free-123movies-11901.html`

clicking play leads to popup request which can be blocked by regex
`/^https?:\/\/(?:[a-z]{2}\.)?[0-9a-z]{7,16}\.(?:com|pw|site)\/[a-z](?=[0-9a-z]{0,15}[A-Z])(?=[a-z]{0,15}[0-9A-Z])[0-9a-zA-Z]{10,16}\/(?:[1-4]\d{4}|[4-9]\d{3})(\?_=\d+)?$/$popup,3p,match-case`

common ad server `||izitrckr.com^`

**Pull request merged**
