### PR TITLE
Fix #933 in new annoyances list

### LINKED ISSUE #933: holyclock.com bad redirect
### URL(s) where the issue occurs

`http://www.leava.fr/`

### Describe the issue

On Saturday, access to this website is blocked and redirects to holyclock.com.
I do not consider that blocking a website, whatever the reason is, is a good thing.

```js
                <!-- HolyClock.com <HEAD> code for leava.fr -->
        <script type="text/psajs" orig_index="6">//<![CDATA[
_holyclock_id="bb85a1671890f6643970029eb14cb08e";_holyclock_tag='<s'+'cript src\x3d"//www.holyclock.com/holyclock.js?'+Math.floor(+new Date/864E5)+'">\x3c/script>';null!==document.cookie.match(/(?:^|;)\s*_holyclock_qr=\s*\w/)&&null===window.location.hash.match(/#holyclock=qr(?=#|$)/)&&document.write(_holyclock_tag);
//]]></script>
        <!-- HolyClock.com <HEAD> code for leava.fr -->
```

### Versions

- Browser/version: Chrome Version 62.0.3202.94 x64
- uBlock Origin version: v1.14.20

### Notes

Adding `||holyclock.com^$third-party` in **My Filters** fixes the issue.

### PR DESCRIPTION
**Pull request by HLFH**
On Dec 17, 2017, the new annoyances list has been created by @gorhill.
So #933 can be fixed. https://github.com/uBlockOrigin/uAssets/issues/933#issuecomment-350466024

### CODE REVIEW

**Comment by gorhill** [comment]
This is an annoyance for _you_, but that this is an annoyance for everybody is arguable -- there is subjectivity involved here, and I rather not have such filter in a list here.

**Comment by HLFH** [comment]
@gorhill Not only for me I guess.
notonlyforme
Someone informed me that you've released an _annoyances_ list.

**Comment by gorhill** [comment]
Yes ok, if the site really wants to prevent access on specific days, than it should just stop serving the pages server-side rather than serve them in the first place while making them difficult to access with client-side code.

**Comment by HLFH** [comment]
> it should just stop serving the pages server-side rather than serve them in the first place while making them difficult to access with client-side code

I've sent them an email to inform them, then.

**Pull request merged**
