### PR TITLE
Create .gitattributes aka hightlighter (Linguist)

### PR DESCRIPTION
**Pull request by krystian3w**
Hightlighter based on https://github.com/github/linguist/pull/5968

Possible see on: https://github.com/ameshkov/VscodeAdblockSyntax/blob/master/test_rules.txt

https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes

### CODE REVIEW

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, can you check this?

**Comment by MasterKia** [comment]
https://github.com/uBlockOrigin/uAssets/pull/14699

**Comment by krystian3w** [comment]
Closed in favour #14699

**Comment by gorhill** [comment]
> Possible see on: https://github.com/ameshkov/VscodeAdblockSyntax/blob/master/test_rules.txt

This filter below is valid in uBO, it will convert to ASCII at compile time:

    пример.рф##banner

I think it's fair to let filter list maintainers use readable domain names.

**Comment by scripthunter7** [comment]
@gorhill Yes - most adblockers use the punycode library (I'm not sure about ABP). The unicode domain is a known issue and will be allowed in the next version.

**Comment by krystian3w** [comment]
@scripthunter7 I detected super long lines lost highlight: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/9a59b9c41cf5cfa8faedf570bd74408985f1a542/PPB/uBO_AG/popupy_suplement.txt#L5

I think uBo have similar long lines.

**Comment by scripthunter7** [comment]
@krystian3w https://github.com/github/linguist/discussions/6063

**Pull request closed without merging**
