### PR TITLE
Block Criteo tracking on tagesspiegel.de

### PR DESCRIPTION
**Pull request by ryanbr**
### URL(s) where the issue occurs
**Visiting:** `https://www.tagesspiegel.de/gesellschaft/panorama/coronavirus-weltweit-so-unterschiedlich-gehen-die-laender-mit-dem-virus-um/25595076.html`

### Describe the issue

We're blocking the following:

`<script type="text/javascript">`
`var Criteo = Criteo \|\| {};`
`Criteo.events = Criteo.events \|\| [];`
`Criteo.events.push(function() {`
`Criteo.DisplayAcceptableAdIfAdblocked({`
`"zoneid": 640113,`
`"width": 160,`
`"height": 600,`
`"containerid": "crt-sky-right",`
`"callbacksuccess": function() { adslotFilledByCriteo('sky-right', true); }`
`});`
`});`
`</script>`

### Versions

- Browser/version: Brave
- uBlock Origin version: 1.24.4

### CODE REVIEW

**Comment by uBlock-user** [comment]
Criteo is already blocked, so what difference does this make ?

**Comment by ryanbr** [comment]
Stops the inline scripts? Looking at the privacy aspect here.

**Comment by uBlock-user** [comment]
> Stops the inline scripts?

Stopping or not stoping the inline-script doesn't stop the website from making a connection attempt to `static.criteo.net`, so all this filter does is stop the execution of this script.

**Comment by ryanbr** [comment]
nvm. I'll push this to my own list.

**Pull request closed without merging**
