### PR TITLE
Clear tracking parameters

### PR DESCRIPTION
**Pull request by shenzhiming88**
There are many tracking parameters on this page, and these rules can clean them up
A test link `https://www.bilibili.com/video/BV1h54y1x7Xe?p=1&share_medium=android&share_plat=android&share_session_id=5b1739bd-fc0a-472f-bceb-ef87073ff6ac&share_source=QQ&share_tag=s_i&timestamp=1629362676&unique_k=y0yWTB`
Refence: https://github.com/the1812/Bilibili-Evolved/blob/master/src/utils/url-params-clean.ts
(The function of this file is to clean up the trace parameters)

### CODE REVIEW

**Comment by shenzhiming88** [comment]
I don't know how to put these parameters on the same line, so I split them into many different lines (I would like to be able to use `|` for splitting)

**Comment by iam-py-test** [comment]
@shenzhiming88 try using https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt

**Comment by shenzhiming88** [comment]
@iam-py-test Thank you. However, I would prefer that the list that comes with uBO have these rules. More importantly, in China, I can't seem to open the GitHub download page directly (not sure if your rules provide a mirror)

**Comment by gorhill** [comment]
There is no list in uBO to deal with query parameters, it's best to submit to currently existing lists with that purpose, so as to not further burden filter list maintainers here.

**Comment by iam-py-test** [comment]
> 
> 
> @iam-py-test Thank you. However, I would prefer that the list that comes with uBO have these rules. More importantly, in China, I can't seem to open the GitHub download page directly (not sure if your rules provide a mirror)

1. Try using Tor Browser (https://torproject.org)
2. Try using https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt 

Or I can post the rules & you can copy them into your My Filters
I also can try rehosting them

Also, I just want to clarify that those filters are @DandelionSprout 's

**Comment by shenzhiming88** [comment]
However, I think these query parameters are also privacy related, so it would be better to add them to the Privacy list as well, I don't know what you are thinking about

**Comment by shenzhiming88** [comment]
> > @iam-py-test Thank you. However, I would prefer that the list that comes with uBO have these rules. More importantly, in China, I can't seem to open the GitHub download page directly (not sure if your rules provide a mirror)
> 
>     1. Try using Tor Browser (https://torproject.org)
> 
>     2. Try using https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt
> 
> 
> Or I can post the rules & you can copy them into your My Filters
> I also can try rehosting them
> 
> Also, I just want to clarify that those filters are @DandelionSprout 's

Tor Browser is also blocked by China's GFW
Although I have the ability to open this page, it's still too much trouble. I don't know if there is one that provides a way to open it in China

**Comment by iam-py-test** [comment]
> 
> 
> > > @iam-py-test Thank you. However, I would prefer that the list that comes with uBO have these rules. More importantly, in China, I can't seem to open the GitHub download page directly (not sure if your rules provide a mirror)
> > 
> > 
> > ```
> > 1. Try using Tor Browser (https://torproject.org)
> > 
> > 2. Try using https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or I can post the rules & you can copy them into your My Filters
> > I also can try rehosting them
> > Also, I just want to clarify that those filters are @DandelionSprout 's
> 
> Tor Browser is also blocked by China's GFW
> Although I have the ability to open this page, it's still too much trouble. I don't know if there is one that provides a way to open it in China

I know there are ways to get around the GFW and do this, but I don't know how

**Comment by iam-py-test** [comment]
@shenzhiming88 does this link work? 
https://iam-py-test.github.io/mirrors/LegitimateURLShortener.txt

**Comment by shenzhiming88** [comment]
@iam-py-test Yes. Thank you for your help!

**Comment by iam-py-test** [comment]
> 
> 
> @iam-py-test Yes. Thank you for your help!

@shenzhiming88 just glad I could help
I assume the link works?

**Comment by shenzhiming88** [comment]
> > @iam-py-test Yes. Thank you for your help!
> 
> @shenzhiming88 just glad I could help
> I assume the link works?

Yes. I can open it directly.

**Comment by iam-py-test** [comment]
@shenzhiming88 I will try to re-host some lists (including my own) for people who can't access GH.

**Comment by DandelionSprout** [comment]
>More importantly, in China, I can't seem to open the GitHub download page directly (not sure if your rules provide a mirror)

You can try with https://gitlab.com/DandelionSprout/adfilt/-/raw/master/AnnoyancesList. If I get confirmation that it works in PR-China, I'll make sure to ping / quasi-nag #1566 about adding more non-GitHub mirrors.

**Comment by shenzhiming88** [comment]
> 
> 
> > More importantly, in China, I can't seem to open the GitHub download page directly (not sure if your rules provide a mirror)
> 
> You can try with https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt. If I get confirmation that it works in PR-China, I'll make sure to ping / quasi-nag [uBlockOrigin/uBlock-issues#1566](https://github.com/uBlockOrigin/uBlock-issues/issues/1566) about adding more non-GitHub mirrors for other lists too.

I can open it. Thanks!

**Pull request closed without merging**
