### PR TITLE
Add some malicious websites

### PR DESCRIPTION
**Pull request by shenzhiming88**
- `kuaizip.com` Adware
- `zhuangjizhuli.com` Malware

### CODE REVIEW

**Comment by shenzhiming88** [comment]
@uBlock-user

**Comment by uBlock-user** [comment]
@shenzhiming88  VT report for exe from `zhuangjizhuli.com` ?

**Comment by shenzhiming88** [comment]
Hello!
image
I actually gave the address back to Kaspersky and they blacklisted the exe file with the page all together

> Hello,
> 
> The specified URL was added to our blocklist.
> Thank you for your help.

> Hello,
> 
> New malicious software was found in the attached F6E699CBBC295B881517C30C53ED3FB4>file:
> F6E699CBBC295B881517C30C53ED3FB4- Trojan.Win32.Agentb.kkjz
> Its detection will be included in the next update.
> Thank you for your help.

**Comment by uBlock-user** [comment]
@shenzhiming88 and VT report for .exe from `kuaizip.com` ?

**Comment by shenzhiming88** [comment]
@uBlock-user Hello!
网页捕获_26-7-2021_1614_www virustotal com

**Pull request merged**
