### PR TITLE
Fix cookie message overlay on obuvki.bg

### PR DESCRIPTION
**Pull request by ryanbr**
### URL(s) where the issue occurs

`https://www.obuvki.bg/goljam-damski-portfejl-guess-brightside-vy-slg-swvy75-80430-bla.html`

### Describe the issue

Fixes popup, and restores scroll.

### Screenshot(s)

obuvk

### Versions

- Browser/version: Brave
- uBlock Origin version: 1.31.2

### Settings

- [List here all the changes you made to uBO's default settings]

### CODE REVIEW

**Comment by krystian3w** [comment]
@mapx- that page have sister domains:

```js
[
  {
    "id": "1",
    "code": "default",
    "name": "eobuwie.pl",
    "url": "https:\/\/www.eobuwie.com.pl\/",
    "sortOrder": 1
  },
  {
    "id": "6",
    "code": "cz",
    "name": "eobuv.cz",
    "url": "https:\/\/www.eobuv.cz\/",
    "sortOrder": 2
  },
  {
    "id": "17",
    "code": "sk2",
    "name": "eobuv.sk",
    "url": "https:\/\/www.eobuv.sk\/",
    "sortOrder": 3
  },
  {
    "id": "11",
    "code": "ro",
    "name": "epantofi.ro",
    "url": "https:\/\/www.epantofi.ro\/",
    "sortOrder": 4
  },
  {
    "id": "12",
    "code": "hu",
    "name": "ecipo.hu",
    "url": "https:\/\/www.ecipo.hu\/",
    "sortOrder": 5
  },
  {
    "id": "14",
    "code": "ua",
    "name": "eobuv.com.ua",
    "url": "https:\/\/www.eobuv.com.ua\/",
    "sortOrder": 6
  },
  {
    "id": "7",
    "code": "ru",
    "name": "eobuv.com",
    "url": "https:\/\/www.eobuv.com\/",
    "sortOrder": 7
  },
  {
    "id": "15",
    "code": "bg",
    "name": "obuvki.bg",
    "url": "https:\/\/www.obuvki.bg\/",
    "sortOrder": 8
  },
  {
    "id": "8",
    "code": "de",
    "name": "eschuhe.de",
    "url": "https:\/\/www.eschuhe.de\/",
    "sortOrder": 9
  },
  {
    "id": "5",
    "code": "en",
    "name": "efootwear.eu",
    "url": "https:\/\/www.efootwear.eu\/",
    "sortOrder": 10
  },
  {
    "id": "13",
    "code": "lt",
    "name": "eavalyne.lt",
    "url": "https:\/\/www.eavalyne.lt\/",
    "sortOrder": 11
  },
  {
    "id": "16",
    "code": "gr",
    "name": "epapoutsia.gr",
    "url": "https:\/\/www.epapoutsia.gr\/",
    "sortOrder": 12
  },
  {
    "id": "18",
    "code": "se",
    "name": "eskor.se",
    "url": "https:\/\/www.eskor.se\/",
    "sortOrder": 13
  },
  {
    "id": "20",
    "code": "it",
    "name": "escarpe.it",
    "url": "https:\/\/www.escarpe.it\/",
    "sortOrder": 14
  },
  {
    "id": "19",
    "code": "es",
    "name": "zapatos.es",
    "url": "https:\/\/www.zapatos.es\/",
    "sortOrder": 15
  },
  {
    "id": "21",
    "code": "fr",
    "name": "chaussures.fr",
    "url": "https:\/\/www.chaussures.fr\/",
    "sortOrder": 16
  },
  {
    "id": "22",
    "code": "ch_de",
    "name": "eschuhe.ch\/de",
    "url": "https:\/\/www.eschuhe.ch\/de\/",
    "sortOrder": 17
  },
  {
    "id": "24",
    "code": "ch_it",
    "name": "eschuhe.ch\/it",
    "url": "https:\/\/www.eschuhe.ch\/it\/",
    "sortOrder": 18
  },
  {
    "id": "23",
    "code": "ch_fr",
    "name": "eschuhe.ch\/fr",
    "url": "https:\/\/www.eschuhe.ch\/fr\/",
    "sortOrder": 19
  },
  {
    "id": "25",
    "code": "hr",
    "name": "ecipele.hr",
    "url": "https:\/\/www.ecipele.hr\/",
    "sortOrder": 20
  }
]
```

**Comment by mapx-** [comment]
just prepare a PR (if you checked out similar filters are working for all those pages)

**Comment by krystian3w** [comment]
Poland page no longer block scroll, also use new name for element: `##.e-consents-alert`

fyi @ryanbr / @mapx- 

to exclude GDPR new text should read @okiehsch / @uBlock-user (experts to find out if it's just a cookie bar or gdpr)

**Comment by ryanbr** [comment]
What are you talking about @krystian3w  What site, what scrollbar issue.

**Comment by mapx-** [comment]
I guess it's about `eobuwie.com.pl`
see https://github.com/ryanbr/uAssets/commit/51c6d286b3a0cbfb9e1fa8a76a0b60d72aa697d3

**Comment by krystian3w** [comment]
I mean we can revert this pr due pages no longer scroll and use different name for cookie bar.

**Comment by ryanbr** [comment]
https://www.eobuwie.com.pl/ has a scroll bar, I see a consent block. And works as intended.

eobu

**Comment by krystian3w** [comment]
No works, pop-up no longer exist also repair scroll if works without uBo is pointless.

**Pull request merged**
