### PR TITLE
gmarket.co.kr - anti right click

### PR DESCRIPTION
**Pull request by green1052**
test in [here](https://item.gmarket.co.kr/Item?goodscode=1598495491&ver=637870315524544233)

### CODE REVIEW

**Comment by mapx-** [comment]
maybe

```
gmarket.co.kr##+js(set, document.oncontextmenu, noopFunc)
gmarket.co.kr##+js(set, document.onmousedown, noopFunc)
```

**Comment by green1052** [comment]
> maybe
> 
> ```
> gmarket.co.kr##+js(set, document.oncontextmenu, noopFunc)
> gmarket.co.kr##+js(set, document.onmousedown, noopFunc)
> ```

i think `||script.gmarket.co.kr/js/itemdweb/ItemBase.js` is better than

ItemBase.js script is just anti right click

**Comment by krystian3w** [comment]
No blocked in Fanboy Annoyances/AdGuard Annoyances by network filter?

**Comment by green1052** [comment]
> 

yes

**Pull request closed without merging**
