### PR TITLE
A: ocremix.org

### PR DESCRIPTION
**Pull request by MisterSheeple**
### URL(s) where the issue occurs

`https://ocremix.org/remix/OCR03969` for example

### Describe the issue

Before:

image

After:

image

### CODE REVIEW

**Comment by MisterSheeple** [comment]
I'm new to this, so if there's a better way this can be done, please let me know. I closed this because I was thinking of blocking the widget by checking for a "Promotion" string in there, so in case the widget were to ever disappear, it wouldn't cause breakage. But I can't figure out how to do that, so let me know if my current implementation is fine or if I can improve upon it, and if so, how.

**Comment by BlazeFTL** [comment]
@MisterSheeple Its Always Better To Pinpoint Your Target Element
Ex:
`##div.widget-neutral.widget:has-text(Promotion)`
nth-of-child Is Not Ideal And Can Cause Breakage In Future
Take A Look Here `https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters`

**Comment by MisterSheeple** [comment]
Thank you, should be better now.

**Comment by mapx-** [comment]
report at easylist repo https://github.com/easylist/easylist/issues

**Pull request closed without merging**
