### PR TITLE
Send.cm,skyve.io update

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://send.cm/6ea8b5th9ht7` Empty spaces
`https://skyve.io/6fcrzrlah6qx` popup,fake button,empty space

### CODE REVIEW

**Comment by BlazeFTL** [comment]
IDK If Empty Spaces Should Be Addressed In UBO Or Not...If Not Then Remove
Send.cm Please...

**Comment by mapx-** [comment]
we already have uBO specific filters for that site, so we could add other ones

**Comment by D4niloMR** [comment]
that doesn't seem to be a placeholder, just a site design

**Comment by BlazeFTL** [comment]
Seemed like wasted space...i dont mind remove it

**Comment by D4niloMR** [comment]
yeah but why remove it on ublock filters?

**Pull request merged**
