### PR TITLE
update #19976 youtube.com

### PR DESCRIPTION
**Pull request by ajayyy**
dummy object (in 000d7185):

image

real object:

image

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
@stephenhawk8054

**Comment by ajayyy** [comment]
Sorry for the force pushes, forgot to add the `.*?` originally.

**Comment by stephenhawk8054** [comment]
@ajayyy Ah sorry, I didn't see your last edit. In case you want to use `,` inside regex, you can wrap the arguments inside `' '`

**Comment by ajayyy** [comment]
ah, I see. The `.*` should cover the rest of the chars in this case though, thanks!

**Comment by stephenhawk8054** [comment]
Yeah, your last edit should also work too, without the need of `' '`

**Pull request closed without merging**
