### PR TITLE
Add scam domains

### PR DESCRIPTION
**Pull request by iam-py-test**
### URL(s) where the issue occurs

```
steamkeygiveaway.net
```

### Describe the issue

This is an (unblocked) scam website. I have tested and this domain isn't blocked

### Screenshot(s)

image
image
image
image
image

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- Advanced user mode: ON
- Dynamic filtering mode: Hard mode
- Filterlists:
Built-in: (5/5)
Ads: (3/3)
image
image

### Notes

More screenshots at https://github.com/iam-py-test/investigations/blob/main/2021/11/25/1.md

### CODE REVIEW

**Comment by shenzhiming88** [comment]
On a side note, `Fanboy's Annoyance` should include the `Easylist Cookie`, so I don't see the need to subscribe to the `Easylist Cookie`.

**Comment by Yuki2718** [comment]
No full URLs in this issue and your link has all URLs of any requests, which has to waste our time. Report **full** URLs of main documents.

**Comment by Yuki2718** [comment]
Of note redirect-path way differs on my end, `fasterfiles.net` => `secureclickers.com` (blocked by EL, has to allow) => `take.yunosurveys.com`.  Such behavior is very common. Another reason is if generic patter can be found, it's better to use it than adding short-life domain tho not always possible.

**Comment by iam-py-test** [comment]
> No full URLs in this issue and your link has all URLs of any requests, which has to waste our time. Report **full** URLs of main documents.

Just `https://steamkeygiveaway.net/` needed. Be sure to use a VM and VPN

**Comment by Yuki2718** [comment]
See above.

**Comment by iam-py-test** [comment]
Probably either random or by location.
At least blocking some of the domains later in the redirect chain has an effect, as those seem to be reused

**Comment by Yuki2718** [comment]
Do you guarantee you'll cleanup all these domain once expired?

**Comment by iam-py-test** [comment]
> Do you guarantee you'll cleanup all these domain once expired?

Not really, but I will try

**Comment by Yuki2718** [comment]
Since you're relatively new as a filter maintainer, I can see where you're from. But mainaing filter list is not only about adding staff, but also about keep removing and adjusting for long term. We want to minimize the maintanance cost. And if you can provide full URLs of bad pages unblocked by the current filters, it greatly saves our time to check - we don't add domain just because someone suggested to do so.

**Comment by iam-py-test** [comment]
As stated, just going to the homepage and clicking on anything under "action games" is enough

**Comment by Yuki2718** [comment]
> As stated, just going to the homepage and clicking on anything under "action games" is enough

Nothing happens on my end other than normal page move.

**Comment by iam-py-test** [comment]
> > As stated, just going to the homepage and clicking on anything under "action games" is enough
> 
> Nothing happens on my end other than normal page move.

I meant any of the links.

**Comment by Yuki2718** [comment]
At best it shows Claim key! popup, and I don't have the key.

**Comment by iam-py-test** [comment]
> At best it shows Claim key! popup, and I don't have the key.

Ok, I am horrible at writing descriptions. Very sorry.
Hope this is better:
- Go to the homepage
- Click on one of the links under "action games"
- Click the "Claim key" button
- Enter fake email and details
- Click "Claim key"
- Wait for redirect to page

**Comment by Yuki2718** [comment]
Tested ALL the links under ACTION GAMES.

**Comment by iam-py-test** [comment]
> Tested ALL the links under ACTION GAMES.

Did you follow the instructions above? If it doesn't work, I'll go back and see if I can verify (I have the VM off at the moment)

**Comment by Yuki2718** [comment]
Yeah, that is one thing - Steps to reproduce is mandatory in cases like this. But I mean, if you provided full URLs, this PR would have already be merged if good.

**Comment by Yuki2718** [comment]
I can confirm only (the last one is not in your PR, you can either add or leave it):
```
||fasterfiles.net^$all
||steamkeygiveaway.net^$all
||yunosurveys.com^$all
```

**Comment by iam-py-test** [comment]
> Yeah, that is one thing - Steps to reproduce is mandatory in cases like this. But I mean, if you provided full URLs, this PR would have already be merged if good.

Very sorry.

**Comment by Yuki2718** [comment]
No need to apologize, you're doing very good contribution to thie repo and other. I'll search for the rest of URLs I can't confirm later from your page, but will be appreciated if you can.

**Comment by iam-py-test** [comment]
I have updated to only add those that you verified, and added the additional one to both this PR and my lists

**Comment by iam-py-test** [comment]
@Yuki2718 thanks!

**Comment by Yuki2718** [comment]
All right, I might check the rest domain if I could find time (have many tasks on AG repo so may not be able to).

**Comment by iam-py-test** [comment]
One recommendation: Is there a way that a last-updated date can be added to the badware list?

**Comment by Yuki2718** [comment]
> Is there a way that a last-updated date can be added to the badware list?

Do you mean things like `! Version: 25November2021v1-Beta`? Then I guess the answer is no. It increase workload of volunteers while is not necessary. Anyone who is curious about the last-updated date can check GH.

**Pull request merged**
