### PR TITLE
Fix https://github.com/AdguardTeam/AdguardFilters/issues/54259

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/AdguardTeam/AdguardFilters/issues/54259

### CODE REVIEW

**Comment by mapx-** [comment]
chrome + jpn list => even for desktop devices selecting text is disabled

**Comment by Yuki2718** [comment]
> 
> 
> chrome + jpn list => even for desktop devices selecting text is disabled

I can copy even without any blocker.
sanspo

IP dependent?

**Comment by mapx-** [comment]
tested FF / chrome desktop => select is blocked, so just remove mobile condition

**Comment by mapx-** [comment]
I tested the original link on adguard repo
`https://www.sanspo.com/smp/geino/news/20200423/geo20042315420032-s.html`

**Comment by Yuki2718** [comment]
> 
> 
> I tested the original link on adguard repo
> `https://www.sanspo.com/smp/geino/news/20200423/geo20042315420032-s.html`

Confirmed, the link leads you to smartphone page even on desktop client. I'll remove if_env directive.

**Comment by mapx-** [comment]
thx

**Pull request merged**
