### PR TITLE
seemingly redundant

### PR DESCRIPTION
**Pull request by Infrastructural**
Seemingly made redundant by presence of
```
rte.ie
tubitv.com
etonline.com
```
in an allowing filter or whatever it would be called from EasyList

### CODE REVIEW

**Comment by ghajini** [comment]
why you are adding back those adservers which are there in EL

**Comment by Infrastructural** [comment]
I didn't add them lol, they got added back

**Comment by Infrastructural** [comment]
So, should I remove them in this PR or should I close it?

**Comment by Infrastructural** [comment]
https://github.com/uBlockOrigin/uAssets/pull/14578

**Pull request closed without merging**
