### PR TITLE
Add ads.listonic.com to whitelist for Unbreak list

### PR DESCRIPTION
**Pull request by GregPK**
### URL(s) where the issue occurs

https://ads.listonic.com/

### Describe the issue

This whitelists my company website https://ads.listonic.com/. We are producing mobile applications and we offer ads in our aps. Ads.listonic.com is B2B website for businesses who want to cooperate with us and buy ads to promote their products.

### Screenshot(s)

image

### Versions

Not relevant

### Settings

- None

### Notes

One thing I'm uncertain of: we also are petitioning EasyList to change the `badfilter` from the line above to include this domain in the whitelist. Will a change in EasyList break the `badfilter` marking here and will have to be updated?

### CODE REVIEW

**Comment by agatazur** [comment]
Company website https://ads.listonic.com/ is still being blocked by uBlock.
The issue appears when redirected from https://tylkofmcg.pl/ to https://ads.listonic.com/ and when we try to open links sent via Gmail. Links from social media open easily.
We requested adding https://ads.listonic.com/ to whitelist a few months ago.

**Comment by okiehsch** [comment]
The site is not blocked by as you can see by simply clicking your listonic link.

> The issue appears when redirected

I assume you get redirected through a tracking link which is blocked, any way for me to reproduce, i.e. can you sent me a test link.

**Comment by agatazur** [comment]
We get redirected by SUMO plugin and it's a deep link that gets blocked. We can't check the link, it's being changed by plugin.
If you haven't had any similar issues then we will try to fix it contacting SUMO directly.

**Comment by okiehsch** [comment]
> If you haven't had any similar issues

I am not usually using the site, I don't see any issues browsing it but I don't have an account, so that's all I can test.

**Pull request closed without merging**
