### PR TITLE
Fix juragan-anime.net

### PR DESCRIPTION
**Pull request by nik2143**
This fix ads on juragan-anime.net

### CODE REVIEW

**Comment by mapx-** [comment]
@Alex-302

`juragan-anime.net##+js(aopr, MANGO)`

**Comment by Alex-302** [comment]
@mapx- does not URL blocking rule enough?

**Comment by mapx-** [comment]
sure, just in case they change the domain ..

**Comment by Alex-302** [comment]
Ok, will check later.

**Pull request closed without merging**
