### PR TITLE
Badware

### PR DESCRIPTION
**Pull request by shenzhiming88**
The software does not work properly even after payment, cheating users of their property
See: `https://www.zhihu.com/question/21406655/answer/658774547`

### CODE REVIEW

**Comment by okiehsch** [comment]
>  does not work properly even after payment

That is out of scope.

**Comment by uBlock-user** [comment]
Site issue, not badware.

**Comment by shenzhiming88** [comment]
> > does not work properly even after payment
> 
> That is out of scope.

So, only deal with malware?

**Comment by okiehsch** [comment]
And with bundled Adware or fake sites etc.
Not with a software that does not work properly.

**Comment by shenzhiming88** [comment]
> And with bundled Adware or fake sites etc.
> Not with a software that does not work properly.
> Allegedly.

However, the software requires users to pay to use the function, but the function is still not available after payment, I think this is fraud

**Comment by uBlock-user** [comment]
@shenzhiming88 Contact with site admin and take it up with him ?

**Comment by shenzhiming88** [comment]
> @shenzhiming88 Contact with site admin and take it up with him ?

According to the description of `https://www.zhihu.com/question/21406655/answer/658774547` and `https://www.zhihu.com/question/52157612/answer/658743763`, they refused to deal with this issue and abused paying users

**Comment by shenzhiming88** [comment]
@uBlock-user

**Comment by uBlock-user** [comment]
So the admin is acting scummy, still out of scope of this list.

**Pull request closed without merging**
