### PR TITLE
upd #20095

### PR DESCRIPTION
**Pull request by ABetterWeb**
nsfw

detection => overlay

### CODE REVIEW

**Comment by ABetterWeb** [comment]
also, it looks like the `rmnt` scriptlet for this site may be outdated (anyway no ad)

**Comment by stephenhawk8054** [comment]
It still displays the overlay if I refresh without bypassing the cache. Does this work?

```adb
truyen-hentai.com###aabnode
```

**Comment by ABetterWeb** [comment]
@stephenhawk8054 I don't get that on Firefox, but your filter works. How about still addressing `window.aab` though?

**Comment by stephenhawk8054** [comment]
Ok I'll update it

**Pull request merged**
