### PR TITLE
(fix) anti adblock measures

### PR DESCRIPTION
**Pull request by Alex4567890**
fixes for https://github.com/AdguardTeam/AdguardFilters/issues/76572 & https://github.com/AdguardTeam/AdguardFilters/issues/76561

### CODE REVIEW

**Comment by Alex4567890** [comment]
Should the name of the commit or whatever it is?

**Comment by wout-codes** [comment]
-_-

**Comment by Alex4567890** [comment]
@wout-codes why are you disliking? I'm attempting to help.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a022238204cd08cc5dc23b2ee8903e8593aa2e4c

**Comment by okiehsch** [comment]
@wout-codes any particular reason for your thumbs down under every post that is referenced to Adguard?

**Comment by wout-codes** [comment]
> @wout-codes any particular reason for your thumbs down under every post that is referenced to Adguard?

No. I just don't like the uBO's syntax.

**Pull request closed without merging**
