### PR TITLE
Fix Multi Shorteners 

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://lksfy.com/jlmfm0olam`
`https://go.birdurls.com/ntqy9qolam`
`vlshort.com/3k7hc9olam`
`https://cut.lc/w6c8qpolam`
https://github.com/uBlockOrigin/uAssets/issues/20799

### CODE REVIEW

**Comment by BlazeFTL** [comment]
It Would Be Cat And Mouse Game...This Site Owner More Active Than DG😂

**Comment by JobcenterTycoon** [comment]
On the next update we can try `spoof-css`

**Comment by BlazeFTL** [comment]
Currently spoof-css only returns the value that we set but if it could return values directly from css then it might perform better...
##a[href*=".click"] Was Already Updated With Different Styles,Spoof But All Got Bypassed By Site Owner...I Dont Know What MasterKia's rpnt Filter Was Maybe You Can Try On This Site In Future..

Cause Here `##a[href*=".click"]` = DropGalaxy's `iframe` Style Filters...I Had To Update Whenever Site Owner Updated

**Comment by JobcenterTycoon** [comment]
MasterKia’s rpnt filter obtain the default real css and returning it to the site. With this MasterKia was able to bypass dragontea’s `spoof-css` detection. dragontea changed the style and then detect if the obtained `getComputedStyle` style also changed. This way to detect spoof-css is not uncommon.

See the full discussion: https://github.com/uBlockOrigin/uBlock-issues/issues/2618

**Comment by BlazeFTL** [comment]
@JobcenterTycoon Recheck...Site Owner Updated🤣

**Comment by JobcenterTycoon** [comment]
Done. Also blocked the linked badware domain and reported to different security vendors.

**Pull request merged**
