### PR TITLE
Xpshort,Gplinks Up

### PR DESCRIPTION
**Pull request by BlazeFTL**

### CODE REVIEW

**Comment by BlazeFTL** [comment]
@mapx- Was my this commit https://github.com/uBlockOrigin/uAssets/pull/22528/commits/2facb726e3f1a4894344a18aec41706086b03161 any issue ?

https://github.com/uBlockOrigin/uAssets/commit/32d1c6230717a36d6277911dd5c68977d1d977a6
Sir Reverted It...The Site Is Broken For More Than A Year Now Then I Guess If

**Comment by mapx-** [comment]
no issue, however the site is working even with that warning at the top

**Comment by BlazeFTL** [comment]
That warning is there for more than a year now...if it can hidden by ubo wouldn't it be beneficial for the users ?

He removed these two rules which are actually legit
```
savelinks.*##[href="https://pornx11.com/"]
savelinks.*##+js(acs, eval, replace)

**Comment by mapx-** [comment]
do you get any detection ? maybe on mobile ?

`##[href="https://pornx11.com/"]` => what is hidinh this filter ?

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/1647ec753cbe2399ed8937dff7acd25bcb3e2388

**Pull request merged**
