### PR TITLE
Removing duplications

### PR DESCRIPTION
**Pull request by kubalav**
Removed duplicated rules.

### CODE REVIEW

**Comment by mapx-** [comment]
@kubalav  could you indicate the duplicate for 
`||info^$script,third-party,domain=oload.info`

**Comment by kubalav** [comment]
.info^$script,third-party,domain=oload.tv|openload.co|streamango.com|streamcherry.com

**Comment by kubalav** [comment]
Updated PR

**Comment by mapx-** [comment]
thx

**Pull request merged**
