### PR TITLE
Update https://github.com/uBlockOrigin/uAssets/issues/3573

### PR DESCRIPTION
**Pull request by ghajini**
Firefox specific-ensure to run as early as possible

### URL(s) where the issue occurs
```
https://userscloud.com/tmui0a8fgg2h
https://userscloud.com/nf1x5liq6r6b
```

### Describe the issue

race condition when fresh visit of site=> crap loads,

on reload of page crap is prevented with current set of filters

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.38.6

### Settings

- uBO's default settings

### CODE REVIEW

**Comment by mapx-** [comment]
test 
`userscloud.com##+js(aopr, JSON.parse)`

**Comment by ghajini** [comment]
@mapx- already tested beforehand, not work

**Comment by mapx-** [comment]
@ghajini did you try removing the branches ? see @gwarser comment

**Comment by ghajini** [comment]
yess doing that only, 
completed

**Comment by gwarser** [comment]
Hopefully next pull request will be more clean :)

**Comment by gwarser** [comment]
Ahhh, you merged your own patches in the past instead of fetching from uAssets, where in uAssets patches were squashed/rebased without merge commit :/ History of your copy of the repo is different starting from first merge commit. Fixing this will rewrite all these newer commits, so it will probably be easier to just fork again clean version of uAssets.

**Pull request merged**
