### PR TITLE
Add recipe for megaphone.fm podcast embeds

### PR DESCRIPTION
**Pull request by saizai**

### CODE REVIEW

**Comment by uBlock-user** [comment]
uMatrix has already been archived, no reason to submit recipes anymore.

**Comment by saizai** [comment]
@uBlock-user what's its replacement, if any?

**Comment by uBlock-user** [comment]
https://github.com/geekprojects/nuTensor seems so

**Comment by saizai** [comment]
If https://github.com/uBlockOrigin/uAssets/blob/master/recipes/recipes_en.txt is totally deprecated, should it still be in this repo?

**Comment by uBlock-user** [comment]
There's an ongoing pull -- https://github.com/uBlockOrigin/uAssets/pull/8073

**Pull request closed without merging**
