### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by MasterKia**

### CODE REVIEW

**Comment by MasterKia** [comment]
@JobcenterTycoon

**Comment by MasterKia** [comment]
Wait.

**Comment by JobcenterTycoon** [comment]
Such breakage https://github.com/uBlockOrigin/uAssets/commit/9dcb9a15a491fb501a7f9997899391393a3bbcc4#r80549394 can’t be accepted. Users would disable the adblocker when they encounter such big breakage.

Also `##header[id]:has(.row):remove()` depend on a CSS name too.

**Comment by MasterKia** [comment]
That filter triggers the anti-adb anyway, hence the "Wait".

**Comment by MasterKia** [comment]
> and site owner know this

Then if site owner is such a nice person, maybe remove everything to make website look white and users think site itself is broken.

**Comment by MasterKia** [comment]
@JobcenterTycoon

**Comment by MasterKia** [comment]
@okiehsch

**Pull request merged**
