### PR TITLE
Update #1733

### PR DESCRIPTION
**Pull request by SMed79**
* http\://www.linkeasy.org/js/home/5282.js
* http://i.imgur.com/rXCH4G5.png

### CODE REVIEW

**Comment by mapx-** [comment]
pretty good for easylist

**Comment by mapx-** [comment]
@ryanbr

**Comment by SMed79** [comment]
So, why you have added `||hipercontas.com.br^` ??
The script from `linkeasy.org` is which open the popup !!

**Comment by mapx-** [comment]
the main issue there was the popup, fixed using 
`universeseries.org^$csp=script-src 'self' 'unsafe-inline' data: *.fbcdn.net *.facebook.com *.google-analytics.com`

the `hipercontas` filter was for the ads

**Pull request closed without merging**
