### PR TITLE
useless filter

### PR DESCRIPTION
**Pull request by Alex4567890**

### CODE REVIEW

**Comment by mapx-** [comment]
still useful

image

**Comment by Alex4567890** [comment]
> 
> 
> still useful
> 
> image

I'm pretty sure it's not about the ad blocker.

**Comment by Alex4567890** [comment]
Actually, you're right. That thing does not appear with uBlock Origin.

**Comment by uBlock-user** [comment]
When the fix for anti-adblock is added, everything else is also fixed together.

**Pull request closed without merging**
