### PR TITLE
Fix ads on boards.net sites

### PR DESCRIPTION
**Pull request by ryanbr**
### URL(s) where the issue occurs

Fixes ads on 
`https://xmenagerie.proboards.com/thread/1812/introduction`
`https://crossports.freeforums.net/thread/641/links-pl-message-boards`
`https://trongridlines.boards.net/thread/2/welcome-gridlines-programs`

### Describe the issue

https://forums.lanik.us/viewtopic.php?f=62&t=44538

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: `Brave/Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)`
- uBlock Origin version: `1.24.4`

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

`<script>
            window.runAntiAdBlock = 1;
        </script>`

### CODE REVIEW

**Comment by uBlock-user** [comment]
@ryanbr Why `window.runAntiAdBlock` instead of `runAntiAdBlock` ?

window.runAntiAdBlock is internally translated to `window.window.runAntiAdBlock`

**Comment by ryanbr** [comment]
sure, updated

**Comment by uBlock-user** [comment]
@gorhill isn't window.runAntiAdBlock translated to window.window.runAntiAdBlock anymore ? I'm not seeing any difference in Firefox, did something change with the scriptlet ?

**Comment by uBlock-user** [comment]
With or without that filter, I still see ad placeholders which need 

`###banner-container, [id^="ad-"]` to fix.

**Comment by gorhill** [comment]
> isn't window.runAntiAdBlock translated to window.window.runAntiAdBlock anymore ?

Yes -- there is no need to prefix with `window`.

`window` is a property of `window`, pointing to itself. See <https://developer.mozilla.org/en-US/docs/Web/API/Window/window>, so in the end even `window.window.window.runAntiAdBlock` would work.

**Comment by uBlock-user** [comment]
Was this always like this since th beginning?, because I distinctly remember you telling someone on the tracker that using `window.runAntiAdBlock` will not work, a year or two ago

**Comment by gorhill** [comment]
> I distinctly remember you telling someone on the tracker that using `window.runAntiAdBlock` will not work

I was wrong -- I didn't realize `window` was a property of `window`.

**Comment by uBlock-user** [comment]
@okiehsch Should this go into Annoyances section because proboards was fixed there ? and the same anti-adblock script is used on the other two domains ?

**Comment by okiehsch** [comment]
I can‘t test at the moment.
If the anti-adblock message is dismissable it is an annoyance if it is a „hard“ wall it should be fixed in uBO-filters.

**Comment by uBlock-user** [comment]
I tested all three, it's dismissable on all three too and stays the same as a cookie named "aab" is lodged, so it should go in the Annoyances list.

@ryanbr Can you change the list to annoyances.txt ?

**Comment by ryanbr** [comment]
Okay, done.

**Comment by mapx-** [comment]
4 days ago I added in annoyances list:
`proboards.com##+js(aeld, scroll)`

I'll add the other 2 pages to the same filter.

**Comment by llacb47** [comment]
Doesn't `aeld, scroll` have a bigger potential to break something?

**Pull request closed without merging**
