### PR TITLE
Formatting of some filters

### PR DESCRIPTION
**Pull request by DaviPiyu148**
I just changed/formatted a few lines of code for multiple filters so that their descriptions are properly displayed in adblocking software such as Adguard.

### CODE REVIEW

**Comment by krystian3w** [comment]
You should wait to end process at AdGuard side:

https://github.com/AdguardTeam/FiltersRegistry/issues/654

Barware risk should be visible in beta his extensions and apps: https://github.com/AdguardTeam/FiltersRegistry/issues/926

**Comment by DaviPiyu148** [comment]
I apologize; even after reading that thread, I still don't know why I should wait, but I'll do it. Could you offer a brief explanation of the reason and should I close the request as it isn't really a PR that big?

**Comment by krystian3w** [comment]
> ould you offer a brief explanation of the reason and should I close the request as it isn't really a PR that big?

https://github.com/uBlockOrigin/uAssets/discussions/24340 - Such differences can be a "million" after disabling AdGuard English type recommended lists in AdGuard.

**Comment by DaviPiyu148** [comment]
> > could you offer a brief explanation of the reason and should I close the request as it isn't really a PR that big?
> 
> #24340 - Such differences can be a "million" after disabling AdGuard English type recommended lists in AdGuard.

But that doesn't mean you shouldn't do it. You may be indifferent to seeing ' | ' in the place of description rather than proper description of the filter but I am sure not. Also, as I said, it was not big enough of a PR in the first place, I literally just edited 2-3 lines of code.

**Pull request merged**
