### PR TITLE
update link1s, fixes https://github.com/AdguardTeam/AdguardFilters/issues/87103

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by IThinkIAmCool** [comment]
Actually the anti adb I encountered looked like a BlockAdBlock script - still addresses anti adb on `lucidcams.com` though.

**Comment by mapx-** [comment]
no anti adb on adguard link, do you have another one?

**Comment by IThinkIAmCool** [comment]
`http://link1s.com/Gjka` -- opening it in multiple tabs may be a good tactic.

**Comment by thinksheiscool** [comment]
Anti-adblock on:
`https://cazzette.com/best-american-music/`
`https://rodjulian.com/breakfast-in-the-country-of-india-top-dishes-in-india/`
`https://hookeaudio.com/best-headset-microphone/`

**Comment by thinksheiscool** [comment]
Related: https://github.com/AdguardTeam/AdguardFilters/issues/91312

**Pull request merged**
