### PR TITLE
update fix for netcine.biz and pop-up(s)

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by uBlock-user** [comment]
I do not any experience anti-adblock acting with the existing fix

Secondly, where do you see the popups ?

**Comment by uBlock-user** [comment]
I do not experience any anti-adblock acting with the existing fix

Secondly, where do you see the popups ?

**Comment by IThinkIAmCool** [comment]
I didn't know it has been fixed since I hadn't updated uBO's 'uBlock filters'.
I saw the pop-ups before updating uBO's 'uBlock filters'.

**Comment by IThinkIAmCool** [comment]
Could the timer be bypassed or whatever?

**Comment by okiehsch** [comment]
No,  the timer is validated server side.
Add
`decorardicas.com.br,loucasporcabelos.com.br##+js(nano-stb)`
and you will see that the timer is boosted but the video will only appear after the timer has reached 0 on the server side.

**Pull request closed without merging**
