### PR TITLE
Update twitter: https://github.com/uBlockOrigin/uAssets/issues/20792

### PR DESCRIPTION
**Pull request by D4niloMR**
https://github.com/uBlockOrigin/uAssets/issues/20792#issuecomment-1822044238

### CODE REVIEW

**Comment by D4niloMR** [comment]
The only account I have that show ads for me is paywalled now, I can't test more. But from what I tested it's working fine.
image

**Comment by Yuki2718** [comment]
But why `:remove()`? Don't use it unless necessary.

**Comment by D4niloMR** [comment]
> But why `:remove()`?

This is what prevented this in my end: https://github.com/uBlockOrigin/uAssets/issues/20792#issuecomment-1820244711

**Comment by Yuki2718** [comment]
> This is what prevented [#20792 (comment)](https://github.com/uBlockOrigin/uAssets/issues/20792#issuecomment-1820244711) on my end

Okay, but can you restore the original rule as I'm not sure if the new rule covers all?

**Comment by Yuki2718** [comment]
Yes, aria-label is language-dependent.

**Comment by Yuki2718** [comment]
Thanks

**Comment by D4niloMR** [comment]
Ok, maybe it still have ads in opened images though, but I can't test https://github.com/uBlockOrigin/uAssets/pull/20813#issuecomment-1822068115

**Comment by DaisukeDaisuke** [comment]
> maybe it still has ads in opened images though

Ads next to the image will still be displayed
In my opinion `AdGuard – Ads` removes this, so I don't think it's anything to worry about

<details>

<summary>open image</summary>

Desktop Screenshot 2023 11 23 - 08 34 00 19

</details>

<details>

<summary>open Troubleshooting Information</summary>

```
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 154605
 cosmetic: 122649
 scriptlet: 26970
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  urlhaus-1: null
 added:
  adguard-social: 22021-34, 5m
  adguard-spyware: 72599-174, 5m
  adguard-spyware-url: 1329-5, 5m
  block-lan: 55-0, 5m
  fanboy-cookiemonster: 48997-225, 5m
  ublock-annoyances: 5887-57, 4m
  ublock-quick-fixes: 206-73, 4m
 default:
  JPN-1: 13797-5, 5m
  easylist: 75640-81, 5m
  easyprivacy: 32912-16327, 5m
  plowe-0: 3719-1171, 4m
  ublock-badware: 7479-147, 4m
  ublock-filters: 35700-235, 4m
  ublock-privacy: 735-228, 4m
  ublock-unbreak: 2154-87, 4m
filterset (user): [array of 1414 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 19 redacted]
userSettings:
 largeMediaSize: 1
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2048 ms (selfie)
 maxAssetCacheWait: 573 ms
popupPanel:
 blocked: 12
 network:
  twitter.com: 9
  ads-twitter.com: 2
  google-analytics.com: 1
 extended:
  ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
  ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona…
  ##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"] > d…
  ##html:style(overflow:auto!important)
  ##+js(trusted-set-cookie, d_prefs, MjoxLGNvbnNlbnRfdmVyc2lvbjoyL…
```
</details>

**Comment by D4niloMR** [comment]
> so I don't think it's anything to worry about

`AdGuard – Ads` is not enabled by default.

And maybe just `twitter.com##[data-testid="cellInnerDiv"] > div:has([data-testid="top-impression-pixel"])` fix this. But as I mentioned earlier, I can't test properly because the only account I have(that has ads) it's paywalled.

**Comment by DaisukeDaisuke** [comment]
When I added the filter I received to My Filters, it was fixed
Desktop Screenshot 2023 11 23 - 09 18 50 44

**Comment by D4niloMR** [comment]
> When I added the filter I received to My Filters, it was fixed

Test if it has flickering please

**Comment by DaisukeDaisuke** [comment]
Do I need to disable my current uasset solution when testing?

**Comment by DaisukeDaisuke** [comment]
I've disabled everything, but no ads are displayed and flickering occurs

**Comment by D4niloMR** [comment]
> There was also a blank space

Ok, so the `:remove()` seems necessary.

https://github.com/easylist/easylist/blob/edcb694e2ad52ad178b30b305d697b7ab079927c/easylist/easylist_specific_hide.txt#L4835

EasyList updated the filter, it's working?

**Comment by DaisukeDaisuke** [comment]
It does not work.
I either added one line of the EasyList filter I received to my filters or subscribed to the latest EasyList.


<details>

<summary>open image</summary>

Desktop Screenshot 2023 11 23 - 09 32 13 28

</details>

**Comment by D4niloMR** [comment]
Well, so I can think in 2 filters:

`twitter.com##[data-testid="cellInnerDiv"] > div:has([data-testid="top-impression-pixel"]):remove()`

From AdGuard:
`twitter.com##div[data-testid="cellInnerDiv"] > div > div[class] > div[class][data-testid="placementTracking"]:remove()`

**Comment by DaisukeDaisuke** [comment]
> twitter.com##[data-testid="cellInnerDiv"] > div:has([data-testid="top-impression-pixel"]):remove()

No ads, no flickering and white space, no ads next to images

___
> twitter.com##div[data-testid="cellInnerDiv"] > div > div[class] > div[class][data-testid="placementTracking"]:remove()

Tweet corruption has occurred
`Something went wrong. Try reloading.`

<details>

<summary>open image</summary>


Desktop Screenshot 2023 11 23 - 09 47 49 76

Desktop Screenshot 2023 11 23 - 09 47 59 52

</details>

**Comment by D4niloMR** [comment]
> > twitter.com##div[data-testid="cellInnerDiv"] > div > div[class] > div[class][data-testid="placementTracking"]:remove()
> 
> Tweet corruption has occurred `Something went wrong. Try reloading.`

Strange, the other one is removing the div even higher than that filter and no issue.

Btw, since I can't test it, I won't create a PR.

**Comment by stephenhawk8054** [comment]
@Yuki2718 So, does `twitter.com##div[data-testid="cellInnerDiv"] > div > div[class] > div[class][data-testid="placementTracking"]` work on your side?

**Comment by D4niloMR** [comment]
@stephenhawk8054 

Those two filters are still relevant? 
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L3879#L3880

**Comment by stephenhawk8054** [comment]
I don't use Twitter so I'm not sure

**Comment by Yuki2718** [comment]
My account still doesn't get the new ad. But as AG added the rule and some people say it worked, I'll add the rule to EL and Quick. I think the rule alternates the current rules?

**Comment by DaisukeDaisuke** [comment]
I'm a beginner, so I don't know what "#?#" means, but if you disable everything except the new rules, no ads will be displayed except for these two.
Using it at the same time as the current rules does not seem to cause corruption (I browsed for 5 minutes)
image

**Comment by Yuki2718** [comment]
The rule I mentioned above is just an areas of `twitter.com##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])` in https://github.com/uBlockOrigin/uAssets/issues/20792#issuecomment-1820098266

**Comment by Yuki2718** [comment]
@DaisukeDaisuke I wonder if `twitter.com##div[data-testid="cellInnerDiv"] > div > div[class] > div[class][data-testid="placementTracking"]` completely covers what were covered by `twitter.com##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])`. To test this, add
```
twitter.com#@?#[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:-abp-has([data-testid="top-impression-pixel"])
twitter.com#@#[data-testid="cellInnerDiv"] > div:has([data-testid="top-impression-pixel"]):remove()
```
to My filters and ignore the flickering issue. All I want to know is if no ads will be displayed.

**Comment by Yuki2718** [comment]
I guess the flickering occurs only on the primaryColumn so limiting `remove()` to primaryColumn is not bad, unless `twitter.com##div[data-testid="cellInnerDiv"] > div > div[class] > div[class][data-testid="placementTracking"]:remove()` works fine, which was reportedly [not](https://github.com/uBlockOrigin/uAssets/pull/20813#issuecomment-1823703253).

**Comment by DaisukeDaisuke** [comment]
My Filter is definitely enabled, but EasyList shows ads whether I add exclusion rules or not
I could be doing something wrong

<details>

<summary>open Troubleshooting Information</summary>

```
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 42753
 cosmetic: 30815
 scriptlet: 8
 html: 0
listset (total-discarded, last-updated):
 removed:
  JPN-1: null
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  ublock-filters: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null
 default:
  user-filters: 1411-16, never
  easylist: 72196-15, never
filterset (user): [array of 1416 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 19 redacted]
userSettings:
 largeMediaSize: 1
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4949 ms
 maxAssetCacheWait: 67 ms
popupPanel:
 blocked: 21
 network:
  ads-twitter.com: 2
  twimg.com: 19
 extended:
  ##div[data-testid="trend"]:has(path[d$="10H8.996V8h7v7z"])
  ##svg[aria-label="Verified account"]
  ##div.r-1d6w8o1.r-x572qd.r-1udh08x.r-1ifxtd0.r-rs99b7.r-1phboty.…
  ##div[aria-label] > img[src^="https://pbs.twimg.com/profile_imag…
  ##div[aria-label^="Follow @"]:nth-ancestor(1)
  ##a[href*="/analytics"]:nth-ancestor(1)
```

</details>

**Comment by Yuki2718** [comment]
Probably the latest EL is not yet available. 
> Only MyFilter and uAsset are enabled: no ads are displayed

Given this, I assume `twitter.com##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"]:has([data-testid="top-impression-pixel"])` can now be removed.

**Comment by Yuki2718** [comment]
Done https://github.com/easylist/easylist/commit/4cc5168fbdd162015c6aa0e9c339d583e8131cb1 thanks for your cooperation.

**Comment by DaisukeDaisuke** [comment]
Thanks for the fix

The "uBlock filters – Quick fixes" I currently have is as follows, and no ads are displayed even if I use exclusion rules.
image

<details>

<summary>open Troubleshooting Information</summary>

```
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 15994
 cosmetic: 12324
 scriptlet: 19155
 html: 0
listset (total-discarded, last-updated):
 removed:
  JPN-1: null
  easylist: null
  easyprivacy: null
  plowe-0: null
  urlhaus-1: null
 default:
  user-filters: 1390-16, never
  ublock-badware: 7479-10, now
  ublock-filters: 35679-47, now
  ublock-privacy: 735-0, now
  ublock-quick-fixes: 199-73, now
  ublock-unbreak: 2151-2, now
filterset (user): [array of 1395 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 19 redacted]
userSettings:
 largeMediaSize: 1
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4265 ms
 maxAssetCacheWait: 55 ms
popupPanel:
 blocked: 1
 network:
  google-analytics.com: 1
 extended:
  ##[data-testid="trend"]:has-text(/Promoted|Gesponsert|Promociona…
  ##[data-testid="primaryColumn"] [data-testid="cellInnerDiv"] > d…
```

</details>

**Comment by Yuki2718** [comment]
Yes, but we will keep the rule for the aforementioned flickering issue.

**Comment by Yuki2718** [comment]
@uBlock-user So `##div[data-testid="cellInnerDiv"] > div > div[class] > div[class][data-testid="placementTracking"]` doesn't match?

**Comment by Yuki2718** [comment]
I added the rule 5 hours ago https://github.com/uBlockOrigin/uAssets/commit/f91aa325083e60d239b6386cb6a7b8975e18dbdc BTW I wonder why nobody uses `[data-testid="tweet"]`. Shouldn't `##article[data-testid="tweet"]:has([data-testid="top-impression-pixel"]):remove()` cover all?

**Comment by Yuki2718** [comment]
Okay, so changing to `##article[data-testid="tweet"]:has([data-testid$="-impression-pixel"]):remove()` as you originally suggested makes it to work?

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c3ae3a9e18f2cc58cdb7a79375a3e5eeb5f11f48

**Pull request merged**
