### PR TITLE
Unblocking the criteo homepage

### PR DESCRIPTION
**Pull request by stm-x**
### URL(s) where the issue occurs

`https://www.criteo.com/`

### Describe the issue

Access to criteo.com is strictly-blocked by peter lowes list.

### CODE REVIEW

**Comment by iam-py-test** [comment]
@mapx- 
 MVPS HOSTS has the same problem (after updating all filters):
image

**Comment by okiehsch** [comment]
We only unbreak sites that are broken with a default setup.
MVPS Hosts is not part of the default setup.

`||www.criteo.com^$badfilter`

**Comment by iam-py-test** [comment]
> 
> 
> We only unbreak sites that are broken with a default setup. MVPS Hosts is not part of the default setup.
> 
> `||www.criteo.com^$badfilter`

I don't need it unblocked, I just figured I would alert you about the problem

**Comment by spirillen** [comment]
It is blocked for very good reasons by many, it is to be classified as Adware and Tracking

- https://medium.com/nextdns/cname-cloaking-the-dangerous-disguise-of-third-party-trackers-195205dc522a
- https://mypdns.org/my-privacy-dns/matrix/-/issues/3116
- https://mypdns.org/my-privacy-dns/matrix/-/issues/3117

If you for some reasons believes the ban should be eased a bit then block it at least as `^3p`

You can just try to scrape my collecting library: https://github.com/Import-External-Sources/hosts-sources

```shell
github/Import-External-Sources/hosts-sources$ git grep '\.criteo\.com$' | cut -d ':' -f 2 | sort -u
```

I will spare you the full list here as it is rather big (704 results)

**Comment by ryanbr** [comment]
Disappointing. Looking from a webcompat perspective. Its an unnecessary first party block given its 3p blocked in Easyprivacy. To disable uBO or Brave shields just opens up more trackers to the user for the sake of policy. 

You want people not to need to disable their adblock software to get a workaround, the less interaction by the user the better. "Just make it work".

**Comment by Yuki2718** [comment]
User actually don't need to disable uBO on the strict-blocked page, but some user will do.

**Comment by gorhill** [comment]
> the less interaction by the user the better. "Just make it work".

Entirely agree of course.

However here we are not talking about "users", we are talking about sites used to push ads/trackers on users, from uBO's perspective the _clients_ of those sites_ are tracker/ad pushers, not users. They are welcome to eat their own food by disabling uBO if it gets in the way on these specific sites.

**Comment by Yuki2718** [comment]
> the clients of those sites are tracker/ad pushers, not users.

I can say that's not always the case because subdomain also blocked. The latest article on `https://note.smartnews-ads.com/` (`https://github.com/AdguardTeam/AdguardFilters/issues/95110`) is "how COVID-19 changed consumer's sense of beauty".

**Comment by ryanbr** [comment]
We take a more harder line in Easylist for revolving adservers/trackers. But each request is treated on its own merits if it comes to our attention. But having a blanket rule like this seems to is an overkill. General strict block should be reserved for specific servers imo.

**Comment by Yuki2718** [comment]
In relation to https://github.com/uBlockOrigin/uAssets/commit/1142bef68ee287d27f6191c433ff8491570b6612 are all visitors of these pages (many of them include ordinary blogs about marketing) really customers/clients? We already unblocked `analytics.google.com` in https://github.com/uBlockOrigin/uAssets/issues/18576 and `pagefair.com` blocking has been bothering to me personally as I occaisonary visit and reference the site for their statistics (badfilterd in My filters). It seems most of these sites don't even have click-through tracker missed by the original rules. If it's click-through tracker that matters, we can use `$doc` instead of totally breaking sites (even then I prefer actually confirming existence of such trackers). Should a univ student interested in marketing and installed uBO who doesn't know how to badfilter rules should put up with all the annoynaces or disable uBO (and accept all the tracker)? To me it only looks like we want to break these sites.

**Comment by gorhill** [comment]
> `pagefair.com` blocking has been bothering to me

If you think `pagefair.com` shouldn't be in Peter Lowe's, why not ask him to remove it? There must be a reason why he added it in his list.

**Comment by Yuki2718** [comment]
Peter's is hosts file, not having `$3p` and 0 or 1. Based on publicwww it seems `asset.pagefair.com/measure.min.js` shoudl be blocked.

**Comment by Yuki2718** [comment]
Don't know what quote that is, anyway what are blocked here are not adservers but ordinary and/or useful sites. Adservers are all blocked by EL.

**Comment by gorhill** [comment]
So essentially you are arguing having Peter Lowe's as a default list.

**Comment by Yuki2718** [comment]
I'm pro for having PL in the default lists as I have actually seen cases it catched something missed by other lists. Only questioning some aggressive blocking which we can had had been fixed with `$3p`.

**Comment by gorhill** [comment]
We come back to the previous discussion: using `3p` removes the domain and all subdomains from being candidate for strict blocking. That's the issue.

**Comment by Yuki2718** [comment]
Changes since the last discussion:
- `$doc` was not mentioned at the time
- We unblocked `t.co` and GA in https://github.com/uBlockOrigin/uAssets/issues/18576 (I believe it's right decision, any blogger may use GA)
(And still no single confirmed case that any of them actually turned to click-through tracker)

**Comment by gorhill** [comment]
> We unblocked `t.co` and `analytics.google.com`

We used our judgment that blocking `t.co` was a problem due to widespread use of `t.co` to shorten links. As for `analytics.google.com` we know it's not used for tracking.

> no single confirmed case that any of them actually turned to click-through tracker

That's the problem, if they turn, strict-blocking won't be there to make it visible.

**Comment by Yuki2718** [comment]
> As for `analytics.google.com` we know it's not used for tracking.

But what if I claim `analytics.google.com` may be used as click-through tracker in future? This is the very problem here. We all agreed that click-through tracker should be strict-blocked, but the story is different if it's not click-through tracker but harmless sites. The only reason we keep these rules is assumption without evidence. We *know*, say, taboola uses, and has been using, only `api.taboola.com` for click-through tracker, this is why the rule was there. What's the basis taboola may use parent domain or other subdomain in future? Even if that's the case, what is different from all other tracker which we and all the contributors seek for and add to filters once found?

**Comment by gorhill** [comment]
> But what if I claim analytics.google.com may be used as click-through tracker in future?

Then we block it. People visiting that site are welcome to disable their blocker.

**Comment by Yuki2718** [comment]
> Of course I assume that the claim would come with actual cases supporting it.

If so, we can revert at least some of https://github.com/uBlockOrigin/uAssets/commit/1142bef68ee287d27f6191c433ff8491570b6612 , right? I'm fine to block confirmed tracker, but am against blocking domain for unconfirmed theoretical possibility.

**Comment by gorhill** [comment]
Let's wait for reports, than we can act on a per-cases basis?

**Comment by Yuki2718** [comment]
All of them were reported once, but okay.

**Comment by gorhill** [comment]
Yes, and if again, depending on the report, will just tell people they can just disable uBO if they want to visit the site, or email Peter Lowe if they disagree with the block. We can explain the reason we won't work around the block: we trust Peter Lowe and won't second guess him, but whoever else is free to do so.

**Comment by Yuki2718** [comment]
Well, it's not on I don't trust Peter, but rahter `$3p` difference is significant in these domain. But TBH I don't wanna waste more of your and my time on this.

**Pull request merged**
