### PR TITLE
Update q

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`https://infinityscans.xyz/comic/415/records-of-the-demonic-paths-return/chapter/57084/66to5e8drqjh0fk60r3r5qj2fr`

### Describe the issue

antiadb

### Screenshot(s)

image

### Versions

- Browser/version: firefox/edge
- uBlock Origin version: 1.54.1b1

### Settings

-  uBO's default settings

### CODE REVIEW

**Comment by mapx-** [comment]
@BlazeFTL a PR ? I removed 1x1.gif filter

**Comment by BlazeFTL** [comment]
Ok

**Comment by BlazeFTL** [comment]
Possibly Because Of Obfuscation...Ubo Cant Defuse Obfuscated fetch/xhr

**Comment by BlazeFTL** [comment]
> adshield

They Noob

I Would Like To See How We Can Better Fix Without Exception

**Comment by BlazeFTL** [comment]
I Meant For This Site

**Pull request merged**
