### PR TITLE
address dvdplay. sbs popups

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

```
dvdplay.sbs
https://dvdplay.sbs/page-1269-The-Falcon-and-the-Winter-Soldier-S01-Series/
```

### Describe the issue

popups when clicked anywhere

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox 98
- uBlock Origin version: 1.41.8

### Settings

-  uBO's default settings

### CODE REVIEW

**Comment by ghajini** [comment]
@mapx- how about i use `dvdplay.sbs##+js(set, D4zz, undefined)`

**Comment by mapx-** [comment]
why not `dvdplay.sbs##+js(aopr, D4zz)` or `dvdplay.sbs##+js(aopr, decodeURI)`

**Comment by ghajini** [comment]
> why not `dvdplay.sbs##+js(aopr, D4zz)` or `dvdplay.sbs##+js(aopr, decodeURI)`

doesn't worked in firefox

**Comment by PerfectSalad** [comment]
@ghajini @mapx- Is there an issue with `acis.js` in FF Android uBO?

**Pull request merged**
