### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by MasterKia**

### CODE REVIEW

**Comment by MasterKia** [comment]
@JobcenterTycoon @okiehsch

**Comment by JobcenterTycoon** [comment]
Maybe they have a serverside script which automatly change these random looking class names every hour.

`techpowerup.com` did this too. They placed a serverside script which automatically changed a few parameter after ~30 minutes

**Comment by MasterKia** [comment]
Remove the first 3 rules.

**Comment by MasterKia** [comment]
@JobcenterTycoon 
Remove the first 3 rules, add these instead:
```
soft98.ir##[src*="file.soft98.ir"]:style(color: white !important;)
soft98.ir##[src*="cdn.hostdl.com"]:style(color: white !important;)
```

**Comment by JobcenterTycoon** [comment]
Is ok

**Comment by MasterKia** [comment]
> They placed a serverside script which automatically changed a few parameter like the class name and the image URL after ~30 minutes

Did a techpowerup inform you about that?

**Comment by JobcenterTycoon** [comment]
No but im monitored them.

**Comment by MasterKia** [comment]
For how long did you keep up with them until they let go?

**Comment by JobcenterTycoon** [comment]
It started february and ended with https://github.com/uBlockOrigin/uAssets/commit/dfdb43fd734601db6339516ef5533ee18f624218

**Comment by MasterKia** [comment]
The funny thing is, their ads are already blocked so even if the user clicks on them they'll be closed; and yet the still insist to shove it down the throat of users.

**Pull request merged**
