### PR TITLE
fix web.de

### LINKED ISSUE #6834: web.de Layout messed up
### URL(s) where the issue occurs
`https://web.de/`

### Describe the issue

The new site layout is dislocated to the left, so that part of the actual page is missing. This is fixed when I uncheck Ublock filters
### Screenshot(s)

https://i.imgur.com/n4Ej4H7.png

### Versions

- Browser/version: Firefox 72.0.1
- uBlock Origin version: 1.24.2

### Settings

no settings changed, personal filters do not cause this to happen. 

### Notes
Tested deactivating UBO completely, then went through the lists one by one. Thus I found the Ublock filters list is responsible

### PR DESCRIPTION
**Pull request by krystian3w**
`web.de##body[data-ad-type] > #app > .main:style(grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border)) !important;)`

`web.de##+js(ra, data-ad-type, body)`

### CODE REVIEW

**Comment by mapx-** [comment]
@okiehsch maybe you are able to get the issue (see the new `web.de` page) and see what to do

**Comment by krystian3w** [comment]
problematic is used:

https://developer.mozilla.org/en-US/docs/Web/CSS/minmax

**Comment by krystian3w** [comment]
```
[{
	"Host raw": "http://.web.de/",
	"Name raw": "SSLB",
	"Path raw": "/",
	"Content raw": ".1",
	"Expires": "15-02-2020 21:44:00",
	"Expires raw": "1581799440",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
}]
```

`web.de##+js(cookie-remover, SSLB)`

**Comment by okiehsch** [comment]
I can't reproduce, with a german IP I get
image

**Comment by krystian3w** [comment]
try few refresh or I record mp4 👼 with used Hola VPN.

**Comment by okiehsch** [comment]
Refreshing doesn't change anything on my end. 
I believe you that you can reproduce, no need to record a mp4.

**Comment by krystian3w** [comment]
https://streamable.com/tio67

**Pull request closed without merging**
