### PR TITLE
address ads ytx.mx

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

```
https://yts.mx
https://yts.mx/movies/x-2022
```

### Describe the issue

unblocked 3rd party ads

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox
- uBlock Origin version: 1.42.4

### Settings

- uBO's default settings

### CODE REVIEW

**Comment by stephenhawk8054** [comment]
Hmmm... I can't play the video until I add `cloudflare.net` (which is CNAME connection) to `denyallow` filter. 

Or I think you can use `yts.mx##+js(nostif, "admc")` for this site.

**Comment by ghajini** [comment]
site is circumventing easylist generic filters so denyallow filter
i don't get `cloudflare.net` request
firefox_0lC17c5mYu
firefox_7twdcKjijR

`yts.mx##+js(nostif, "admc")` also work

**Comment by stephenhawk8054** [comment]
Maybe depending on region and DNS server? Mine looks like below

<details><summary>Screenshot</summary>

image

</details>

And the video is just stuck at loading screen

**Comment by ghajini** [comment]
ok then denyallow is not good as of now

**Pull request closed without merging**
