### PR TITLE
Allow mining on mylink.li

### PR DESCRIPTION
**Pull request by mylinkadmin**
Thank you.

Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

### CODE REVIEW

**Comment by ryanbr** [comment]
Personally if a site enforces coin mining to allow use, then adblockers shouldn't let it run. the problem isn't with the list, its an issue of the site and its bad design.

**Comment by okiehsch** [comment]
I asked gorhill before I merged and he is fine with opt-in, i.e. `authedmine`.

**Comment by SMed79** [comment]
> if a site enforces coin mining to allow use, then adblockers shouldn't let it run.

As i asked here https://github.com/uBlockOrigin/uAssets/issues/770#issuecomment-340907369

**Comment by ryanbr** [comment]
"I have a charity website that relys on coin mining for income" (which was another excuse someone used in forums), which was still denied. If a site needs or use Coin mining, it should be blocked just like any other server. uBo is using a grey area to allow coin miners is bad for users.

Its either you block miners, or you don't, there isn't a "sometimes".

**Comment by okiehsch** [comment]
> the right question is:  Can you access to the contents without mining? 

To clarify and to paraphrase gorhill:
If a filter blocking a miner breaks a specific site, and if the miner is shown to be entirely opt-in with no anti-user workaround, then an exception filter is acceptable to unbreak the site -- just like filter list maintainers accept to create exceptions for some other ubiquitous 3rd parties to unbreak sites.

**Comment by ryanbr** [comment]
The difference here is they're raping your cpu in the process, and for the most part getting around an advert might involve a minor whitelist or a filter adjustment(s).

If a site is willing injecting coin miner without a whiltelist, then it should remain broken. The onus should be on the website to change not the lists, afterall they're the one's injecting the nasty code. I'm not expecting ubo to change their policy, I'm just outlining our thoughts on coin miners.

**Pull request merged**
