### PR TITLE
Redundant entries

### PR DESCRIPTION
**Pull request by peace2000**
More redundant entries.

Pretty sure this is ok to remove `||jtpc2pa9o2n7.com^` but not 100 %, it doesn't have any comment etc...

For long entries GH can't compare properly for changes, this tool works well: https://countwordsfree.com/comparetexts

### CODE REVIEW

**Review by Yuki2718 — APPROVED** [review]

**Comment by Yuki2718** [comment]
@peace2000 Can you please add comment about removed domain if you edit a long rule like nobab in this case? It took a bit of time to find out what were removed: `hiringpinas.com,hotelsevillanoacapulco.com,iansomerhalderfan.com,infophoria.co.id,ingenioyhumor.blogspot.com,isabelleallen.net,jameelajamil.tk,januaryproxy.ml,jayamuvi.com,jennadewan.org,josh-duhamel.org,juegosyvideojuegos.com,julia-garner.com,juliannemooreweb.net,kavatch.de,kendall-photos.com,kissproxy.gq,laboratoriummuzycznychfuzji.com,lauramarano.com.br,lauren-german.org,lilireinhart.us,lilyjamesdaily.com,lizzieolsen.us,localbook.co,lokerbisnisonline.id,lucyhaledaily.us,madelainepetsch.com.br,madkyo.cz,mallinformasi.com,mcanimx.co.in,medieval-engineers.eu`

**Comment by peace2000** [comment]
@Yuki2718 Hi, I have noted that GH can't compare long texts and their changes properly so that's why I gave link to this tool: https://countwordsfree.com/comparetexts as it can properly compare changes related to that "nobab" section. If you copy that red and green sections to it, it shows differences between them. I gave that link in my previous pull reqs as well, so that reviewers can easily compare changes.

Couple of pics from comparison:

kuva

kuva

Sorry if I was unclear.

**Comment by Yuki2718** [comment]
Oh, sorry I missed your comment.

**Comment by peace2000** [comment]
Hopefully @okiehsch didn't miss my comment concerning that comparison tool link I gave in previous pull requests.

**Comment by okiehsch** [comment]
I didn't, thanks it's very helpful.
I am rather busy atm and had no time thoroughly checking if the domains are redundant or not.

**Comment by peace2000** [comment]
I used tool called PyFunceable to pick those domains that are possibly redundant, are you familiar with that tool?

**Comment by Yuki2718** [comment]
Well, these domain are dead rather than being redundant.

**Comment by okiehsch** [comment]
> I used tool called PyFunceble to pick those domains that are possibly redundant, are you familiar with that tool?


Yes.
There is the possibilty of a false possible, so we have to check manualy,

**Pull request merged**
