### PR TITLE
Remove IF rules

### PR DESCRIPTION
**Pull request by bernd87**
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

### CODE REVIEW

**Comment by stephenhawk8054** [comment]
Can you describe the issue in more details, and how to reproduce it?

The filter 

```
imagefap.com##+js(acis, $, open)
```

is still needed for desktop version `https://www.imagefap.com` to prevent popup.

For mobile version of `https://beta.imagefap.com` (which can only open in mobile environment), I can replace other filters with

```
!#if env_mobile
beta.imagefap.com##+js(aost, open, setPopUnder)
!#endif
```

to prevent the popup. But I'm not sure if it still causes issue for you or not, unless you give us more details about how to reproduce the issue.

**Comment by bernd87** [comment]
hmm, which popups are we talking about? I am on the desktop version & I just tried with the this whole list disabled and i had no popups or ads at all, which i think is the case because they get blocked from some other list?!

`imagefap.com##+js(acis, $, open)` basically blocks any custom scripts it seems

**Comment by okiehsch** [comment]
@stephenhawk8054 I can't reproduce but I can see the script in the source that you want to disable with the scriptlet.
Can you change it to 
`imagefap.com##+js(acis, $, popCookie)`
that should fix the greasemonkey issue I would assume.
@bernd87 
If you add 
````
imagefap.com#@#+js(acis, $, open)
imagefap.com##+js(acis, $, popCookie)
````
to your filter list are your custom scripts working or not?

**Comment by bernd87** [comment]
@okiehsch 
with
`imagefap.com#@#+js(acis, $, open)
imagefap.com##+js(acis, $, popCookie)`
the scripts seem to work fine

**Comment by bernd87** [comment]
I can post and explain the script if needed

**Comment by stephenhawk8054** [comment]
I tested the site `https://www.imagefap.com` with `imagefap.com#@#+js(acis, $, open)` exception and opened in new Private Window. After that, clicking on the links at the `Our niches` table on the left triggered a popup for me.

But yeah, I think `$` and `open` can cause issues here with user scripts, `imagefap.com##+js(acis, $, popCookie)` would be better

**Comment by okiehsch** [comment]
> I can post and explain the script if needed

Thanks, but no need really, the `acis, $, open` means that basically any custom script with a string "open" in it won't work, hence 
my suggestion to change it to `acis, $, popCookie`.
With that change only custom scripts that include the string `popCookie` won't work most of the time and that should be a rather rare occurenc.

**Comment by okiehsch** [comment]
@stephenhawk8054 does the filter
`imagefap.com##+js(aopr, Buu.serve)`
serve any purpose on your end anymore?

**Comment by stephenhawk8054** [comment]
@okiehsch Looks like nope, besides `imagefap.com##+js(acis, $, popCookie)`, I think others are obsolete now. Except maybe `*$popunder,domain=imagefap.com,3p` to automatically close the popup in mobile `beta` version, but it can be replaced by `beta.imagefap.com##+js(aost, open, setPopUnder)` on my side.

**Comment by okiehsch** [comment]
Ok, let's remove them all and add your filter.

**Pull request closed without merging**
