### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://dropgalaxy.vip/9chr1jdat0h0`

### CODE REVIEW

**Comment by BlazeFTL** [comment]
This Has To Be Removed
```
dropgalaxy.*##+js(set, navigator.userAgent, '')
```
Or Can Be Replaced With
```
dropgalaxy.*##+js(trusted-set, navigator.userAgent, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML\, like Gecko) Chrome/119.0.0.0 Safari/537.36)

**Comment by BlazeFTL** [comment]
@JobcenterTycoon Bro You Free ?

Site Owner Added `handleError`
Now All 3 acs Filter(1 From Annoyance Too) Has To Be Whitelisted

Any Idea To Fix Without Removing Those Rules ?

**Comment by JobcenterTycoon** [comment]
Sorry im out.

**Comment by BlazeFTL** [comment]
I Fixed It With But Obviously Wont Work In 1 Day🤣
```
dropgalaxy.*##+js(set, onerror, '')
```

**Pull request merged**
