### PR TITLE
Clean up uAssets filters related to Korean content 1

### PR DESCRIPTION
**Pull request by piquark6046**
https://github.com/List-KR/List-KR/issues/285

### CODE REVIEW

**Comment by piquark6046** [comment]
https://github.com/uBlockOrigin/uAssets/pull/13031/commits/f4790be75e7a0687ad5abc14f87dfc3f2c799b90


<details>
<summary>Screenshot</summary>

Screenshot from 2022-04-30 12-53-15

</details>

**Comment by krystian3w** [comment]
We use `filters` word for 1 line in list file, rules is for firewall only.

filter = "AdGuard rule"
list = "filter" list in AdGuard syntax

**Comment by piquark6046** [comment]
https://github.com/uBlockOrigin/uAssets/pull/13031#issuecomment-1114009769
The title of this PR was renamed.

**Comment by piquark6046** [comment]
https://github.com/uBlockOrigin/uAssets/pull/13031/commits/e52b9fafc107d5a8b845437ee8dbc2d193faeb3a
The anti-adblock and advertisement is resolved by List-KR.

**Pull request merged**
