### PR TITLE
update https://github.com/uBlockOrigin/uAssets/issues/8706

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

NSFW `https://send.cm/haaoqngjjdtm`

### Describe the issue

update filter
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox a
- uBlock Origin version: 1.42.4

### Settings

-  uBO's default settings

### Notes
iam keeping `send.cm##+js(aeld, , break;case $.)` if site tries to load propeller requests from not inline

### CODE REVIEW

**Comment by ghajini** [comment]
@mapx- 
Is this valid?
`send.cm##+js(acis, /parseInt|navigator/, break;case $.)`

**Comment by mapx-** [comment]
no, regex accepted on the second parameter only

**Comment by ghajini** [comment]
so how the filter will look, if i have to target `parseInt, navigator, break;case $.`

**Comment by mapx-** [comment]
if matches

`acis, parseInt, /navigator|break;case/`

**Comment by mapx-** [comment]
or 2 acis filters

**Comment by ghajini** [comment]
or
`acis, parseInt, /navigator|parseFloat|break;case $./`

2 acis 👍

**Comment by mapx-** [comment]
be careful with regex .. if you want to use a point `.`  as part of the matching stuff you have to use it `\.` otherwise has another meaning in regex

**Comment by ghajini** [comment]
ok i will learn all this,ty👍

**Pull request merged**
