### PR TITLE
Update filters.txt

### PR DESCRIPTION
**Pull request by PerfectSalad**
obsolete filters I think

### CODE REVIEW

**Comment by mapx-** [comment]
which one ?

**Comment by PerfectSalad** [comment]
> which one ?

removed `kissproxy . ga` `kissproxy . ml` `aetools . ga` (without the spaces) from filters.txt

**Comment by PerfectSalad** [comment]
removing more in this pr

**Comment by mapx-** [comment]
List all removed sites here

**Comment by PerfectSalad** [comment]
from filters.txt, in the first part (or whatever):

```
kissproxy.ga
kissproxy.mk
aetools.ga
```
and then:
https://github.com/uBlockOrigin/uAssets/pull/12160/commits/197aaf8e5316dd9be660f03de7ee1ac9a7813a38

**Pull request merged**
