### PR TITLE
Profitsfly Up

### PR DESCRIPTION
**Pull request by BlazeFTL**

### CODE REVIEW

**Comment by D4niloMR** [comment]
Which link use this site?

**Comment by BlazeFTL** [comment]
`https://droplink.co/kGd64O`

**Comment by BlazeFTL** [comment]
@D4niloMR New Domain 
`dawenet.com`
```
btcut.io/oHWSRnd

**Comment by BlazeFTL** [comment]
New Domain
```
erzar.xyz

**Comment by Arash4030** [comment]
New Domain `waezm.xyz`

**Pull request merged**
