### PR TITLE
Update filters.txt

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

### CODE REVIEW

**Comment by ghajini** [comment]
i intend to remove 
`*$script,3p,denyallow=wp.com|cdn77.org|facebook.com|facebook.net|fbcdn.net|instagram.com|disqus.com|disquscdn.com|jwpsrv.com|plyr.io|jsdelivr.net|twimg.com|twitter.com|fastly.net|fastlylb.net|jquery.com|hwcdn.net|hcaptcha.com|recaptcha.net|cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com,domain=bmovie.cc`

and add
 `bmovie.cc,fmovie.cc,googlvideo.com##+js(aopr, mm)`

i think inadverently happened reverse
please correct

**Comment by Yuki2718** [comment]
`affforce.com` has a website so `$all` seems to be overkill, Where you saw this call?

**Comment by ghajini** [comment]
at embed of 1moviestv

**Comment by Yuki2718** [comment]
I don't see on `https://1moviestv.com/watch-tv/watch-johnny-test-free-37532.2477258`. Can't it be `$3p`?

**Comment by ghajini** [comment]
i have seen here
`https://5movies.buzz/father-stu/2022/`
server 2

**Comment by Yuki2718** [comment]
Maybe `||affforce.com^$popup`

**Comment by ghajini** [comment]
since that was serving phishing/malware, i blocked it completely

**Comment by mapx-** [comment]
for the fake player test

```
5movies.*###cookiedata
5movies.*##.btn-lg
5movies.*###content-embed:style(display: block!important)
5movies.*##.mvi-cover
5movies.*##.streamaly
5movies.*##.les-title:has-text(HD)
```

**Comment by Yuki2718** [comment]
> for the fake player test

Still getting popup on play.

**Comment by mapx-** [comment]
mmhmm, I get no popup

**Comment by mapx-** [comment]
wait ... server 2

**Comment by Yuki2718** [comment]
Yep, server2. I'm using Firefox FWIW.

**Comment by mapx-** [comment]
It seems to be a fake one and behind it no real one ?

**Comment by mapx-** [comment]
yeah, just redirecting

view-source:https://1movietv.com/favis/motvhd.html

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN">
<HTML>
<HEAD>
<TITLE>1080 HD</TITLE>
<META HTTP-EQUIV="REFRESH" CONTENT="0; url=https://www.affforce.com/scripts/un981c6l?a_aid=a88a0870&a_bid=29cc11a7">
</HEAD>
</HTML>
```

**Comment by mapx-** [comment]
so server2 is completely fake

**Comment by Yuki2718** [comment]
Whoops, missed that!

**Comment by ghajini** [comment]
`server2,3,4,hd server 1080` all same

**Comment by mapx-** [comment]
ok, this 1 too 

`1movietv.com##li.uk-active:remove()`

**Pull request merged**
