### PR TITLE
Removed addthis.com, included in Easyprivacy

### PR DESCRIPTION
**Pull request by ryanbr**
Cleaned up unused filters, since its now included in Easyprivacy. any fixes can land in Easyprivacy

### CODE REVIEW

**Comment by mapx-** [comment]
still needed (not only scripts but frame too)

```
@@||addthis.com/js/*/addthis_widget.js$script,domain=schonmagazine.com
@@||addthis.com/live/$script,domain=schonmagazine.com
@@||addthis.com/static/$subdocument,domain=schonmagazine.com
```

**Comment by mapx-** [comment]
needing 
`@@||addthis.com/*-angularjs.min.js$script,domain=missingkids.*`

**Comment by ryanbr** [comment]
Unless it breaks the site itself, then agreed it should be addressed with a fix. Because we'll have every site complaining "my addthis icons" aren't working, add to the Easyprivacy like x, y domain.

**Comment by mapx-** [comment]
> addthis is a social icon tracking

probably you are right .. @gorhill @okiehsch  your opinion ?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/2764#issuecomment-402854508

"If the breakage is only the Addthis widget failing to load, I rather not have the fix in uBO's filter lists -- or else the logical consequence is to remove addthis.com from "uBlock filters -- Privacy", which is not something I see as a good thing."

**Comment by mapx-** [comment]
ok, so `schonmagazine` is not broken but `missingkids.com/.org` does

**Comment by ryanbr** [comment]
Whats the issue with missingkids?

**Comment by mapx-** [comment]
> Whats the issue with missingkids?

kill uBO filter

`||addthis.com^$important,3p,domain=~amd.com|~missingkids.com|~missingkids.org|~sainsburys.jobs|~schonmagazine.com|~sitecore.com|~plotaroute.com,badfilter`

and go to 
`https://www.missingkids.org/poster/USVA/VA22-2926/1/screen`

needing
`@@||addthis.com/*-angularjs.min.js$script,domain=missingkids.com|missingkids.org`

**Pull request merged**
