### PR TITLE
Update badware.txt

### PR DESCRIPTION
**Pull request by pandaninjas**
### URL(s) where the issue occurs
`https://flippingcharts.com/#about`
### Describe the issue

The site hosts a Minecraft mod, which logs tokens by calling `func_148254_d`, which according to `https://github.com/KevyPorter/Minecraft-Forge-Utils/blob/master/methods.csv`, is the getToken method. The token then can be used to gain access to the Minecraft account for a limited period of time.

### Screenshot(s)
Screenshot 2022-04-22 at 08-41-29 Download FlippingCharts - Official Website

Screenshot 2022-04-22 083928

### CODE REVIEW

**Comment by iam-py-test** [comment]
VirusTotal scans:
https://www.virustotal.com/gui/url/a424fc4b734ea352c7e1d13aab03d2e497256c9b6d896e7325dff129cbd2eda2
https://www.virustotal.com/gui/file/2ad1c3c9c6a28137a9957772df68da9d243a307194411cf1f89e5ee686add826/detection

Shouldn't that be `$all` if it's malware?

**Comment by pandaninjas** [comment]
> VirusTotal scans: https://www.virustotal.com/gui/url/a424fc4b734ea352c7e1d13aab03d2e497256c9b6d896e7325dff129cbd2eda2 https://www.virustotal.com/gui/file/2ad1c3c9c6a28137a9957772df68da9d243a307194411cf1f89e5ee686add826/detection
> 
> Shouldn't that be `$all` if it's malware?

What's the difference between `$all`, and `$doc`? As far as I can tell, `$all` blocks the loading of additional resources, however the jar download is not hosted on their own servers.

**Comment by pandaninjas** [comment]
> > VirusTotal scans: https://www.virustotal.com/gui/url/a424fc4b734ea352c7e1d13aab03d2e497256c9b6d896e7325dff129cbd2eda2 https://www.virustotal.com/gui/file/2ad1c3c9c6a28137a9957772df68da9d243a307194411cf1f89e5ee686add826/detection
> > Shouldn't that be `$all` if it's malware?
> 
> What's the difference between `$all`, and `$doc`? As far as I can tell, `$all` blocks the loading of additional resources, however the jar download is not hosted on their own servers.

Nevermind, I realized they changed the host of their resources

**Comment by iam-py-test** [comment]
> > VirusTotal scans: https://www.virustotal.com/gui/url/a424fc4b734ea352c7e1d13aab03d2e497256c9b6d896e7325dff129cbd2eda2 https://www.virustotal.com/gui/file/2ad1c3c9c6a28137a9957772df68da9d243a307194411cf1f89e5ee686add826/detection
> > Shouldn't that be `$all` if it's malware?
> 
> What's the difference between `$all`, and `$doc`? As far as I can tell, `$all` blocks the loading of additional resources, however the jar download is not hosted on their own servers.

In my personal opinion, it's best to block all connections to a malware domain (I don't think there is a downside, apart from that it is harder for the user to bypass it, which I guess is a feature). It's just my opinion, not a rule here

**Comment by krystian3w** [comment]
IMO modern scam start use inline styles:

```html
<style>

* { 
/* */
}
</style>
```

Or `<a style="style" ...> a </a>

Inline images like svg or base64 encoded.

Try use redirect by forms to different page.

So looks pretty nice after temporary unlock.

To block inline css, forms and maybe images we need use `:remove()`, html filtering, `ra.js` with stay parameter (or block 3p request by `$all,domain=fraud-domain.agency`).

**Review by krystian3w — APPROVED** [review]

**Comment by iam-py-test** [comment]
> IMO modern scam start use inline styles:
> 
> ```
> <style>
> 
> * { 
> /* ... */
> }
> 
> </style>
> ```
> 
> Or `<a style="...style..." ...> a </a>`
> 
> Inline images like svg or base64 encoded (to exclude generate fake CDN).
> 
> Tries use redirect by forms to different page.
> 
> So looks pretty nice after temporary unlock.
> 
> To block inline css, forms and maybe images we need use `:remove()`, html filtering, `ra.js` with stay parameter (or block 3p requests by `$all,domain=fraud-domain.agency` to defend forms).

Not really needed if we already block the main document

**Comment by krystian3w** [comment]
Needed if many users immediately ignore prompts.

**Comment by iam-py-test** [comment]
@mapx- reason for closing this?

**Comment by mapx-** [comment]
missed the last commit

**Review by iam-py-test — APPROVED** [review]

**Pull request merged**
