### PR TITLE
address databasegdriveplayer .co ads

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

```
https://series.databasegdriveplayer.co/player.php?type=series&imdb=tt9742936&season=3&episode=20
https://databasegdriveplayer.co/player.php?tmdb=661231
```

### Describe the issue

popup ads

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: opera/firefox
- uBlock Origin version: 1.42.4

### Settings

- uBO's default settings

### CODE REVIEW

**Comment by ghajini** [comment]
@stephenhawk8054 
does downloads from this site are real one? 
they require google sign-in (& badfiltering some EL filter to check)

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 does downloads from this site are real one? they require google sign-in (& badfiltering some EL filter to check)

Is there any button to download? I only see the video player with 2 links above.

**Comment by ghajini** [comment]
this one 
image

`https://series.databasegdriveplayer.co/player.php?type=series&imdb=tt9742936&season=3&episode=20`

**Comment by stephenhawk8054** [comment]
Looks like it requires some `CloudClone` app to have access to google drive account

image

I would prefer to let it blocked as current.

**Pull request merged**
