### PR TITLE
update gplinks

### PR DESCRIPTION
**Pull request by huyszn**
`gplinks.co/EWu8`

New domain: `ktgnews.com`

### CODE REVIEW

**Comment by spidy2356** [comment]
adblock detection pop up comes again in gplinks in firefox and kiwi android. plz fix this sir as soon as possible.

here is link: https://gplinks.co/wyIRsNAd

thank u

**Comment by ItsProfessional** [comment]
@spidy2356 already fixed. Update your filter lists.

**Comment by spidy2356** [comment]
@ItsProfessional but sir, my filterlist are already updated. Still not working on Android kiwi and Android firefox but working in pc browser like brave and firefox. Plz check once sir

**Comment by huyszn** [comment]
It's because they just updated the domain to `jankarihubedu21.com`

**Comment by spidy2356** [comment]
> It's because they just updated the domain to `[jankarihubedu21.com](http://jankarihubedu21.com)`

yes sir. that's why. plz fix it sir.

**Comment by spidy2356** [comment]
@ItsProfessional in firefox android next page redirect URL not coming. so I can't get bypass url. plz check sir

**Pull request merged**
