### PR TITLE
DevUP Update

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://devuploads.com/3gnadp4i2vwf`

They Dont Seem To Update That Much

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
Are the frame whitelists needed? It works fine for me without whitelisting the frames.

**Comment by BlazeFTL** [comment]
No script,xhr,
Can Be Used Just To Safe For Others
Thats What I Tried

**Comment by BlazeFTL** [comment]
@JobcenterTycoon Bro Can You Remove...Causes Anti Adb
```
dev.miuiflash.com,djxmaza.in,thecubexguide.com##[id*="iframe"]:style(height:250px !important;left:-4000px !important;position:absolute !important)
djxmaza.in,miuiflash.com,thecubexguide.com###featuredimage:style(height:250px !important;left:-3000px !important;position:absolute !important)

**Comment by JobcenterTycoon** [comment]
Fixed. On my end only the second one caused anti adb

**Pull request merged**
