### PR TITLE
obsolete filters

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by uBlock-user** [comment]
```
||max-adserv.com^$3p
||allittledprevi.info^
```

Should be added back, these are global filters and the sites are still alive.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7e3f33936877c6464de75125aa378cc75a91bc98

**Comment by IThinkIAmCool** [comment]
I was about to say that. Sorry.

**Comment by IThinkIAmCool** [comment]
@ryanbr You might want to add 

> ```
> ||max-adserv.com^$3p
> ||allittledprevi.info^
> ```

**Pull request merged**
