### PR TITLE
 bt-scene.cc

### PR DESCRIPTION
**Pull request by anewuser**
### URL(s) where the issue occurs

https://bt-scene.cc/the-holy-bible-king-james-version-tf5221623.html

### Describe the issue

Fake download buttons next to the real one.

### CODE REVIEW

**Comment by gorhill** [comment]
The following EasyList filter is already hiding these fake download buttons on my side:

    div > a[class][rel="nofollow"][onclick]

**Comment by okiehsch** [comment]
It isn't needed, the EasyList filter was added a few days ago https://github.com/easylist/easylist/commit/aeb3e53a0c60e13423d27a4c4bece35aa79d27dc, so his EasyList was probably not up to date when he added this filter.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/eb7855cd6e4196f07b7e5b72ce33bcd758b660e7

**Comment by SMed79** [comment]
@okiehsch mirrors https://github.com/easylist/easylist/commit/aeb3e53a0c60e13423d27a4c4bece35aa79d27dc#commitcomment-27921059

**Pull request merged**
