### PR TITLE
added some filters for link.ltc24.com

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by IThinkIAmCool** [comment]
I think I got a NSFW on that website after disabling uBlock Origin.

**Comment by mapx-** [comment]
provide a test link

**Comment by IThinkIAmCool** [comment]
Could you create one on link.ltc24.com?

**Comment by IThinkIAmCool** [comment]
`https://link.ltc24.com/dCpA`

**Pull request closed without merging**
