### PR TITLE
update #19976 youtube.com

### PR DESCRIPTION
**Pull request by ajayyy**
Based on my last one with mimeType (#20114). Checking if length > 3

Fake (7a13cbe7)
image

Real
image

### CODE REVIEW

**Comment by rojamet** [comment]
Works like a charm when added manually. Legend, saved my evening until it's merged.

**Comment by Sbmhawk** [comment]
Can confirm it works when added manually

**Comment by OothecaPickle** [comment]
Thanks!

**Review by miguelmazetto — APPROVED** [review]
Works when adding manually 👍

**Review by OothecaPickle — APPROVED** [review]

**Comment by 3052** [comment]
what the fuck, so they are hiding anti adblock JavaScript URLs as fake media URLs? is that what you are suggesting? if so that is fucking disgusting. at any rate great job

**Comment by CreationStory** [comment]
VECTOR 1 ALPHA 4 CAST CAST CAST HEAVY SPLASH!!!! GET DOWN *BOOOOOOMMMMMMM* HEAVY FLANK LEFT DELTA RIGHT GO GO GO DANGER CLOSE THIS IS WAR SOLDIER GET BACK UUUUUUUUUUUUUPPPPPPPPPPPPPPPPPPP HHHHHHHOOOOOOOOOORAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHH

**Comment by CreationStory** [comment]
You seem to have deleted my funny comment. So you are the same type of person as the people we are at war with lolol

**Comment by 0-x-2-2** [comment]
> You seem to have deleted my funny comment. So you are the same type of person as the people we are at war with lolol

posting cringe bro, not funny

**Comment by CreationStory** [comment]
u didnt even read it u big fat liar xD

**Review by jakeroxas — APPROVED** [review]

**Pull request merged**
