### PR TITLE
DropGalaxy Up

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://dropgalaxy.vip/1067702uyv4s`
Hopefully This Works For Most People Out There
If The Previous Solution Seems Better Than Then Its Better To Reject This One...I Hope This Would Decrease The Chance Of Anti Adb On FireFox

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
I can confirm it works for Firefox but

```
dropgalaxy.*##+js(rmnt, script, /.onerror|document.write|async|Error|sbmt|isMobileBrowser|navigator.userAgent|InstallTrigger|userTimezoneOffset|badip/)
dropgalaxy.*##+js(rpnt, script, /.onerror|.onload|.offsetParent/)
```

breaking the cloudflare ddos protection screen. Also i don’t understand

`||youtube.com^$domain=dropgalaxy.*`

You can merge the `no-xhr-if` and `no-fetch-if` filter.

**Comment by BlazeFTL** [comment]
@JobcenterTycoon I Tried Many Times But I Dont Get Any Cloudfare Screens Now At All...With Diff IP,Clear Everything..So Cant Test

YouTube Was Just Useless..For Clicking 3 Buttons No One Needs A Tutorial Also Reduced Bandwidth Usage..Can Be Removed If You Want

**Comment by JobcenterTycoon** [comment]
Try a crappy free proxy browser addon, it will trigger cloudflare 99%.

**Comment by BlazeFTL** [comment]
@JobcenterTycoon Can You Check Final Edit ?
I Still Think `youtube.com^$domain=dropgalaxy.* `
Bandwidth Waste🐸

**Comment by JobcenterTycoon** [comment]
`badip` crashing the cloudflare check. I prefer more safe filter like

`dropgalaxy.*##+js(rmnt, script, /div-gpt-ad-dropgalaxycom|script1\.async|InstallTrigger|userTimezoneOffset=userDate\[/)`

To make rpnt more safe you can use [condition](https://github.com/gorhill/uBlock/wiki/Resources-Library#replace-node-textjs-) so the rpnt filter will only be applied when specific string or regex being found.

**Comment by BlazeFTL** [comment]
I Had No Problem With Badip Tho...Anyway Removed...My Regex Capabilities Are Weak AF So I Dont Wanna Do Anything More🥱

**Pull request merged**
