### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by MasterKia**
Removed from uBlock Filters because Brave doesn't support ":upward()" for now.
The annoyance filter should be deprecated by now.

### CODE REVIEW

**Comment by MasterKia** [comment]
@JobcenterTycoon

**Comment by JobcenterTycoon** [comment]
Ok but i have a question about

```
||file.soft98.ir^$all,redirect=click2load.html
||cdn.hostdl.com^$all,redirect=click2load.html
```

For what are these filter?

**Comment by MasterKia** [comment]
Try
```
||file.soft98.ir^$all
||cdn.hostdl.com^$all
```
=> You get anti-adblock

Try
```
||file.soft98.ir^$all,redirect=1x1.gif
||cdn.hostdl.com^$all,redirect=1x1.gif
```
=> You get a nice big white square

**Comment by JobcenterTycoon** [comment]
```
||file.soft98.ir^$all,redirect=noopframe
||cdn.hostdl.com^$all,redirect=noopframe
```
Does not work?

**Comment by MasterKia** [comment]
Could you defuse their anti-adblock?

**Comment by MasterKia** [comment]
> ```
> ||file.soft98.ir^$all,redirect=noopframe
> ||cdn.hostdl.com^$all,redirect=noopframe
> ```
> 
> 
>     
>   
> 
> Does not work?

No I tried now.

**Comment by MasterKia** [comment]
They might defuse `redirect=click2load.html` tomorrow.
So defusing the anti-adblock is a priority.

**Comment by MasterKia** [comment]
@okiehsch Could you defuse this site's anti-adblock?

**Comment by JobcenterTycoon** [comment]
I see no anti adblock with your new filter even when i remove the `redirect=` filter

**Comment by MasterKia** [comment]
If you really want to just trigger the anti-adblock, get rid of all my filters and use:
`||file.soft98.ir^$all`

**Comment by MasterKia** [comment]
The reason I asked about defusing is because they're rapidly expanding the anti-adb.
Until today it couldn't detect `||file.soft98.ir^$all`, but now it can.

**Comment by JobcenterTycoon** [comment]
Ok now im understand. I tested a bit and

```
||cdn.hostdl.com^$all,redirect=nooptext
||file.soft98.ir^$all,redirect=nooptext
```

Works for me without the "nice big white square". I don’t know what they doing next so the best is to wait

**Comment by MasterKia** [comment]
Did you ever manage to (temporary) defuse aternos's anti-adb?

**Comment by JobcenterTycoon** [comment]
At the moment i don’t get anti adblock on aternos

**Comment by MasterKia** [comment]
Ah, so they just suffice to changing CSS names for now.

**Comment by JobcenterTycoon** [comment]
Yes

**Comment by MasterKia** [comment]
Lucky us.

**Comment by MasterKia** [comment]
@JobcenterTycoon Do you know why `soft98.ir##[href*="sysban.ir"]:upward(2):remove()` doesn't remove this?
Screenshot_20220805_095329

`https://soft98.ir/software/17418-Display-Driver-Uninstaller.html`

**Comment by JobcenterTycoon** [comment]
The link inside the box is `https://soft98.ir/software/17418-Display-Driver-Uninstaller.html` which get changed with javascript to `https://sysban.ir/charge/` thats why the filter not working

**Comment by MasterKia** [comment]
`which get changed with javascript to https://sysban.ir/charge/`
I searched for "sysban" string but couldn't find anything in the js files.

**Comment by JobcenterTycoon** [comment]
Pretty sure its encoded/obfuscated

**Comment by MasterKia** [comment]
They should have real dedication to this advertisement to come up with a solution like that.

**Comment by JobcenterTycoon** [comment]
I taked a look and have these filters against the anti adblock, the box and the amazon stuff
```
soft98.ir#@#[src*="file.soft98.ir"]:upward(5):remove()
soft98.ir###logo1 + div[class^="col-13"]:remove()
soft98.ir##article.card > div[id]:not([class^="card-"], [class="tab-content"]):remove()
```

**Comment by MasterKia** [comment]
> No needed anymore

I'm looking to come up with "stable" filters for the "sysban" box.

**Comment by JobcenterTycoon** [comment]
There are no stable filter. They can change the `.card` class or change `div` to `span` but its a bit more efford for them.

**Comment by MasterKia** [comment]
So "##[src*="file.soft98.ir"]:upward(5):remove()" isn't a stable filter?

**Comment by MasterKia** [comment]
> There are no stable filter.

The only stable filters are the ones depending on URL.

**Pull request merged**
