### PR TITLE
viprow. nu ads

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`https://www.viprow.nu/sky-sports-news-ssn-breaking-sports-news-online-stream-1`

### Describe the issue

popups

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: opera
- uBlock Origin version: 1.42.4

### Settings

-  uBO's default settings

### CODE REVIEW

**Comment by skip029** [comment]
This is happening again as of a week ago.

**Comment by stephenhawk8054** [comment]
@skip029 Can you give a URL that has video to play?

**Comment by skip029** [comment]
<https://www.viprow.nu/nfl-network-online-stream-2>
Live NFL Network - Link 2 Streaming Online - VIPRow<https://www.viprow.nu/nfl-network-online-stream-2>
viprow.nu<https://www.viprow.nu/nfl-network-online-stream-2>
[favicon-32x32.png]<https://www.viprow.nu/nfl-network-online-stream-2>


Sent from my iPhone

On Sep 19, 2022, at 9:01 PM, stephenhawk8054 ***@***.***> wrote:

﻿

@skip029<https://github.com/skip029> Can you give a URL that has video to play?

**Comment by stephenhawk8054** [comment]
@skip029 I get no ads and the video plays normally now. Can you force update the filter lists and test again?

**Comment by skip029** [comment]
Still nothing for me. If I disable Adguard Base video will show.

Sent from my iPhone

On Sep 20, 2022, at 2:25 AM, stephenhawk8054 ***@***.***> wrote:

﻿

@skip029<https://github.com/skip029> I get no ads and the video plays normally now. Can you force update the filter lists and test again?

**Comment by stephenhawk8054** [comment]
> Still nothing for me. If I disable Adguard Base video will show.

Adguard Base is not in default lists. You should report it to Adguard.

**Comment by skip029** [comment]
Ahhh thank you!!

Sent from my iPhone

On Sep 22, 2022, at 8:12 PM, stephenhawk8054 ***@***.***> wrote:

﻿

Still nothing for me. If I disable Adguard Base video will show.

Adguard Base is not in default lists. You should report it to Adguard.

**Pull request merged**
