### PR TITLE
fix https://github.com/AdguardTeam/AdguardFilters/issues/87134

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by mapx-** [comment]
- Don't send us to other repositories (adguard) without providing all the necessary info ("You need to be logged")
- I don't want to see anymore _**No description provided**_ in your posts

**Comment by IThinkIAmCool** [comment]
Do you want the account I made?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/64d61367626f80fecb721c96b709339b5c61fa36

**Comment by mapx-** [comment]
@IThinkIAmCool you can contact us on reddit (using pm) - see the moderators
https://www.reddit.com/r/uBlockOrigin/

**Pull request closed without merging**
