### PR TITLE
update (NSFW) `manga18fx.com` anti-adb

### PR DESCRIPTION
**Pull request by huyszn**
`https://manga18fx.com/`

### CODE REVIEW

**Comment by D4niloMR** [comment]
The carousel seems to be broken with uBO enabled for some reason, can you reproduce?

**Comment by huyszn** [comment]
The carousel works for me with uBO enabled.

**Comment by D4niloMR** [comment]
Seems to happen when verbose mode is enabled on the logger.

I see this in the console when it happens:

```
Uncaught TypeError: safe.uboLevel is not a function
    validate blob:https://manga18fx.com/78008b7c-4246-4bb0-8f4a-fa3947a32bb9:349
    get blob:https://manga18fx.com/78008b7c-4246-4bb0-8f4a-fa3947a32bb9:367
    jQuery 5

Uncaught ReferenceError: $ is not defined
    <anonymous> https://manga18fx.com/:1906

Uncaught ReferenceError: jQuery is not defined
    <anonymous> jQuery

Uncaught ReferenceError: $ is not defined
    <anonymous> https://manga18fx.com/js/script.js:1
```


@gorhill

**Comment by huyszn** [comment]
Oh okay, I was not using the dev build.

**Comment by gorhill** [comment]
Oops, it's supposed to be `uboLog`, not uboLevel` -- Absent-mindedness.

Will publish a new build soon.

**Pull request merged**
