### PR TITLE
Blocks ads on youtube videos

### PR DESCRIPTION
**Pull request by pedrogarcia**
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`youtube.com`

### Describe the issue

Blocks youtube ads.

### CODE REVIEW

**Comment by okiehsch** [comment]
image

Already part of `EasyList`

**Comment by pedrogarcia** [comment]
@okiehsch I don't see EasyList available as a subscription for uBlock. Is it turned on by default?

**Comment by pedrogarcia** [comment]
Nevermind, found it. Turns out I had hidden unsubscribed filters.

**Comment by okiehsch** [comment]
> Is it turned on by default?

Yes.

**Pull request closed without merging**
