### PR TITLE
update https://github.com/AdguardTeam/AdguardFilters/issues/90217

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`https://www.2embed.ru/embed/imdb/movie?id=tt10098288`

ref link = 

`https://www.d123movies.to/watch-movie-2/roohi-2021_cwj0kkn5k/j37bdx5-full-movie-free-online?WatchNow=1`

### Describe the issue

popups in new tab

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.37.2

### Settings

- uBO's default settings

### CODE REVIEW

**Comment by okiehsch** [comment]
`2embed.ru##+js(acis, Math, [$.)`
works on your end using chromium?

**Comment by ghajini** [comment]
yes, 

for firefox html filtering

**Comment by okiehsch** [comment]
It does not work for me using chromium due to a race condition.
`2embed.ru##+js(aeld, [$)`
prevents the popups on my end.
If you add that filter too I will merge, thanks.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5c3f0c19b7890404124c559b0db49cae6b162ad0

**Comment by ghajini** [comment]
this not work `2embed.ru##+js(aeld, [$)`may be due to race condition

**Comment by okiehsch** [comment]
Using Firefox `2embed.ru##^script:has-text(break;case $.)` get's rid of the popups no?

**Comment by ghajini** [comment]
In firefox everything works with help of 
`2embed.ru##^script:has-text(break;case $.)`

for chromium aeld filter not worked for me

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/795bcc96f4f99d3991787c7d86bc3dfae988c50d

**Pull request closed without merging**
