### PR TITLE
Update https://github.com/uBlockOrigin/uAssets/issues/8706

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs
```
https://send.cm/63b81dcgju9o
https://send.cm/lkq3rx1e9n3r
```
### Describe the issue

propeller ads

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox stable
- uBlock Origin version: 1.39

### Settings

- 
- uBO's default settings

### Notes

Reviews for different browsers
@mapx-, @okiehsch
any breakages

### CODE REVIEW

**Comment by mapx-** [comment]
why not the classic 
`send.cm##+js(acis, JSON.parse, break;case $.)`

**Comment by ghajini** [comment]
does not work always, comes after refresh

**Comment by Yuki2718** [comment]
> does not work always, comes after refresh

I wonder if other cases we have added HTML filter can also be resolved by changing to Promise. AG also uses this.

**Comment by ghajini** [comment]
> > does not work always, comes after refresh
> 
> I wonder if other cases we have added HTML filter can also be resolved by changing to Promise. AG also uses this. 

no, don't replace html filters, they are best

**Pull request merged**
