### PR TITLE
https://github.com/AdguardTeam/AdguardFilters/issues/76791 fix & made the fix closer to the one that was above

### PR DESCRIPTION
**Pull request by Alex4567890**
Edit: the link provided on https://github.com/AdguardTeam/AdguardFilters/issues/76791 is nsfw

### CODE REVIEW

**Comment by uBlock-user** [comment]
>  @@||assistir.one,nnaa66.xyz^$ghide

Invalid filter, can't append domains with network filters.

**Comment by Alex4567890** [comment]
> > @@||assistir.one,nnaa66.xyz^$ghide
> 
> Invalid filter, can't append domains with network filters.

I found out

**Comment by Alex4567890** [comment]
@uBlock-user did you take a look at https://github.com/uBlockOrigin/uAssets/pull/8673/commits/9c987143ec3633f8d8365c02d409a91b75017734 ?

**Comment by uBlock-user** [comment]
@Alex4567890 to append multiple domains, you must do it like this --

`@@*$ghide,domain=example.com|example2.com`

**Pull request merged**
