### PR TITLE
Unbreak ninjastream.to

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`https://ninjastream.to/watch/ExamDrwlNQR8M`

### Describe the issue

clicking on play does nothing

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.34.1b2

### Settings

-  uBO's default settings

### CODE REVIEW

**Comment by ghajini** [comment]
temp onhold

**Comment by ghajini** [comment]
2 things

1. Download doesn't work `https://ninjastream.to/download/zKWm6BBJ1m85P`

2. playback doesn't start here `https://ninjastream.to/watch/ExamDrwlNQR8M`

@mapx- @okiehsch

**Comment by mapx-** [comment]
adding

```
ninjastream.to#@#+js(nowoif)
ninjastream.to##+js(aeld, , 0x)
||ninjastream.to/js/lib.js
```

The download will start after 5-6 clicks
The video is running well

**Comment by ghajini** [comment]
would you come here @gorhill 
https://github.com/uBlockOrigin/uAssets/pull/8937#issuecomment-823277064
https://github.com/uBlockOrigin/uAssets/pull/8937#issuecomment-823243024

**Pull request closed without merging**
