### PR TITLE
Update annoyances for bluma

### PR DESCRIPTION
**Pull request by LewisJohnson**
Added book banner on bulma.io

Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://bulma.io/documentation/components/navbar/`

### Describe the issue

Large book banner

### Screenshot(s)

annoying af

### Versions

- Browser/version: Google Chrome 66.0
- uBlock Origin version: uBlock Origin v1.16.4

### Notes

They also have a 'sponsor' banner. I'm not sure if it fits into annoyances or filters.
```
! 08/05/2018, 11:42:00 https://bulma.io/documentation/components/navbar/
bulma.io##.bd-side-sponsors
```

sponser banner

### CODE REVIEW

**Comment by mapx-** [comment]
if the annoyances / ads can be fixed using simple (classic) filters, just report at easylist repository (for easyprivacy, annoyances too)
https://github.com/easylist/easylist/issues

**Comment by LewisJohnson** [comment]
Easylist is never updated.

**Comment by mapx-** [comment]
@ryanbr @monzta @Khrin

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/cb54a349059ca8a29b95cdaac7b40e5e5424575c

**Pull request closed without merging**
