### PR TITLE
Replace the Wikia recipe with a Fandom recipe

### PR DESCRIPTION
**Pull request by j-james**
Every site that used to be hosted on wikia.com has been moved to fandom.com.\
This PR updates the recipe to fandom.com and modifies it to work properly.

### CODE REVIEW

**Comment by llacb47** [comment]
Don't delete the `wikia.com` recipe, some sites haven't been moved yet. 
Example: `https://religion.wikia.org/wiki/Portal`

**Comment by j-james** [comment]
Wikia.com and wikia.org are separate domains - the original recipe didn't affect them. 

There's a lot of overlap, so here's a recipe for wikia.org anyway.

**Comment by llacb47** [comment]
Oops.

**Comment by krystian3w** [comment]
Or no moved newer if well understood Wikia on homepage?

**Comment by okiehsch** [comment]
@gorhill do you want to update existing recipes?

**Comment by j-james** [comment]
Merging with #6197

**Pull request closed without merging**
