### PR TITLE
Update #8041 pixiv.net placeholder

### PR DESCRIPTION
**Pull request by Yuki2718**
https://github.com/uBlockOrigin/uAssets/issues/8041

Any test/review/improvements by those who use Pixiv more extensively like @paperclip-dayo and @DandelionSprout  are welcome.

### CODE REVIEW

**Comment by DandelionSprout** [comment]
I am probably far too late to chip in on all this stuff, but these seem to be the most important entries I could find in 15min after a very long day of sleep:
```
!!! Assumes the absence of Pixiv Premium, or that "Ad display settings" at https://www.pixiv.net/setting_user.php is set to "Show".
!!! Also assumes that AdGuard Base is turned on.

! https://www.pixiv.net/en/ (Requires being logged on)
pixiv.net##div:not(.submit-area):has(:scope > iframe:not([src]))
pixiv.net##div[class^="sc-"]:has(:scope > div[style] > iframe[width="728"][height="90"])
pixiv.net##li[size]:has(:scope > div > iframe[name="topbranding_rectangle"])
! https://www.pixiv.net/en/tags/princess_dress
pixiv.net###root > div > div > div:has(iframe[name="footer"]):not(:has(img))
! https://www.pixiv.net/en/tags/%E4%BA%BA%E9%AD%9A%E3%82%B9%E3%83%BC%E3%83%84/artworks?mode=r18 (Requires being logged on and that R-18 is turned on in the user settings)
pixiv.net##li:has(:scope > iframe[name="infeed"])
```

I had an oddly hard time reproducing the rest of the Pixiv entries from Placeholder Buster.

**Comment by Yuki2718** [comment]
@DandelionSprout You're not too late, the commit has not been merged. Just curious, have you added the committed rules? I think e.g. `pixiv.net##div[class^="sc-"]:has(:scope > div[style] > iframe[width="728"][height="90"])` should be covered by `pixiv.net##iframe[width="728"][height="90"]:upward(2)`, not?

**Comment by DandelionSprout** [comment]
I didn't use the new rules at the time of testing, I just checked with uBO's logger which of the old entries I was even able to reproduce.

**Comment by Yuki2718** [comment]
Okay, we don't need to hurry. I have no problem to edit or close this PR. My rationale for the new rules are here: https://github.com/uBlockOrigin/uAssets/issues/8041#issuecomment-711010387 It's no harm to create rules from scratch, I think. I haven't tested R18 mode BTW.

**Comment by Yuki2718** [comment]
So thanks to @DandelionSprout 's help in the above comment I could find it:

pixiv

**Comment by paperclip-dayo** [comment]
Also a bit late to the party but thanks for cleaning up those pixiv rules 👍 
Did a quick browse of random pages and nothing appears to be broken.
In the meantime I did find a couple more of other empty placeholders after the ad banner gets killed that might be worth cleaning up.

Between comments and related images on the illustration pages:
illust

Manga page `https://www.pixiv.net/manga` top header:
manga_top

Manga page `https://www.pixiv.net/manga` between editors recommended and pixivision section:
manga_bot

Homepage `https://www.pixiv.net/`, closer to the top of the page, above "popular tags":
mainpage

**Comment by Yuki2718** [comment]
There's no too-late for a site like pixiv, it's near-impossible for a single person to make a perfect rule set without these helpful feedback. I'll check them later.

**Comment by Yuki2718** [comment]
Okay, everything except for the second SS could be covered by `pixiv.net##div[class^="sc-"]:has(> div[style] > iframe[width="728"][height="90"])`:

<details>

pixiv1

pixiv3

pixiv4

</details>

About the second, on my end it's not blank screen:

pixiv2

**Comment by paperclip-dayo** [comment]
Thanks, regarding the second ss, I checked with UBO off and it might be because I'm getting a different banner served from `pixon.ads-pixiv.net` 
banner

Makes sense to leave it untouched in this case I suppose since both are pixiv-related banners and not 3rd-party ads.

**Comment by Yuki2718** [comment]
@paperclip-dayo Actually most placeholder rules added are related to `ads-pixiv.net`. It's possible they serve ads to you but not to me. Can you right-click on the ads, choose 'Inspect element' (on Firefox, on Chromium it's 'Inspect') and take SS so that I can see DOM tree of that staff?

**Comment by paperclip-dayo** [comment]
I'm getting the same banner as you now, the one with free month of pixiv premium, so can't do that for now.
Gotta remember to do it next time I get a different banner from that server :)

**Pull request merged**
