### PR TITLE
this fixes #25

### LINKED ISSUE #25: Cosmetic Filter: Wired "Sponsored Stories by Outbrain"
### One or more specific URLs where the issue occurs

`http://www.wired.com/2016/04/wait-web-isnt-really-dead-google-made-sure/`

### Describe the issue

The content of Wired's sponsored stories powered by Outbrain just below each post is already blocked by both "hpHosts’ Ad and tracking servers" and "MVPS HOSTS". However, the HTML frame surrounding them is still present occupying prime real estate.

### Screenshot(s)

wiredcosmeticfilter

### Your settings

- Browser/version: Firefox 45.0.2 Windows
- uBlock Origin version: 1.6.8

### My Suggested Filter
`www.wired.com###around-the-web`

### PR DESCRIPTION
**Pull request by collinbarrett**

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks.

**Comment by collinbarrett** [comment]
Thank you! My first accepted pr on GitHub. Hopefully I did it all correctly. Keep up the great work on UBO!

**Comment by gorhill** [comment]
Normally the checksums have to be updated as well, but to encourage contributions I won't mind doing myself after one or more pull requests.

Also, I will provide a template for pull requests, so as to avoid having to open an issue, the pull request can be used as the issue reference if it is documented similarly.

**Comment by collinbarrett** [comment]
Gotchya, so in the future if I am going to submit a pr I will just do so and in the process it will give me a chance to create an issue for reference, rather than creating the issue first.

I'll need to look into checksums for the future. I understand the concept, but I've never worked with them and am not sure how to update them.

Thanks.

**Pull request merged**
