### PR TITLE
libertatea .ro - anti adb

### PR DESCRIPTION
**Pull request by WaterIsH2O**
example URL: `https://www.libertatea.ro/stiri/protest-la-bolintin-vale-dupa-moartea-unui-localnic-politistii-si-jandarmii-intervin-3925594`

### CODE REVIEW

**Comment by WaterIsH2O** [comment]
seems like `onnetwork.tv` anti adb

**Comment by WaterIsH2O** [comment]
@mapx- did you try to look at the video?

**Comment by mapx-** [comment]
Video working fine on my side FF / chrome.

**Comment by WaterIsH2O** [comment]
> Video working fine on my side FF / chrome.

oh, nvm lol

**Comment by WaterIsH2O** [comment]
I don't know what happened, maybe it was just unavailbale.

**Pull request closed without merging**
