### PR TITLE
https://forums.lanik.us/viewtopic.php?f=91&t=39633 (capital.fr)

### PR DESCRIPTION
**Pull request by SMed79**

### CODE REVIEW

**Comment by mapx-** [comment]
working too
`capital.fr##script:inject(abort-on-property-write.js, checkPub)`

**Comment by SMed79** [comment]
I referred to the filter added by @okiehsch here https://github.com/uBlockOrigin/uAssets/commit/0b6b6a5788e53f0948116a596e264e7710d2fc03

**Comment by mapx-** [comment]
does not matter, essentially is if working or not.

**Comment by SMed79** [comment]
Ok, would you please fix the below sites too.

* http\://photo.gala.fr/photos-johnny-hallyday-sa-villa-a-pacific-palissade-27450
`gala.fr##script:inject(setTimeout-defuser.js, checkPub, 6000)`

* http\://photo.femmeactuelle.fr/l-actu-du-03-01-18-27421
`femmeactuelle.fr##script:inject(setTimeout-defuser.js, checkPub, 6000)`

Thank you.

**Comment by okiehsch** [comment]
@SMed79 that fixes the specific sites but `gala.fr` redirects me to 
````
http://www.gala.fr/maf/telechargement#title=Stars : toute l'actu des stars - Gala&url=http://www.gala.fr/
````
can you reproduce that?

**Comment by SMed79** [comment]
> can you reproduce that?

No issue here ==>>  https://streamable.com/e/x7ulz/nswogo

**Comment by okiehsch** [comment]
If I go to for example 
````
http://www.gala.fr/l_actu/news_de_stars/exclu-france-gall-une-femme-tres-cash-mais-tres-maternelle-pour-lun-de-ses-derniers-collaborateurs_411245
````
and after the site has finished loading click the reload button, I get redirected to 
gala

**Pull request merged**
