### PR TITLE
Profitsfly Up

### PR DESCRIPTION
**Pull request by BlazeFTL**
`droplink.co/fVUapt`

### CODE REVIEW

**Comment by BlazeFTL** [comment]
@D4niloMR Can You Take A Look ?
I Cant Reproduce And People Saying Adb Detected

**Comment by D4niloMR** [comment]
I can only reproduce the site waiting for adclick

**Comment by BlazeFTL** [comment]
Seems That Was Again Added After Site Owner Saw I Commented It Out...I Didnt See Waiting For AdClick The Entire Day

**Comment by D4niloMR** [comment]
Yes, it's only on some links

**Pull request merged**
