### PR TITLE
Added minemytraffic.com (Web Browser Mining)

### PR DESCRIPTION
**Pull request by SMed79**
**URL**: `https://gomovies.co/`
**Script**: `https://minemytraffic.com/lib/xminer.min.js`

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks.

**Comment by SMed79** [comment]
@gorhill Please check the script file `dolladollabillz.js` at `goodolddownloads.com`

**Comment by gorhill** [comment]
I don't see any `dolladollabillz.js` loaded at that site. Can you be more explicit about what is the exact issue?

**Comment by mapx-** [comment]
the script is
`https://goodolddownloads.com//js/dolladollabillz.js?v=1506029593`

a lot of coinhive referrences

**Comment by gorhill** [comment]
Ok, I shift-reloaded the page, now I see it in the logger.

**Comment by gorhill** [comment]
Well the site makes it opt-in, and users can even adjust the mining parameters (from their DONATE page). Seems to me they do it right.

**Comment by SMed79** [comment]
Ok, thank you.

**Pull request merged**
