### PR TITLE
https://github.com/easylist/easylist/issues/12147#issue-1251695641

### PR DESCRIPTION
**Pull request by MasterKia**
https://github.com/easylist/easylist/issues/12147#issue-1251695641
Since EasyList maintainer @Khrin didn't like cooperating with the downstream.

All rules should be kept *until* PersianBlocker is added as default (hopefully).
The only rules which are too important and can't be removed are (until EasyList decides to add them):
```
tamin.ir#@#.ads2
@@||tamin.ir/content/ads/
```

### CODE REVIEW

**Comment by Yuki2718** [comment]
`webii.ir##.ads-box` appear to be indeed ads: `https://www.webii.ir/cat/digital`

**Comment by MasterKia** [comment]
> ##.ads-box

image

The website title is "وب سایت تبلیغات و نیازمندیها درج آگهی رایگان` which roughly translates to `Free advertising (and selling stuff) website where you can submit your goods to sell`.

**Comment by Yuki2718** [comment]
Hmm, so the website itself is for ads. I'm not sure if we should unblock. Similar to https://github.com/uBlockOrigin/uAssets/pull/10149#issuecomment-951821141 , user can turn blocker off on such sites. @mapx- @okiehsch

**Comment by MasterKia** [comment]
> Hmm, so the website itself is for ads. I'm not sure if we should unblock. Similar to [#10149 (comment)](https://github.com/uBlockOrigin/uAssets/pull/10149#issuecomment-951821141) , user can turn blocker off on such sites. @mapx- @okiehsch

It's not for ads per say, is eBay for ads where people can sell their own stuff?

**Comment by Yuki2718** [comment]
`@@1000site.ir/home/ads/asset/favicon.ico` unblocks ad too but it's addressed by your list (`1000site.ir##.col-md-offset-6.col-md-3`). However, such cases are unlikely to be addressed by EL when the breakage is acceptable. Anyway you forgot `||`.

**Comment by Yuki2718** [comment]
`sourceiran.com/wp-content/uploads/300-250.jpg` is self promotion and it's fair not to unblock:
https://easylist.to/pages/policy.html
> Self-promotion should not be specifically removed by EasyList, although equally should not be allowed if it is blocked.

https://github.com/uBlockOrigin/uAssets
> The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by EasyList/EasyPrivacy policies

Anyway `@@||sourceiran.com/wp-content/uploads/*.jpg` alone doesn't work, `sourceiran.com#@#.ads-widget` is also needed - kinda too much to unblock single self-promo.

**Comment by MasterKia** [comment]
I'll take back `sourceiran.com` from uBlock unbreak but can I address it in PersianBlocker?

**Comment by Yuki2718** [comment]
> I'll take back `sourceiran.com` from uBlock unbreak but can I address it in PersianBlocker?

Why not as that's your list?

**Comment by MasterKia** [comment]
> `sourceiran.com#@#.ads-widget` is also needed

BTW I had added this in my list, but forgot to include it in this PR.

**Comment by MasterKia** [comment]
> Similar to `https://github.com/uBlockOrigin/uAssets/pull/10149#issuecomment-951821141`

On that note, I noticed that `clickyab.com` (a Persian site dedicated to ads) is blocked in Pete Lowe's list and I did this: 
```
@@||clickyab.com^$1p
||clickyab.com^$3p
```
Is this a wrong approach according to that comment from gorhill?

**Comment by mapx-** [comment]
usually 
`||clickyab.com^$badfilter`

and not `@@||clickyab.com^$1p`

**Comment by Yuki2718** [comment]
```
cooldl.net#@#.ads-box
cooldl.net#@#.ads-content
```
self-promo too

**Comment by Yuki2718** [comment]
```
@@||beytoote.com/ads/images_pc/$image
@@||beytoote.com/ads/images_mob/$image
```
merge to single rule `@@||beytoote.com/ads/images_$image,1p`

**Comment by MasterKia** [comment]
> usually `||clickyab.com^$badfilter`
> 
> and not `@@||clickyab.com^$1p`

Fixed, I understand and like the concept of "badfilter" but does do any **harm** when unblocked using `^$1p`?

**Comment by Yuki2718** [comment]
> 
> Fixed, I understand the concept of "badfilter" but does do any **harm** when unblocked using `^$1p`?

Depends on site but can allow too much - there may be something to be blocked by generic rules.

**Comment by Yuki2718** [comment]
`@@||beytoote.com/ads/js/*$script,1p` will be needed too (bottom slider broken).

**Comment by MasterKia** [comment]
Also `@@||ads.beytoote.com/live_chat`, breaks the chat function in ` beytoote.com/ads/advertising.php`.

**Comment by Yuki2718** [comment]
Lastly can you take more detailed screenshot(s) of `tamin.ir` (DOM tree)? Some government sites actually deliver ads.

**Comment by MasterKia** [comment]
`https://github.com/easylist/easylist/issues/12152#issue-1251779583`:
https://user-images.githubusercontent.com/17685483/170851340-3e9db42b-bd2f-434c-93d9-dd502c04eb68.png
https://user-images.githubusercontent.com/17685483/170851305-73cd03da-b834-4a9f-a332-10b5a6b9934c.png

I could take more if you want

**Comment by MasterKia** [comment]
image

**Comment by Yuki2718** [comment]
No need, so they're links to subpages of Iranian Social Security Organization.

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7edc8a78db0143793672fdf9ab80d728aa752cdf

**Comment by Yuki2718** [comment]
Adjusted a bit: https://github.com/uBlockOrigin/uAssets/commit/40a47e0629d4a4fd993bcea516245a2da810e3f0 I'll copy them to AG list.

**Comment by MasterKia** [comment]
Should I keep them or remove them?
PersianBlocker if used with uBO and AG should be fine since these unbreak filters are present in both.

But if used with ABP, I guess they don't have an unbreak list and rely on EasyList.

**Comment by Yuki2718** [comment]
We want to keep minimal rules in our lists.

**Comment by MasterKia** [comment]
@Yuki2718 Is there any chance that PersianBlocker could be added PersianBlocker to AG as well?

https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository
I guess PersianBlocker currently doesn't satisfy the requirements of number 4 unfortunately.

**Comment by MasterKia** [comment]
https://github.com/easylist/easylist/issues/12152#event-6697876692

Spam?!
I don't understand this hostility from @Khrin, the EL maintainer.
Does he have a problem with Persian websites?

**Comment by MasterKia** [comment]
https://github.com/easylist/easylist/issues/12152#event-6697876692

@ryanbr 

Could you please tell me how that qualifies as spam?
I don't understand this hostility from @Khrin, the EL maintainer.
Does he have a problem with Persian websites?

**Pull request merged**
