### PR TITLE
Parked domain: 123moviesgo.ga

### PR DESCRIPTION
**Pull request by Omega-6**
Could someone check if the domain parking network doesn't use redirection ads?

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
The domain is still active https://urlfilter.adtidy.org/v2/checkDomain?domain=123moviesgo.ga but https://github.com/uBlockOrigin/uAssets/pull/21057/commits/295000effe99ba7083bedad64522bd2189e5a8a1 is good

**Comment by Omega-6** [comment]
AdGuard had a domain checker??

**Comment by JobcenterTycoon** [comment]
Yes its public.

The site redirect me to a ad site. But the site is blocked after i reported the domain upstream.

**Comment by krystian3w** [comment]
IMO is parked so CSS filters can be removed due move to badware risk:

https://github.com/uBlockOrigin/uAssets/blob/9063c0611fa3b86e0d8c3f4777e762aff2ad443b/filters/badware.txt#L3359-L3363

**Pull request merged**
