### PR TITLE
unitrading.blog: badware

### PR DESCRIPTION
**Pull request by cirx1e**
### URL(s) where the issue occurs

`https://unitrading.blog/`

### Describe the issue

Cryptocurrency MEV bot scam

### Notes

> **How the Scam Works:** Victims are enticed by catchy headlines and positive comments on scam videos. They are encouraged to load their wallets with ETH and follow the set-up process, which involves copying a smart contract code to create the bot. They are then asked to deposit ETH into the MEV bot address, resulting in the loss of all funds. Some scams even involve competing with well-funded MEV bots, ensuring the victim's assets are lost.

Source: [Protect Yourself from the Ethereum MEV Bot Scam](https://coinmarketcap.com/community/articles/64ae977bfaeb0a57c182e1e4/)

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
The site is dead.

**Comment by cirx1e** [comment]
> The site is dead.

The website is still accessible on my side.

https://dnschecker.org/all-dns-records-of-domain.php?query=unitrading.blog&rtype=A&dns=google

**Comment by JobcenterTycoon** [comment]
With your tool i get

result

**Comment by cirx1e** [comment]
It seems that this domain has been deleted (or expired), but somehow Google DNS (`8.8.8.8`) is still returning DNS records at that time.

**Pull request closed without merging**
