### PR TITLE
infinityscans.xyz Up

### PR DESCRIPTION
**Pull request by BlazeFTL**
`infinityscans.xyz`

### CODE REVIEW

**Comment by mapx-** [comment]
in chromium it's difficult with the race condition

**Comment by BlazeFTL** [comment]
> such exceptions

On My Side FF,Chrome Both Works With script,xhr

**Comment by mapx-** [comment]
maybe now we can remove 
`@@*$script,xhr,domain=infinityscans.xyz`
?

**Comment by BlazeFTL** [comment]
@mapx- I Never Needed It

**Comment by BlazeFTL** [comment]
> firefox android where html filter not worked

Mention Gorhill

**Comment by mapx-** [comment]
I get detection in android

**Comment by BlazeFTL** [comment]
Now For FF This Is Needed.. Chrome Works Bcz Of Script,xhr Allowed
```
@@||cdn.prplads.com^$script,domain=infinityscans.xyz

**Comment by BlazeFTL** [comment]
I Say Let's Allow Script,xhr For FF Also...Let The Site Owner Waste His Time By Adding New Scripts,Xhr Checks

**Comment by mapx-** [comment]
yes, I added `@@*$script,xhr,domain=infinityscans.xyz` in android and is working

However, we could add it only for mobile

**Comment by BlazeFTL** [comment]
> only for mobile

There's No Saying That It Would Always Work For Mobile...

Allow For Everything

**Comment by BlazeFTL** [comment]
> nothing left to block ads

No Ads Can Get Through...But The Same Goes For Every Problem... Defusing At Root Level For Less Exceptions Would Take Time...If Anyone Interested Go Ahead

**Pull request merged**
