### PR TITLE
Fix DG

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://dropgalaxy.com/drive/ngqdesnq0pqp`

### CODE REVIEW

**Comment by BlazeFTL** [comment]
@mapx- Can I Get Write Access For A Week ?
Its Hard Testing Like This...

**Comment by mapx-** [comment]
@okiehsch's call

**Comment by okiehsch** [comment]
Why is it easier to test issues if you have write access?


How would it

**Comment by BlazeFTL** [comment]
Although I Am Doin This Because I Wanna Burn Site Owners *
I Made A Mistake In Rule Again...Opening Too Many PRs At This Point
As I Said I Wouldnt Touch Anything Else Other Than What I Manage

**Comment by okiehsch** [comment]
> I Dont Plan On Doin This Forever Just For A Week Maybe

What's the point? Do you think the site will stop after a week?

**Comment by BlazeFTL** [comment]
Maybe Run Out Of Detection Ideas...Anyway Forget It

**Comment by okiehsch** [comment]
Ok, if you think you made a mistake in one of your pull requests, just tell us and we will remove it ourselves, there is no need to open an new pull request  just for the removal of a filter.

**Comment by BlazeFTL** [comment]
@mapx- Could You Comment This One Out
```adblock-filter-list
dropgalaxy.*##+js(trusted-replace-node-text, script, /s.src =|s.src/i)
```

**Comment by okiehsch** [comment]
Done.

**Comment by Omega-6** [comment]
`https://github.com/AdguardTeam/AdguardFilters/issues/167686`

`https://dropgalaxy.vip/e4655ievv4c4`

after waiting, download button doesn't appear on the screen

**Comment by BlazeFTL** [comment]
@Omega-6 Report Issues Where They Should Be Reported Not Comment Here

**Comment by Omega-6** [comment]
actually, that's how issues are supposed to be reported here, rather than creating a bunch of new issues for the same site

**Pull request merged**
