### PR TITLE
Fix https://github.com/uBlockOrigin/uAssets/issues/22181

### PR DESCRIPTION
**Pull request by BlazeFTL**
`pointlinks.in/BT1SC`
`https://devuploads.com/9r8rquznfkfs`

### CODE REVIEW

**Comment by mapx-** [comment]
@BlazeFTL the PR had some conflicts

**Comment by BlazeFTL** [comment]
@mapx- I PR'ed Long Ago & Commented On Those Issues...But ghajni Ignored & Marked As "Spam"

**Comment by BlazeFTL** [comment]
Not taking The Better Solution Here https://github.com/uBlockOrigin/uAssets/commit/12081185b3314717cd302c005044e4079e92b30c

Organizing According To Alphabet Even When The Domains Aren't Used & Has To Be Cleaned Regularly & Marking My Comment As Spam https://github.com/uBlockOrigin/uAssets/commit/4aeab00cf9ba7e9ae3f5983094177d904e414a6a

Is He Even "Fit" To Be A Maintainer ?
When I Asked For Write Access..I Thought I Was Denied Because I Had "Bad Behavior"...But In None Of Those Cases I Started Those

**Comment by BlazeFTL** [comment]
> can't force me to do as per you

Lets See

**Comment by okiehsch** [comment]
> Is He Even "Fit" To Be A Maintainer ?

He is.

> When I Asked For Write Access..I Thought I Was Denied Because I Had "Bad Behavior"...But In None Of Those Cases I Started 


> Is He Even "Fit" To Be A Maintainer ?

He is.

> When I Asked For Write Access..I Thought I Was Denied Because I Had "Bad Behavior"

You said you only want it for a "week or so" and I declined that because it makes no sense to me.

**Comment by BlazeFTL** [comment]
> He is.

His Actions Arent...I Can List All The Abnormalities Of Him Here...But I Dont Wanna Waste Time

My Contributions Are Legit Useless I Guess... Because Even If You Had Given Me Write Access That Benefit Me Other Than Make My Contributions Easier

**Comment by okiehsch** [comment]
> My Contributions Are Legit Useless I Guess... Because Even If You Had Given Me Write Access That Doesnt Benefit Me Anything Other Than Make My Contributions Easier

What benefits do you have in mind? And why bring up that you were denied write access if you really don't want it in the first place?

**Comment by okiehsch** [comment]
> Organizing According To Alphabet Even When The Domains Aren't Used & Has To Be Cleaned Regularly

Btw I am still doing that if I do a commit and see that the filters I have to change are not ordered alphabetically, it's just my personal preference, so maybe I am not "fit "too.

**Comment by BlazeFTL** [comment]
> am not "fit" to

I Said That Because Hes All Previous Actions...I Mentioned Jobcenter And Mapx On 4-5 More Commits Where All He Did Was Remove All Filters For DG

**Comment by okiehsch** [comment]
> For Gplinks Organizing According To Alphabet Is A Extra Hassle As The Domains Have To Removed According To The Date They Get Added

He rearranged them in the commit you linked to. it's something I have done many times, what I have never done is declining a pull request because it was not oredered alphabetically, that would be wrong imo.

**Comment by BlazeFTL** [comment]
> It's something I have done many time

You Just Didnt Get It..Did You ?
Lets Say You Sort All Gplinks Domains Alphabetically...Now You Have 10 Domains There & 8 Of Them Aren't Used Anymore How Would You Remove The Useless Domains ? Buy Remembering The Domains ?

**Comment by okiehsch** [comment]
> Lets Say You Sort All Gplinks Domains Alphabetically...Now You Have 10 Domains There & 8 Of Them Aren't Used Anymore How Would You Remove The Useless Domains ? By Remembering The Domains ?

That's a fair point, in that case rearranging them is not helpful.

**Comment by BlazeFTL** [comment]
> rearranging them is not helpful.

He Did That twice Even After Telling Him Not To

**Comment by BlazeFTL** [comment]
I Wanted Write Access Just So I Could Contribute..& At Any Point You Feel I Shouldn't Have Write Access You Can Just Remove That Cant You ?😆

**Comment by okiehsch** [comment]
So you now want write access even thogh an hour ago you said
"My Contributions Are Legit Useless I Guess... Because Even If You Had Given Me Write Access That Doesnt Benefit Me Anything Other Than Make My Contributions Easier"
?

**Comment by okiehsch** [comment]
Contributions are never usesless you obviously contribute quite a bit.

It's not about begging, I asked you https://github.com/uBlockOrigin/uAssets/pull/20990#issuecomment-1835838982
and you declined. That's fine by me and you don't have to explain yourself unless you change your mind.

**Comment by BlazeFTL** [comment]
As I Said https://github.com/uBlockOrigin/uAssets/pull/20990#issuecomment-1835849221

I Am Not That Active Now...Just Maintaining A Few Sites...You Say Dont Add Trusted Click Element...& I Didnt A Single Commit After That...So No Discussion Needed

**Comment by okiehsch** [comment]
Ok.

**Comment by BlazeFTL** [comment]
Obsolete? Thats Why It Gets Reverted ?
Which Filter Policy Said We Cant Use Broad Exceptions ?
DG,DevUP Still Working For Me..
Server Side ? They Are The Most Advance Guys ? To Implement Server Side Detection Right ?

Dont Blame Region Based Problems On Me And Provide A Fix That Works For Everyone ?

**Comment by BlazeFTL** [comment]
@adsdestroyer Elaborate Yourself..What Exactly Is Caused By Me ? Numerous Issues ?...You Probably Use 20 + Third Party Filters

**Comment by BlazeFTL** [comment]
Just A Proof Of My Work - https://github.com/AdguardTeam/AdguardFilters/issues/171489#issuecomment-1910105683

**Pull request merged**
