### PR TITLE
Fix affiliate.fc2.com: anti-adblock message

### PR DESCRIPTION
**Pull request by Yuki2718**
### URL(s) where the issue occurs

`https://affiliate.fc2.com/`

### Describe the issue

Unobtrusive anti-adblock

### Screenshot(s)

fc2

### Versions

- Browser/version: Brave 1.8.86
- uBlock Origin version: 1.26.0

### Settings

- Default + Fanboy's Annoyances + uBlock Annoyances

### CODE REVIEW

**Comment by mapx-** [comment]
it's preferable `@@||affiliate.fc2.com^$ghide`
Could you modify your commit ?

**Comment by Yuki2718** [comment]
> 
> 
> it's preferable `@@||affiliate.fc2.com^$ghide`
> Could you modify your commit ?

Sure, to what?

**Comment by mapx-** [comment]
`@@||affiliate.fc2.com^$ghide` is working on my end

**Comment by Yuki2718** [comment]
> 
> 
> `@@||affiliate.fc2.com^$ghide` is working on my end

Can you test from Japanese IP?
No cosmetic filter applied after adding `@@||affiliate.fc2.com^$ghide`.

fc2

**Comment by mapx-** [comment]
tested jpn ip too, same result, ghide working fine

**Comment by mapx-** [comment]
added, even if I don't understand why this different behaviour

**Comment by Yuki2718** [comment]
> 
> 
> added, even if I don't understand why this different behaviour

Thx, I have no idea about the difference.

**Pull request merged**
