### PR TITLE
Add domains

### PR DESCRIPTION
**Pull request by iam-py-test**
### URL(s) where the issue occurs
```
freedownloadfiles.org
fruegelke.xyz
ec2-34-213-49-207.us-west-2.compute.amazonaws.com
hh3valve.com
shib-inu.cc
ether-give21.net
198.46.136.245
```

### Describe the issue

Unblocked scam, phishing, and malware domains

### Screenshot(s)

image
image
image
image

### Versions

- Browser/version: Firefox 94.0.1
- uBlock Origin version: uBlock Origin 1.38.7rc0

### Settings

- Advanced user mode: Enabled
- Filters:
Built-in, Ads, Malware domains, Multipurpose: All enabled
All privacy except AdGuard URL Tracking: Enabled
Annoyances: EasyList Cookie, Fanboy’s Annoyance, uBlock filters – Annoyances
Regional: NOR, DNK, ISL: Dandelion Sprouts nordiske filtre
Custom:
image
image

### Notes

This is a combination of several separate malware/phishing/scam operations. For more details, see the comments above each entry

### CODE REVIEW

**Comment by Yuki2718** [comment]
Are you sure that all the download from `freedownloadfiles.org`, not just one, are malicious? Also `ec2-34-213-49-207.us-west-2.compute.amazonaws.com` is nonsense, it varies by your locaion etc.

**Comment by Yuki2718** [comment]
You have to provide full URLs as far as possible.

**Comment by okiehsch** [comment]
> Are you sure that all the download from freedownloadfiles.org, not just one, are malicious?

I would certainly not recommend downloading and installing anything from it but the site is open about offering downloads of cracked software they are not trying to dupe anybody.
That is out of scope of uBO-badware imo.

**Comment by iam-py-test** [comment]
Sorry for the late reply
> 198.46.136.245 is blocked by Online Malicious URL Blocklist

Sorry about that. I removed that entry. The reason I didn't see that is because I already had a $all rule in place blocking it

> I would certainly not recommend downloading and installing anything from it but the site is open about offering downloads of cracked software they are not trying to dupe anybody.

Its not offering cracked software, it is offering a trojan which _pretends_ to be cracked software. I did run it on a VM just to check by the way.
<details>
Claims to be a WinRAR crack, but just looks generic (no WinRAR icon or properties)
Creates a ton of malware processes but opens no GUI:

I think it stopped working as my firewall blocked it from communicating. <br>
This is one of processes it created: 

42 detentions and claims to be something it isn't, plus having no GUI, makes it MAL in my book. <br>
Second opinion scanners: <br>
I tried launching Autoruns but the malware kept killing it. 
</details>

> Are you sure that all the download from `freedownloadfiles.org`, not just one, are malicious?

I didn't check every single one, but I checked a few. All identical files inside the RARs.

**Comment by Yuki2718** [comment]
@iam-py-test Remove `ec2-34-213-49-207.us-west-2.compute.amazonaws.com` and `fruegelke.xyz`, it's different on my end and I guess only used on this site so blocking `freedownloadfiles.org` should be suffice. Even if not, better to use generic filter or regex.

**Comment by Yuki2718** [comment]
Removed `hh3valve.com`. It doesn't make sense to block c2 server by browser extension.

**Pull request merged**
