### PR TITLE
Update badware.txt

### PR DESCRIPTION
**Pull request by shenzhiming88**
The software will upload and delete files secretly

### CODE REVIEW

**Comment by Yuki2718** [comment]
Interesting, the site claims FP:

> Special reminder: Antivirus will intercept the robot's control of the game. If you encounter any problems, please try to exit Antivirus, such as QQ Computer Manager, 360.
Important reminder: Individual antivirus will falsely report this software, please don't believe it, this software is not Virus Trojan, please exit the antivirus before running the assistant (usually Tencent’s computer housekeeper will deliberately misreport this software and intercept the actions of the robot)
49 well-known antivirus engines in the world online virus check URL http://www.virscan.org

**Comment by shenzhiming88** [comment]
@Yuki2718 Haha, this is of course a lie, malicious sites will certainly claim to be clean
You can check this link: https://www.huorong.cn/info/1617368984641.html

**Comment by shenzhiming88** [comment]
@uBlock-user Hello!
VirusTotal:`https://www.virustotal.com/gui/file/5d95b04f1931e30470f6f02d5eb089570a5df24aaea3e9fb5e22574693bf5eec`
IMG_20210730_205325

**Comment by shenzhiming88** [comment]
@uBlock-user

**Pull request merged**
