### PR TITLE
Fix https://github.com/easylist/easylist/issues/17251 without exception

### PR DESCRIPTION
**Pull request by FanOfRootBeer**
- overrides gtm exception
- still unbreaks

### CODE REVIEW

**Comment by mapx-** [comment]
I guess you'll break some functionality

**Comment by FanOfRootBeer** [comment]
Should the blocking filter have been more specific?

**Comment by mapx-** [comment]
I guess @dimisa-RUAdList could respond. If it's ok could be added in the regional list.

**Comment by dimisa-RUAdList** [comment]
Ok, fixed in RU AdList: https://github.com/easylist/ruadlist/commit/5677317750757691541ddee827739da6ada5c932

**Pull request closed without merging**
