### PR TITLE
address https://github.com/AdguardTeam/AdguardFilters/issues/179947

### PR DESCRIPTION
**Pull request by dportvine**

### CODE REVIEW

**Comment by stephenhawk8054** [comment]
I think it's better be added to EL annoyance list

**Comment by dportvine** [comment]
This banner appears every time, the user's choice is not stored in cookies. You can also download the APPS below and choose a platform.

<details>
<summary>Screen</summary>


</details>

Also, I see at least two rules in this filter that are clearly not ads
https://github.com/uBlockOrigin/uAssets/issues/17905
https://github.com/uBlockOrigin/uAssets/issues/22973

**Comment by stephenhawk8054** [comment]
I can't check lazada page, but for timesofindia, there's no options for users to close the popup, unlike this case.

But in case the popup appears at every load, it can be addressed.

**Comment by dportvine** [comment]
> But in case the popup appears at every load, it can be addressed.

Here's the video if you don't believe me.
<details>
<summary>Screen</summary>

https://github.com/uBlockOrigin/uAssets/assets/111344219/3b2c8124-b137-445a-b598-a9224b842e61
</details>

**Pull request merged**
