### PR TITLE
update https://github.com/uBlockOrigin/uAssets/issues/10321

### PR DESCRIPTION
**Pull request by sugarfreesweetener**
https://github.com/uBlockOrigin/uAssets/issues/10321

### CODE REVIEW

**Comment by sugarfreesweetener** [comment]
oops, has more commits than I expected

**Comment by sugarfreesweetener** [comment]
`*$image,redirect-rule=1x1.gif,domain=freevpn4you.net`

@mapx-

**Comment by mapx-** [comment]
I don't understand this PR

Split it in coherent ones.

**Comment by sugarfreesweetener** [comment]
it was supposed to be an update for https://github.com/uBlockOrigin/uAssets/issues/10321

https://github.com/uBlockOrigin/uAssets/pull/14872/files#diff-4c4f42122f8aa0b951dfae2559543e589a1cb85689c53cd93601d7fafb67b321R5612 looks like what I wanted this PR to look like

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/127cbc02da88bd0f2659c3249563fa41bf2f52a2

**Pull request closed without merging**
