### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by MasterKia**

### CODE REVIEW

**Comment by krystian3w** [comment]
Add enforce inline block to avoid jump word to origin pop-up line.

https://www.w3schools.com/cssref/pr_class_display.asp

**Comment by MasterKia** [comment]
Could elaborate using an example?

**Comment by krystian3w** [comment]
Yes, for your [pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements).

**Comment by MasterKia** [comment]
I tried but I can't spot the difference.

> to avoid jump word to origin pop-up line.

Could you send screenshots from A vs B?

A) `soft98.ir##body > :nth-of-type(1):before:style(content: "Some text" !important; color: #ff0000 !important; visibility: visible !important; font-size: large !important;)`

B) `soft98.ir##body > :nth-of-type(1):before:style(content: "Some text" !important; color: #ff0000 !important; visibility: visible !important; font-size: large !important; display: inline-block; !important;)`

**Comment by krystian3w** [comment]
More mean toast pop-ups, but for now gone, so I can only draw glitch by "rectangles":

obraz

I try move 3-rd "rectangle" above white text:

obraz

**Pull request merged**
