### PR TITLE
Fix Multi

### PR DESCRIPTION
**Pull request by BlazeFTL**
`go.publicearn.com/sbA5oJXw/?uid=549872`
`http://devuploads.com/gp74hvcgow1q`
`https://dropgalaxy.vip/1vzd0c64tf8n`
`https://tech.hipsonyc.com/?token=e2dGX9Go`

### CODE REVIEW

**Comment by BlazeFTL** [comment]
@mapx- Is Link Shortner List Available For Use ?

**Comment by mapx-** [comment]
sure

**Comment by BlazeFTL** [comment]
Is It Default? Or Something Users Have To Enable Manually?

**Comment by BlazeFTL** [comment]
I Dont See It In FilterList ?.. Integrated Into UBO Ads ?

**Comment by mapx-** [comment]
integrated (like filters-2021.txt for example) but you can see it here

https://github.com/uBlockOrigin/uAssets/tree/master/filters

https://github.com/uBlockOrigin/uAssets/blob/master/filters/ubo-link-shorteners.txt

**Comment by BlazeFTL** [comment]
Ok...I Will Move Somethings There Next Time If I Can...

Updating Filters After 30 Minutes I Dont See My Rules Getting Updated...Is It Due To Gorhills Bandwidth Saving Movement?

**Comment by mapx-** [comment]
yes, exactly.

You can try shift-click (if you are on uBO dev build) or go to a link like this:

https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters,ublock-privacy,ublock-unbreak,ublock-quick-fixes,easylist,easyprivacy,ublock-annoyances

**Comment by BlazeFTL** [comment]
I Reset UBO & Tried Again & I Wonder How This Got Unblocked & I Am Still Getting The Old Rules😪
[Screenshot_2023-12-17-22-06-47-361_org mozilla fenix](https://github.com/uBlockOrigin/uAssets/assets/139938337/da9cafb8-fb5a-4a5d-a0ba-ade4b6c9eeb3)

**Comment by BlazeFTL** [comment]
These Rules Are Still There In Assest Viewer
[Screenshot_2023-12-17-22-16-14-719_org mozilla fenix](https://github.com/uBlockOrigin/uAssets/assets/139938337/52855e41-48dd-4006-8f8c-085141c4c390)

QuickFix Isnt QuickFix Anymore😂

**Pull request merged**
