### PR TITLE
This fixes #430

### LINKED ISSUE #430: freeroms.com
### URL(s) where the issue occurs

http://www.freeroms.com/dl_roms/rom_download.php?title=e_t_-the_extra_terrestrial&system=Atari&game_id=3131

### Describe the issue
This sites shows a suspicious download link to an .exe file by default, and sets a timer to show the actual download link.

A standard rule to hide the link (`freeroms.com##a.download`) breaks the alignment of  the filesize/votes/rating columns. Just setting the element `visilibity` to `hidden` instead doesn't have this problem.

### Versions

- Browser/version: Firefox 53.0.3
- uBlock Origin version: 1.12.4

### PR DESCRIPTION
**Pull request by anewuser**
This fixes #430.

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks.

No need to open a separate issue, you can just describe the issue in the pull request itself.

**Comment by SMed79** [comment]
Reported at easylist forum https://forums.lanik.us/viewtopic.php?p=118921

**Comment by anewuser** [comment]
@SMed79 Your solution hides the information row completely. The ratings appear in the alphabetical lists, but not the file sizes.

**Comment by SMed79** [comment]
OK, thanks.

**Pull request merged**
