### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by MasterKia**

### CODE REVIEW

**Comment by MasterKia** [comment]
@JobcenterTycoon @okiehsch @mapx- @stephenhawk8054

**Comment by okiehsch** [comment]
Do you want write access, so you can make changes without going through this 10 times a day?

**Comment by MasterKia** [comment]
That's up to gorhill.
Sorry if I'm bothering you, won't happen again.

**Comment by okiehsch** [comment]
It's actually up to me.

**Comment by MasterKia** [comment]
Then given that, I'll only edit the soft98 section of the quick-fixes.txt file.

**Comment by okiehsch** [comment]
Invitation has been sent to your email.

**Comment by okiehsch** [comment]
Btw you are not bothering me but it's just easier for you to simply edit the quick-fix list by yourself.

**Comment by MasterKia** [comment]
> Invitation has been sent to your email.

Done.

**Pull request merged**
