### PR TITLE
Added a phishing website (Updated badware.txt)

### PR DESCRIPTION
**Pull request by Radplay**
Added a phishing website (distributes a malicious Android app)
https://www.virustotal.com/gui/url/be0c9fe136dc5818a82880ead977e8adca954045557b33a78259ebd10890935e/detection
https://www.virustotal.com/gui/url/be0c9fe136dc5818a82880ead977e8adca954045557b33a78259ebd10890935e/community

### CODE REVIEW

**Comment by mapx-** [comment]
I see 0 detections on virus total. some other info ?

**Comment by Yuki2718** [comment]
`revanced.io` is not a phishing but a fun site of Revanced (similar to `ublockorigin.com`) distributing unofficial apk as described in `https://revanced.io/about/`. So far no clear sign of malicious activity has been reported. Please do not rely solely on VT community feedback, particularly if its by only one commenter. Any VT results with less than 5 detection need to be taken carefully.

**Comment by Radplay** [comment]
There have been a few reports of users getting random videos in their watched history after using ReVanced from that website.

Example 1: https://www.reddit.com/r/revancedapp/comments/11q6das/_/

Example 2: https://www.reddit.com/r/revancedapp/comments/10vp2hn/_/

**Comment by Radplay** [comment]
> `revanced.io` is not a phishing but a fun site of Revanced (similar to `ublockorigin.com`) distributing unofficial apk as described in `https://revanced.io/about/`. So far no clear sign of malicious activity has been reported. Please do not rely too much on VT community feedback, particularly if its by only one commenter. Any VT results with less than 5 detection need to be taken carefully.

2 weeks passed and things have changed a bit. As of right now, 5 security vendors flag the website as phishing, 2 as malicious and 1 as suspicious ([VT Link](https://www.virustotal.com/gui/url/be0c9fe136dc5818a82880ead977e8adca954045557b33a78259ebd10890935e))

On top of that, there were a couple of reports of users getting suspicious e-mails after installing apks from that website. [Example 1](https://www.reddit.com/r/revancedapp/comments/12pxzu4/found_out_i_downloaded_from_revancedio/), [example 2](https://www.reddit.com/r/revancedapp/comments/12ps8ez/my_gmail_contacts_received_a_fishing_email_with/). There were also reports of people getting videos they didn't watch in their watch history. [Example 1](https://www.reddit.com/r/revancedapp/comments/11q6das/videos_popping_up_in_history_that_i_didnt_watch/), [example 2](https://www.reddit.com/r/revancedapp/comments/10vp2hn/ive_been_using_the_revanced_app_since_saturday/)

**Comment by Yuki2718** [comment]
Oh, okay. But apparently the site ran away? I get NXDOMAIN.

**Comment by stephenhawk8054** [comment]
I cannot access the site currently too, but waiting for external reports/sources is often needed for this list.

**Comment by Radplay** [comment]
> Oh, okay probably I was wrong. But apparently the site ran away? I get NXDOMAIN.

I reported the website to Google Safe Browsing and Microsoft SmartScreen yesterday, maybe that has something to do with it. If it pops up again, I'll make a PR here

**Comment by bookarticle** [comment]
`https://revanced.net/`
`https://revanced.org/`
`https://revanced.pro/`

**Pull request merged**
