### PR TITLE
[gh-pages] fix: typo error in html

### PR DESCRIPTION
**Pull request by seia-soto**
Is this mistake or intended?

### CODE REVIEW

**Comment by seia-soto** [comment]
image

**Comment by DandelionSprout** [comment]
Judging by https://github.com/uBlockOrigin/uAssets/tree/gh-pages, it looks to me like a mistake that should indeed be fixed.

**Comment by stephenhawk8054** [comment]
@gorhill Can you check it? It does look like a typo, or was it intentional?

**Comment by gorhill** [comment]
Thanks.

**Pull request merged**
