### PR TITLE
update cloudvideo.tv

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`https://cloudvideo.tv/zd271pwa1d2v`

### Describe the issue

video unable to play

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox android 91.4
- uBlock Origin version: 1.37.2

### Settings

- uBO's default settings

### CODE REVIEW

**Comment by uBlock-user** [comment]
> video unable to play

video plays fine for me, though there's a delay.

**Comment by lain566** [comment]
> video unable to play

Fixed.
https://github.com/uBlockOrigin/uAssets/commit/bc2dcab4ce287da6d1551bf665facf93cefe8151

**Comment by ghajini** [comment]
> ### URL(s) where the issue occurs
> 
> `https://cloudvideo.tv/zd271pwa1d2v`
> ### Describe the issue
> 
> video unable to play
> ### Screenshot(s)
> 
> [Screenshot(s) for difficult to describe visual issues are **mandatory**]
> ### Versions
> 
>     * Browser/version: firefox android 91.4
> 
>     * uBlock Origin version: 1.37.2
> 
> 
> ### Settings
> 
>     * uBO's default settings
> 
> 
> ### Notes



> > video unable to play
> 
> video plays fine for me, though there's a delay.



> > video unable to play
> 
> video plays fine for me, though there's a delay.

I also said Firefox android

@lain566 can you add
 `cloudvideo.tv##^script:has-text(break;case $.)`

**Comment by lain566** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ea4baf17b6bedee0ab2b001b4c66aef0ca69c338

**Pull request closed without merging**
