### PR TITLE
ez4short, Shrinkme,gplinks,terabox up

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://ez4short.com/smNkJiu?src=PSA`
`https://shrinkme.info/Ba6VI` > Random
`http://gplinks.co/rJgS`
`terabox.fun/sl/2omxpMMJdo`

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
Ok i tested the filter and i have a few issues:
 
1. On `https://ez4short.com/smNkJiu?src=PSA` i get a empty page after it redirected me to `ez4mods.com`. Also the button on `tech5s.co` is unclickable when the user didn’t accepted the cookie banner. The cookie banner is hidden with your filter.
2. `https://shrinkme.info/Ba6VI` redirect me to `themezon.net` and the button is unclickable. Same issue as above.
3. Im a bit worried about

```
terabox.fun,hotmediahub.com##+js(trusted-click-element, .active.btn)
terabox.fun,hotmediahub.com##+js(trusted-click-element, .active.btn, , 200)
```
Because shady sites can abuse this to open unwanted links. Also the selector is very generic and can hit wrong elements.

**Comment by BlazeFTL** [comment]
@JobcenterTycoon I Cross Checked In Chrome+New FF Everything Seems Fine On My End...Maybe A 3rd Person Have To Confirm

For No 3. I Am Pretty Sure That Can Be Said About Any Shady Shortner Sites(No Need To Worry) I Would Watch Over It

**Comment by JobcenterTycoon** [comment]
Blocking the cookie banner script with `||cmp.quantcast.com^$domain=tech5s.co|themezon.net` works for me.

**Comment by BlazeFTL** [comment]
Wait A Sec `tech5s.co` Shouldn't Exist In `te-it.com,world2our.com,mobi2c.com,tech5s.co,ez4mods.com,sinonimos.de,bluetechno.net,forexit.online###submitBtn, #go_d, #devozon-snp, #submitBtn, #tp-snp1, #go_d2:others()`

Was Removed In Previous PR...Pls Check Again

**Comment by JobcenterTycoon** [comment]
All fine but the buttons still not working for me. `||cmp.quantcast.com^$domain=tech5s.co|themezon.net` is needed on my end (only when cookies are not accepted already).

**Comment by BlazeFTL** [comment]
Done Bro

**Pull request merged**
