### PR TITLE
flickr.com

### PR DESCRIPTION
**Pull request by anewuser**
### URL(s) where the issue occurs

`https://www.flickr.com/photos/davef64/5411151024/sizes/l`

### Describe the issue

Element used to prevent right-clicks on images.

### CODE REVIEW

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/40cdcc153cc1c82f7eb358c9fa7fba0a2303b508

**Comment by anewuser** [comment]
@mapx- did you change anything or you just like to take credit for everything?

**Comment by mapx-** [comment]
Well .. at the moment of committing I was notified of some conflicts. I prefer  a clean approach in such cases.
You have now your explanation. I hope in the future you'll refrain from such comments (and use team discussions when you have doubts).

**Comment by anewuser** [comment]
I'm not in any team, and what happened should be transparent to other potential contributors browsing the repository too, since it's easier to just file issues instead of preparing pull requests in vain.

**Pull request closed without merging**
