### PR TITLE
2 more badware urls

### PR DESCRIPTION
**Pull request by koxx12-dev**
`shadyclient.net` and `mcdupe.com`
are distributing Minecraft Session token stealers
Related to #10163 and #10142 (same person)

#### mcdupe.com 
java_yD0WpLrRwB
Classes are named Class`some number here` because i used a Auto Rename plugin that makes code more readable
Used forge 1.8.9 mappings to make code more readable
#### shadyclient.net
java_absoJXdooI
Used forge 1.8.9 mappings to make code more readable

### CODE REVIEW

**Comment by mapx-** [comment]
`$dox` ?

**Comment by koxx12-dev** [comment]
> $dox

these are random class names so it kinda doesnt matter

**Comment by iam-py-test** [comment]
If they are malware, $all is better

**Comment by iam-py-test** [comment]
One question: How did you 'look inside' the malware?

**Comment by koxx12-dev** [comment]
> $dox

these are random class names so it kinda doesnt matter

> One question: How did you 'look inside' the malware? Edit: Are any of these the samples you downloaded: https://www.virustotal.com/gui/file/04ddf6a1d57d01759e106d0d30ade500e891ac37b1c72ed08497c2699803dd03/relations https://www.virustotal.com/gui/file/24ceb0decf80a99941ac789cbbe1318042de67a2ba9925c6aaf2adf267be6c4e/relations https://www.virustotal.com/gui/file/05a8d2290cfd5e949a18221e83859004e3f03ce762023573e301c089ceb1c767?nocache=1 https://hybrid-analysis.com/sample/05a8d2290cfd5e949a18221e83859004e3f03ce762023573e301c089ceb1c767 https://hybrid-analysis.com/sample/24ceb0decf80a99941ac789cbbe1318042de67a2ba9925c6aaf2adf267be6c4e

i decompiled them using recaf
https://github.com/Col-E/Recaf

and yes i download them from respective sites

**Comment by koxx12-dev** [comment]
> `$dox` ?

i just realized what you meant and i just made small mistake when i typing

**Comment by iam-py-test** [comment]
Submitted file: https://bazaar.abuse.ch/sample/05a8d2290cfd5e949a18221e83859004e3f03ce762023573e301c089ceb1c767/

**Pull request merged**
