### PR TITLE
address streamsb ads

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

NSFW
```
https://streamsb.co/d/3ijvtf3wocc3.html
https://streamsb.co/e/3ijvtf3wocc3.html
```

### Describe the issue

popup ads

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox
- uBlock Origin version: 1.42.4

### Settings

-  uBO's default settings

### CODE REVIEW

**Comment by ghajini** [comment]
@mapx- 
can you group streamsb and related filters into one place(right now they are here and there)
& remove unnecessary

**Comment by mapx-** [comment]
what other filters could be placed together ?

**Comment by ghajini** [comment]
i will check,revert back

**Comment by ghajini** [comment]
these are streamsb mirrors i found

```
https://sbplay.org/play/j4y747gqw8u2
https://sbplay2.xyz/d/nh509j06by0c
https://sbplay3.xyz/e/nh509j06by0c

https://sbembed.com/embed-2hn7wzlg34v2.html
https://sbembed1.com/d/2hn7wzlg34v2.html
https://sbembed2.com/d/2hn7wzlg34v2.html
https://sbembed3.com/d/2hn7wzlg34v2.html
https://sbembed4.com/d/2hn7wzlg34v2.html

https://streamsb.co/d/3ijvtf3wocc3.html
https://playersb.com/d/xfxgo18uqg5b?auto=0&referer=&#
https://cloudemb.com/4otil2fa3kpv.html
https://playersb.com/d/xfxgo18uqg5b?auto=0&referer=&#
https://sbvideo.net/embed-2hn7wzlg34v2.html
https://dlmovies.link/d/2yqidvlp3vc5.html
https://sbchip.bar/d/7yvs3qh5mvs0.html
https://sbcloud1.com/d/29rpfq30ey3k.html
https://sbfast.com/d/nmjf0t5fckc8
https://sbflix.xyz/d/yylc7eyyq02w.html
https://tubesb.com/d/w2hu3xhlbzhz.html
https://watchsb.com/d/vi79uyhvs84q.html
https://viewsb.com/d/yd6adun2dmk8.html
pelistop.co
https://embedsb.com/oik7yy8hph86.html
https://oxl.one/e/vgb1gn15ihdp.html
```
i think their filters should be in one place

**Comment by ghajini** [comment]
these filters not req(though ,through checking is required on your side)

```
sbplay.*##+js(nowoif, !/sbplay|^\/d\//)
sbembed1.com,sbplay.*##+js(aopr, DoodPop)
sbvideo.*##+js(nowoif, !/d/)
```

**Comment by ghajini** [comment]
changes 
delete sbembed.com##+js(aopr, DoodPop)
 
& 
add 
```
sbembed.com##+js(aopr, mm)
sbembed.com##+js(aopr, __Y)
```
also merge `(aopr, __Y & aopr, mm)` related to this issue only

**Comment by ghajini** [comment]
thanks this looks much clean now

**Pull request merged**
