### PR TITLE
blocks ads on `https://freebitcoin.vip/claim/`

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by IThinkIAmCool** [comment]
@ryanbr

**Comment by IThinkIAmCool** [comment]
@Yuki2718 Mentioning you because idk if it's fixed in AdGuard Base.

**Comment by Yuki2718** [comment]
>  Mentioning you because idk if it's fixed in AdGuard Base.

I don't see the request by visiting the site?

**Comment by IThinkIAmCool** [comment]
@Yuki2718 It used to work. I got an ad on `https://freebitcoin.vip/` (Firefox / AdGuard Browser Extension)

**Pull request merged**
