### PR TITLE
updated badware.txt

### PR DESCRIPTION
**Pull request by NeikiDev**
added malware urls (part of redline malware)
from collection: https://www.virustotal.com/gui/collection/e8b07232ca57df01f81a2b5d485ad0016ffaff9bf834aaf7d1a565f93b616e0a

### CODE REVIEW

**Comment by mapx-** [comment]
I see 0 detections on virus total. Some other info ?

**Comment by NeikiDev** [comment]
hey yeah ofc!

here is a triage report and if you look at the network it says it connects to the api domain
https://tria.ge/230404-p5btxsgh31/behavioral3

image
image

its an common discord token stealer (labled as readline here)

**Comment by mapx-** [comment]
`||deltaproject.dev^$all`  will block the `api` subdomain too, you can remove it

**Comment by NeikiDev** [comment]
i removed the api subdomain thanks! hope now is all fine

**Pull request merged**
