### PR TITLE
Fix DG Whitelist

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://dropgalaxy.vip/l8aame0v92ng`

Basic Whitelist Found In DG Source
These Are Necessary On My Side..Ref - https://github.com/uBlockOrigin/uAssets/issues/19165#issuecomment-1704355990

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
These filter are not acceptable.

1. No cosmetic filtering for the ads
2. The "Buy premium" button is self advertisment -> Not a case for uBlock Origin
3. Blocked pings and frames are not always detectable

This works for me:
```
@@||googlesyndication.com^$script,xhr,frame,domain=dropgalaxy.com
@@||adoto.net^$script,xhr,domain=dropgalaxy.com
@@||rsc.cdn77.org^$script,xhr,domain=dropgalaxy.com
@@||doubleclick.net^$script,xhr,domain=dropgalaxy.com
@@||challenges.cloudflare.com^$subdocument,domain=dropgalaxy.com
@@||a2zapk.com^$script,xhr,3p,domain=dropgalaxy.com
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=dropgalaxy.com
@@||blockadsnot.com^$script,domain=dropgalaxy.com
@@||login.popmonetizer.com^$script,domain=dropgalaxy.com
dropgalaxy.com##html.i-amphtml-inabox
dropgalaxy.com##div[id^="TR-"]:remove()
dropgalaxy.com##+js(acis, document.createElement, /break;case \$\.|popunder/)
```

**Comment by BlazeFTL** [comment]
I Understand But Oviously DGOwner Will Update According To Our Rules..
The Idea Was To Not Give Any LoopHoles
He Has Added Tons Of iframe Detection Targeting Exact Cosmetic Element Would Be Useless
You Can Delete The Premium Button Filter But Dont Add
```
dropgalaxy.com##html.i-amphtml-inabox
dropgalaxy.com##div[id^="TR-"]:remove()

**Comment by BlazeFTL** [comment]
You Should Allow - frame For
```
@@||googlesyndication.com^$script,xhr,frame,domain=dropgalaxy.com
@@||adoto.net^$script,xhr,frame,domain=dropgalaxy.com
@@||doubleclick.net^$script,xhr,frame,domain=dropgalaxy.com

**Comment by BlazeFTL** [comment]
My Mistake Bro..Go Ahead

**Comment by BlazeFTL** [comment]
Just Allow script,xhr For Adoto Then

**Pull request closed without merging**
