### PR TITLE
Fix n.fcd.su

### PR DESCRIPTION
**Pull request by iSmokeMid69**
### URL(s) where the issue occurs
`https://n.fcd.su/MJn/ygra`

### Describe the issue
Fixes Disabled Button & Popup

### CODE REVIEW

**Comment by krystian3w** [comment]
IMO malware: https://virustotal.com/gui/file/7ec2584f977a1e08a56c00b8b965260ffef7128539f79ad9e2b9e217b7a14e39?nocache=1

```adb
||pufgilsofp.sbs^$all,important # God safe King!
```

```
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMqgMO
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AM93yj7
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMi5Z8Yp
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AM27r9vAM
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMcbFGix2k
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMndWHM0NgT
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMagcc4B2ii7
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMxwBMY5z85xm
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMyOVv4ghciRxL
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMc8o68bbnlcr41
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMvIaFVcrIyzzfnt
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMP4xvN6eOJ0fozHa
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMhZdS9oEcI2AWysIo
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMXAktvCI1A3gGIe1NN
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMEzrvvrrGbJOQUIMWlO
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AMMw02jWnfBSG0fKoSJlZ
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AM3PbLUBLPYuXssHRObIsX
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/853fe65a5092553b0282a3cb9b17c91eM6ETNZuAkqGsLLWuq8sgKF/SF/WMzDua8nIlTIrnLve16AM
pufgilsofp.sbs
hXXps[:]//pufgilsofp.sbs/de3813d6c4445872caceca26d79591b7FqZFwchQiyc8ZD/zbD8VyxWWPFq38jFPe7t
```

**Comment by stephenhawk8054** [comment]
You mean the popup that opens `pufgilsofp.sbs` link?

**Comment by krystian3w** [comment]
I mean on PC pages serve diffrent "html":

image | image
--- | ---
PC - malware | mobile - link to TikTok apk in zip?

**Comment by stephenhawk8054** [comment]
Ok, I understand now

**Comment by krystian3w** [comment]
@stephenhawk8054 I think `pufgilsofp.sbs` will be not longer active, based on #17400 new tmp page with PC malware is:

```python
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgv
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgZQ
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgpSa
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgEPOA
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgcnDFE
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgUPpILT
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgtavuDOe
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgkbtWrULI
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgduk94krK2
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAg2WMqwi40qV
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAg4C6dZkbYtks
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgjbkJSzfT0ngS
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgfYOztHjfrdHg0
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgwwinv01SRHk7kD
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgmHw593VD7NfmdEg
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgUdnVPvA5NmP4WDqI
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAg4O5ANhfDnyLt40KU7
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgygWXV5vH8BYjtpsWDY
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAg1O0RPzK6rwfgiCI1ZhQ
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAgUhb412xHAxyvFWbQ5a7N
hXXps://xfiley[.]me/22025f6532e84af2ec28b6626fe1d3d15-ia5DerbaYm0QEIhfkees686RwsYpEixV1CMzSoW1F4FAg
hXXps://xfiley[.]me/e8166de883d13df853226a74d82f23a9fw108MN-DoxNTU96atxT9-WdqkRF7QKuK/f2QN7XR2HWvw
(both blocked by Eset) --> ﻿hXXps[:]//mpraven[.]org / hXXps[:]//dwnfile[.]fun

```

**Pull request closed without merging**
