### PR TITLE
Update annoyances-others.txt

### PR DESCRIPTION
**Pull request by ButterVsMargarine**
`https://kipflix.vercel.app/`

anti dev tools

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
There is already `||cdn.jsdelivr.net/npm/disable-devtool$script,domain=idlixofficials.com|idlixplus.com|idlixplus.net|embed.meomeo.pw|vumoo.to|mhdtvsports.me` the site should be added here.

**Comment by ButterVsMargarine** [comment]
I thought this rule could be added generically

**Comment by JobcenterTycoon** [comment]
I thought this too but i heard it can break pages.

**Comment by D4niloMR** [comment]
@JobcenterTycoon we can add exception for these. Personally I've never seen such case.

Some already included in `EasyList – Other Annoyances`:

https://github.com/easylist/easylist/blob/b30fe522d937addb9c6e9ff4c215b8896a208769/fanboy-addon/fanboy_annoyance_general_block.txt#L38-L61

https://github.com/easylist/easylist/blob/b30fe522d937addb9c6e9ff4c215b8896a208769/fanboy-addon/fanboy_annoyance_thirdparty.txt#L137-L138

**Pull request merged**
