### PR TITLE
Add missing pubads methods

### PR DESCRIPTION
**Pull request by gazs**
This pull request adds methods listed in the [GPT documentation](https://developers.google.com/doubleclick-gpt/reference#googletagpubadsservice) but missing from the mocked pubads object:
- getTargeting
- getTargetingKeys
- setForceSafeFrame
- setSafeFrameConfig

### CODE REVIEW

**Comment by gorhill** [comment]
You have one or more actual cases where these missing methods cause an issue?

**Comment by gazs** [comment]
Ah, sorry, `http://www.vogue.de/mode` will be triggered on browser window resize

**Comment by gorhill** [comment]
> http://www.vogue.de/mode will be triggered

Thanks.

However, you will first need to change `setForceSafeFrame` and `setSafeFrameConfig` to return `noopthisfn`, as per reference documentation.

**Comment by gorhill** [comment]
Thanks.

**Pull request merged**
