### PR TITLE
fix #14470 albumoftheyear.org

### LINKED ISSUE #14470: albumoftheyear.org: ads
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.albumoftheyear.org/discover/`

### Category

ads

### Describe the issue

ad container at bottom of page (also appears in the middle of the page on some urls):

`albumoftheyear.org##div:has(> .adHeading)`

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

image

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 84570
  cosmetic: 82368
  scriptlet: 19331
  html: 729
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1941-0, 4h.38m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt: 15-0, 4h.38m
    fanboy-cookiemonster: 40297-86, 12h.13m
  default: 
    user-filters: 112-0, never
    ublock-filters: 33232-77, 12h.14m
    ublock-badware: 4263-0, 12h.14m
    ublock-privacy: 247-2, 12h.14m
    ublock-abuse: 76-0, 12h.14m
    ublock-unbreak: 1845-0, 12h.14m
    ublock-quick-fixes: 425-0, 12h.14m
    easylist: 69600-610, 12h.14m
    easyprivacy: 27394-578, 12h.14m
    urlhaus-1: 5443-0, 12h.14m
    plowe-0: 3633-3, 12h.14m
filterset (user): [array of 111 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 331 ms
  maxAssetCacheWait: 268 ms
popupPanel: 
  blocked: 7
  blockedDetails: 
    btloader.com: 2
    cloudflareinsights.com: 2
    consensu.org: 1
    googletagmanager.com: 1
    intergient.com: 1
```
</details>

### PR DESCRIPTION
**Pull request by wavygecko**
Fix #14470

@ryanbr didn't want to add to EasyList https://github.com/easylist/easylist/issues/13105#issuecomment-1229153286

### CODE REVIEW

**Comment by Yuki2718** [comment]
We generally follow EL's criteria, tho there are exception. In any case `##div:has(> .adHeading)` is not acceptable, see https://github.com/easylist/easylist/pull/13083. `##div[style="padding: 30px 0 60px 0; text-align: center;"]` is acceptable but IDK if other members want to add - the aim of this project is not on removing every single tiny placeholder.

**Comment by MasterKia** [comment]
@wavygecko You can make a "Ads placeholder hider" filter list similar to this one (although this list isn't maintained anymore):
https://raw.githubusercontent.com/Yuki2718/adblock/master/no_gen_cosm/phhider.txt

You can even publish it on filterlists.com

**Comment by Yuki2718** [comment]
[Off topic] Although I'm planning to unmaintain, Placeholder Hider with no generic hiding is still maintained (last updated yesterday).

**Comment by wavygecko** [comment]
Ohh okay.

> We generally follow EL's criteria, tho there are exception. In any case ##div:has(> .adHeading) is not acceptable

> #?#div:-abp-has => procedural filter js code evaluates all the div on the page, if the numbers are big it has the same issue as you pointed out.

Why doesn't the evaluation look for what's inside `:has()` and then check upwards (i.e., working right to left, like in CSS)? Seems like that would be better performance.

**Comment by Yuki2718** [comment]
> Why doesn't the evaluation look for what's inside `:has()` and then check upwards (i.e., working right to

In the current implementation if there's no first match (next to the leftmost procedural operator), procedural code is not even ivoked because no need. Evalutating arguments first will be waste if the target of argument (`.adHeading`) exists but no need for the procedural filter.

**Comment by Yuki2718** [comment]
@peace2000 While I do the same on my personal list, let's see AG issues - some people reports/-ed every single small PH they found.

**Pull request closed without merging**
