### PR TITLE
update filters 2021

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

```
https://hindilinks4u.pro/boogie-2021-Watch-online/
https://gofilms4u.pro/becoming-2020-hindi-dubbed-full-movie-online-on-gofilms4u
https://movies.jaanihd.ml/2021/02/world-famous-lover-2020-hindi-dubbed.html
```
### Describe the issue

popup ads
fake download/stream butons

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: opera browser stable/firefox
- uBlock Origin version: 1.34.1b2 / 1.34

### Settings

- uBO's default settings

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

### CODE REVIEW

**Comment by ghajini** [comment]
sorry only these rules to be added to existing filters
```
hindilinks4u.pro,gofilms4u.pro,jaanihd.ml,filmlinks4u.pro##+js(acis, Math, break;case $.)
movies.jaanihd.ml##.blue.dbuttn
hindilinks4u.pro,gofilms4u.pro,filmlinks4u.pro##.mvic-btn
||syjuyyfi.xyz^
```

**Comment by mapx-** [comment]
@ghajini could you provide a clean PR ?

**Comment by Yuki2718** [comment]
@ghajini I usually use web console - manually edit the parts causing conflicts.

**Comment by uBlock-user** [comment]
sync with the list and opening a new PR

**Pull request closed without merging**
