### PR TITLE
link.ltcs24.com + ltc24.com fixes

### PR DESCRIPTION
**Pull request by Alex4567890**
Issue(s) discovered via https://github.com/AdguardTeam/AdguardFilters/issues/76681

### CODE REVIEW

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/da318f64bc522f4cb38caefcd06997d52bd55fc5

**Comment by wout-codes** [comment]
> Issue(s) discovered via [AdguardTeam/AdguardFilters#76681](https://github.com/AdguardTeam/AdguardFilters/issues/76681)

@Alex4567890 Inspect the scripts thoroughly and properly.

**Comment by Alex4567890** [comment]
> > Issue(s) discovered via [AdguardTeam/AdguardFilters#76681](https://github.com/AdguardTeam/AdguardFilters/issues/76681)
> 
> @Alex4567890 Inspect the scripts thoroughly and properly. Because you added an unnecessary rule and forgot to add a very important rule.

ltc24.com##+js(nobab) is actually needed for ad block detection on https://ltc24.com

**Comment by wout-codes** [comment]
I think that's important. @mapx- check.

**Comment by Alex4567890** [comment]
And what does `link.ltc24.com##+js(acis, String.fromCharCode, break)` do/fix?

**Comment by wout-codes** [comment]
Kills popups and it depends. You can't just put it everywhere.

**Comment by Alex4567890** [comment]
Alright, thanks!

**Comment by Yuki2718** [comment]
For bab we prefer ghide unless it unhides other social or annoyance elements.

**Pull request closed without merging**
