### PR TITLE
Fix https://github.com/easylist/easylistchina/issues/114

### PR DESCRIPTION
**Pull request by shenzhiming88**
https://github.com/easylist/easylistchina/issues/114
Domains used for tracking.

### CODE REVIEW

**Comment by krystian3w** [comment]
Too simple filter, try in EasyPrivacy and if no fixed after 2 months back here.

**Comment by shenzhiming88** [comment]
> Too simple filter, try in EasyPrivacy and if no fixed after 2 months back here.

Fine. Thank you for your advice.
https://github.com/easylist/easylist/pull/10280

**Comment by shenzhiming88** [comment]
@mapx- Also will the default list handle content farms? Thanks.

**Comment by krystian3w** [comment]
porn farms not.

**Comment by shenzhiming88** [comment]
> porn farms not: #10072 (or gargul issue about porn farms and ads on these pages)

Thank you for your answer. I meant would it just block the domain name of the content farm instead of dealing with the ads on it. These pages are really particularly annoying.

**Comment by krystian3w** [comment]
IMO the best omit on google search instead generate strict block blockade prompt.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/80ffe32b7dc2390313e37f6cc12246588fe0b74b

**Comment by shenzhiming88** [comment]
> [easylist/easylist@80ffe32](https://github.com/easylist/easylist/commit/80ffe32b7dc2390313e37f6cc12246588fe0b74b)

Oh yes, I submit this PR, which has been merged now.

**Pull request closed without merging**
