### PR TITLE
fix https://github.com/AdguardTeam/AdguardFilters/issues/78227

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by IThinkIAmCool** [comment]
and for other domains / websites

**Comment by mapx-** [comment]
add test cases for all those domains

**Comment by IThinkIAmCool** [comment]
I visited a link from link1s.com multiple times and got redirected to these domains/websites.

**Comment by mapx-** [comment]
Great. Still needing the test case(s) and eventually steps to reproduce the issue.

**Comment by IThinkIAmCool** [comment]
Could I provide a recording?

**Comment by mapx-** [comment]
No. Real test cases.

**Comment by IThinkIAmCool** [comment]
But at the same time I'd like to not potentially dox myself to hwoever may have access to my IP if I give a link. (a 'shortened one')

**Comment by IThinkIAmCool** [comment]
Alright. So you visit a 'shortened' link from link1s.com multiple times.

**Comment by IThinkIAmCool** [comment]
And, in my case, I was redirected to multiple urls.

**Comment by IThinkIAmCool** [comment]
Did you reproduce the issue?

**Comment by IThinkIAmCool** [comment]
Alright. http://link1s.com/VuYpRL is a link created with link1s.com. It should ultimately redirect to google as of now.
Could you open http://link1s.com/VuYpRL multiple times and see if uBlock Origin with the default filter lists and settings gets detected and whatever you may be redirected to?

**Comment by IThinkIAmCool** [comment]
But actually using '##+js(nosiif, visibility, 1000)' seems to not be working on https://alobyt.com/san-francisco-public-health-director-announces-tighter-guidelines-for-coronavirus-care/.

**Comment by IThinkIAmCool** [comment]
`aloguy.com,alohdd.com,alogum.com,alobyt.com##+js(nobab)` worked on my end.

**Comment by IThinkIAmCool** [comment]
Nevermind.
Someone fixed the issue(s): https://github.com/uBlockOrigin/uAssets/commit/fc47047f5162776e4989037693b8697e2a1808f3

**Pull request closed without merging**
