### PR TITLE
Update tuhentaionline.com and fix hentaisea.com popunder [NSFW]

### PR DESCRIPTION
**Pull request by Yuki2718**
Player overlay
`https://www.tuhentaionline.com/ver/ore-no-yubi-de-midarero-heitengo-futarikiri-no-salon-de-8`

<details>

tuhentaionline

</details>

Popunder on clicking Episodes
`https://hentaisea.com/watch/tsuma-shibori/`

<details>

hentaisea

</details>

### CODE REVIEW

**Comment by okiehsch** [comment]
Thx.

**Comment by lain566** [comment]
@okiehsch Those rules for `tuhentaionline.com` are already in the regional filter list.

<details>

Captura de pantalla 2020-10-24 070714
</details>

**Comment by okiehsch** [comment]
Thanks, I removed them.

**Comment by Yuki2718** [comment]
Hm.., I failed to understand it's Spanish site. They're in AG Spanish, but EL Spanish only has `/publi/publi` and no cosmetic so overlay appears. IDK why both lists are kept, they're 'choose one' than 'use both', not?

**Pull request merged**
