### PR TITLE
tgx up

### PR DESCRIPTION
**Pull request by BlazeFTL**

### CODE REVIEW

**Comment by ItsProfessional** [comment]
Why did you move it to the top?

> New filter must be added at the end of the list.
The reason is to provide an easy way to check whether a filter is still relevant. The filters at the top of the file will be the oldest filters, and also the most likely to maybe be obsolete.
Old filters which are confirmed to still be required must be moved to the **end** of the list.

**Comment by BlazeFTL** [comment]
@ItsProfessional It Isnt Any Issue...I Have Been Here Longer Than You So I Know What I Am Doing

**Comment by BlazeFTL** [comment]
@huyszn `[href^="/hus.php"]`

**Comment by BlazeFTL** [comment]
@daxy7 Tell Me Why You Laughing?
What Would Happen So Catastrophic If Those Few Lines Go At Top ?

**Comment by ItsProfessional** [comment]
It's a policy that's been here forever, so it's better if its consistently followed.
I don't see any valid reason for them to be moved to the top.

**Pull request closed without merging**
