### PR TITLE
fix

### PR DESCRIPTION
**Pull request by badutcoder**
### URL(s) where the issue occurs

`https://adikhealth.xyz/p/?id=eVlWWEVwbFZFUU11Q0s2YzVRMUF1ZkVmaGV2dDFIY3dWQkNmYXh2Q1drdzB2SU9JNHJucVNFL2ZrSkVZRjl5cHhhbExTUFJDV0hNVjNXMElnUC9iM0tkNXNlMEFjclhHQVFxZE1hbDI2bHBZQmxCVFBWZHJsc1BSSlVoRHVNVTF5WFNTU2FHZSt3cmhNdk0vbE42Rm53PT0=`

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
I still get anti adblock with this fix.

**Comment by badutcoder** [comment]
try this, works for me

```
adikhealth.xyz,bisnis.adigenius.com,mangindo.xyz##+js(rpnt, script, /;window\['localStora.*?;/, ;)
```

**Comment by JobcenterTycoon** [comment]
I still get anti adblock after i clicked the 3 buttons (tested with Firefox)

**Comment by stephenhawk8054** [comment]
Does the console show anything if you use `log`?

```adb
adikhealth.xyz,bisnis.adigenius.com,mangindo.xyz##+js(rpnt, script, /;window\['localStora.*?;/, ;, log, 1)
```

**Comment by JobcenterTycoon** [comment]
It works when i add

```
adikhealth.xyz,bisnis.adigenius.com,mangindo.xyz##+js(rpnt, script, /;window\['localStora.*?;/, ;, log, 1)
adikhealth.xyz,bisnis.adigenius.com,mangindo.xyz,adikdrive.my.id#@#+js(nano-sib, , *)
adikhealth.xyz,bisnis.adigenius.com,mangindo.xyz,adikdrive.my.id#@#+js(nano-stb, , *)
```

> Does the console show anything if you use log?

Yes

**Comment by stephenhawk8054** [comment]
@JobcenterTycoon Does it work on your side now?

**Comment by badutcoder** [comment]
he changed the code again, here the snippet code:

```javascript
  adikBtnEnd.addEventListener('click', () => {
    function _0x1eb18b() {
      return new Date().getTime()
    }
    if (_0x1eb18b() < _0xf01429cs + 18000) {
      document
        .querySelector('#fmbodfmbd')
        .setAttribute('style', 'display:block'),
        (document.querySelector('#content').innerHTML = '')
    } else {
      if (_0xf01429cs < 168931640 || _0xf01429cs == 0) {
        document
          .querySelector('#fmbodfmbd')
          .setAttribute('style', 'display:block')
        document.querySelector('#content').innerHTML = ''
      } else {
        window.open('https://mangindo.xyz/?hash=' + adikHash, '_blank'),
          localStorage.removeItem('adik-hash')
      }
    }
  })
```

i will remove skip countdown to fix this filter.

**Comment by stephenhawk8054** [comment]
Do the sites update often? If so, I think you can move the filters to quick fix list.

**Comment by badutcoder** [comment]
ok

**Comment by Yuki2718** [comment]
Why added only to quick? Any fix on quick should be removed eventually.

**Comment by stephenhawk8054** [comment]
Updated: https://github.com/uBlockOrigin/uAssets/commit/46e8c5725eb46ea6b3226c2cbf664c4f48f19529

**Pull request merged**
