### PR TITLE
fix(7062): Unbreak viki player

### PR DESCRIPTION
**Pull request by vylmen**
### URL(s) where the issue occurs

https://www.viki.com/videos/1145603v (logged in)

### Describe the issue

Exception: pingAbFactor() is not a function

In JavaScript null is not a function, aside from that, whatever we
return must be truthy. So let's just return a function that returns
true.

Because of the thrown exception, the player plays about 1 second of
content in a continious loop, even if one has a paid account that
disabled ads.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Firefox 76.0.1 64 bit, MacOS
- uBlock Origin version: 1.27.4

### Settings

- Changed how the player interacts with adblock detector

### CODE REVIEW

**Comment by uBlock-user** [comment]
I can't reproduce that when I tested, video plays fine, how is it getting stuck exactly ? Does it happens when you're logged in only ?

**Comment by vylmen** [comment]
yes, logged in.
It gets stuck on this bit:
```js
            {
              key: 'onTimeUpdate',
              value: function () {
                if (!this.options.isLive) {
                  var e = this.player;
                  Math.ceil(e.currentTime()) >= e.duration() && e.duration() > 0 && this.emit(y.VIDEO_ENDED)
                }
                this.player.currentTime() >= this.abFactorCheckPoint && this.pingAbFactor()
              }
            },
```
Because with your commit is has been set to null, this.pingAbFactor() throws an exception. Another prerequisite may be that you have to resume a video so that it tries to forward and then hits this code. I'm not entirely sure about that, but the exception was in this bit.

**Comment by uBlock-user** [comment]
How about `viki.com##+js(set, VikiPlayer.prototype.pingAbFactor, noopFunc)` ? Test that filter.

**Comment by vylmen** [comment]
Updated

**Pull request merged**
