### PR TITLE
 Add curseforge and additional ad domains for fix of #24130 

### PR DESCRIPTION
**Pull request by raqean**
### URL(s) where the issue occurs

`https://modrinth.com/resourcepack/dramatic-skys`
`https://modrinth.com/mod/tips`
`https://modrinth.com/mod/the-filler-update`
`https://modrinth.com/modpack/quantum-freedom`
`https://www.curseforge.com/minecraft/modpacks/technical-electrical`

### Describe the issue

Block additional domains that are used by modrinth and curseforge in-content banner ads. Added curseforge as an additional domain where this format of banner ad is common, but with a different element layout.

### Screenshot(s)

Screenshot 2024-06-19 at 04 23 03
Screenshot 2024-06-19 at 04 23 11

### Versions

- Browser/version: Firefox 127
- uBlock Origin version: 1.58.0
- Basing my changes off of the latest commit related to these sites at the time.

### Settings

no changes

### Notes

none

### CODE REVIEW

**Comment by stephenhawk8054** [comment]
Can you convert to `:is()` format, so it's easier to add domains without adding more lines?

Also, can you change `href*` to `href^`? We want to minimize false positives and target correct elements on the page.

**Comment by raqean** [comment]
I used `href*` instead of `href^` because on curseforge the target domain is buried within a url-encoded redirection link. I've applied the `:is` syntax.

**Comment by stephenhawk8054** [comment]
From what I see, that site has `/linkout?remoteUrl=` at the start. Does this filter work?

```adb
curseforge.com##section.project-description [href^="/linkout?remoteUrl=http"]:is([href*="shockbyte.com"],[href*="billing.kinetichosting.net"],[href*="bisecthosting.com"],[href*="meloncube.net"],[href*="scalacube.com"],[href*="billing.ember.host"],[href*="nodecraft.com"]) > img
```

**Comment by leo60228** [comment]
It's likely desirable to also support the legacy.curseforge.com subdomain (which serves a role roughly equivalent to old.reddit.com).

**Comment by raqean** [comment]
Yes that seems to work. I'll update the PR.

**Comment by raqean** [comment]
> It's likely desirable to also support the legacy.curseforge.com subdomain (which serves a role roughly equivalent to old.reddit.com).

That's a good point, I'll update the filter.

**Comment by stephenhawk8054** [comment]
`curseforge.com##` filter will also cover all subdomains of the page as well, so you don't need to add `,legacy.curseforge.com`

**Comment by stephenhawk8054** [comment]
Thanks. Please comment when you think the PR is complete.

**Comment by raqean** [comment]
I think it's complete, I couldn't find any other sponsor domains. There might be more, but they're hard to discover automatically. People would need to report them to get added individually.

**Comment by mrshmllow** [comment]
This is extremely upsetting to see

**Comment by CDAGaming** [comment]
It is, but this'll end up just being another cat and mouse game. People already have bypasses up and running, so it'll be interesting to see how this all pans out.

It's important to remember who cast the first stone in all this.

**Pull request merged**
