### PR TITLE
Adblock nag on high.fi, download.fi, muropaketti.com

### PR DESCRIPTION
**Pull request by peace2000**
### URL(s) where the issue occurs

`https://high.fi/`
`https://www.download.fi/`
`https://muropaketti.com/`

### Describe the issue

The same as: https://github.com/uBlockOrigin/uAssets/pull/9636

### Screenshot(s)

The same as: https://github.com/uBlockOrigin/uAssets/pull/9636

### Versions

Firefox 90.0.2
Ubo 1.37.1b1

### Settings

Default

### Notes

The same as https://github.com/uBlockOrigin/uAssets/pull/9636.

Could there be some kind of universal solution to counter this on all websites? I believe this is even more widely used.

### CODE REVIEW

**Comment by okiehsch** [comment]
Sure, you can add 
`*##+js(nostif, f.parentNode.removeChild(f), 100)`
that injects that scriptlet globally, we don't add global injection filters to our lists.
Thanks for the report.

**Comment by uBlock-user** [comment]
`##[class^="div-gpt-ad"]` is getting applied even though `#@#[class^="div-gpt-ad"]` is present, something broke in uBO.

**Comment by uBlock-user** [comment]
@okiehsch can you reproduce on stable uBO ?

**Comment by peace2000** [comment]
> 
> 
> Sure, you can add
> `*##+js(nostif, f.parentNode.removeChild(f), 100)`
> that injects that scriptlet globally, we don't add global injection filters to our lists.
> Thanks for the report.

Yeah, I can do that but I was thinking everyone else who uses Ubo as well. That nag is caused by blocking `fundingchoicesmessages.google.com` so I was just wondering if there were a way to fix this universally, without using a global +js filter. Just thinking, I don't know what's possible and what's not. I tried to use resource redirectors but they didn't help...

**Comment by uBlock-user** [comment]
@peace2000 do you see anti-adblock on stable uBO ?

**Comment by okiehsch** [comment]
@uBlock-user You are right It's a uBO bug, I can't reproduce with the stable version.

**Comment by uBlock-user** [comment]
Broken by https://github.com/gorhill/uBlock/commit/c25938f5bcb519ee945c9ccab7d17474474dc825

**Comment by uBlock-user** [comment]
Should revert both commits.

**Comment by okiehsch** [comment]
@gorhill

**Comment by uBlock-user** [comment]
`#@#[class^="div-gpt-ad"]` gets applied on **1.37.1b0**, thats the last working build

**Comment by peace2000** [comment]
@uBlock-user Well in 1.37 that nag went away. So yeah seems to be a bug then.

**Comment by uBlock-user** [comment]
@peace2000 happened with https://github.com/uBlockOrigin/uAssets/pull/9637#issuecomment-886595022

**Comment by uBlock-user** [comment]
Filter count for uBlock badware list also went down from `2059` to `2019` with the latest dev build.

**Comment by gorhill** [comment]
> Broken by gorhill/uBlock@c25938f

Sorry, will fix asap

**Comment by gorhill** [comment]
Fixed in 1.37.1b2, and those suffering the regression will have to force an update of filter lists which were updated during 1.37.1b1.

**Comment by peace2000** [comment]
@gorhill Tested, seems to work properly. Thanks!

**Pull request merged**
