### PR TITLE
fix https://github.com/AdguardTeam/AdguardFilters/issues/82799

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by IThinkIAmCool** [comment]
image
@uBlock-user

**Comment by uBlock-user** [comment]
Are you on default settings ? I can't reproduce it.

**Comment by IThinkIAmCool** [comment]
image

**Comment by IThinkIAmCool** [comment]
Did you try in Google Chrome?

**Comment by IThinkIAmCool** [comment]
image

**Comment by IThinkIAmCool** [comment]
image

**Comment by uBlock-user** [comment]
Had to bypass the cache to reproduce

**Pull request closed without merging**
