### PR TITLE
Update filters-2021.txt

### PR DESCRIPTION
**Pull request by Zerebokep**
### URL(s) where the issue occurs

On every thread (login required), for example:

https://www.elitepvpers.com/forum/apex-legends/4902010-last-cheat-legit.html

### Describe the issue

This breaks multiple elements on the page, e.g. the currency icon(s) are removed. Such generic rules are crazy.

### Screenshot(s)

https://imgur.com/a/dOHoGNs

### Versions

- Browser/version: 91.0.4472.77
- uBlock Origin version: v1.36.0

### CODE REVIEW

**Comment by okiehsch** [comment]
Displays fine on my end.
I don't see how that filter can block the icon in your screenshot.
image

The icon has no target="_blank" attribute.
image

**Comment by Zerebokep** [comment]
You need to be logged in.

**Comment by okiehsch** [comment]
Oh, I overlooked your note for the need to login to reproduce.

**Comment by uBlock-user** [comment]
Tell the admin not to circumvent our filters on an ongoing basis and we wouldn't need to come with such filters in the first place.

**Comment by okiehsch** [comment]
I can reproduce but the filter you remove in your pull request is not sufficient to fix the issue.
image

**Comment by okiehsch** [comment]
@uBlock-user removing
`elitepvpers.com##div > .page > div[style*="padding"] [style*="cursor:"] > img`
does not lead to any ads on my end.

**Comment by uBlock-user** [comment]
@okiehsch His commit removes -- `elitepvpers.com##[target="_blank"] [src$=".gif"]`

**Pull request closed without merging**
