### PR TITLE
update quick

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
### URL(s) where the issue occurs

```
techpowerup. com
```

### Describe the issue

ads

### Versions

- Browser/version: firefox developer
- uBlock Origin version: 1.41.8

### Settings

uBlock Origin default + uBlock Origin annoyances

### Notes

Now very spezific

### CODE REVIEW

**Comment by okiehsch** [comment]
@JobcenterTycoon would you be interested in getting write access to uAssets?
No need for you to open pull requests, just commit yourself. 😉

**Comment by JobcenterTycoon** [comment]
sounds great

**Comment by JobcenterTycoon** [comment]
But i actualy not have the knowlege to create or modify scriptlet filters so i can’t fix such issues like popups at the moment

**Comment by okiehsch** [comment]
I sent an invitation to whatever email you used to register on github.
Only deal with issues you feel comfortable fixing, this is all voluntary.

**Comment by JobcenterTycoon** [comment]
Thanks

**Pull request merged**
