### PR TITLE
DevUploads

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://devuploads.com/icuueomz61bo`

### CODE REVIEW

**Comment by BlazeFTL** [comment]
@JobcenterTycoon Can You Check Spoof-css Makes Stuck At Checking Browser In FF Android
& Without It Site Would Need Regular Updates
```
jytechs.in,dev.miuiflash.com,djxmaza.in,thecubexguide.com##+js(spoof-css, [id*="div-gpt-ad-"]\, [id*="google_ads_"]\, #featuredimage\, [href*="random-affiliate.atimaze.com"], visibility, visible)

**Comment by BlazeFTL** [comment]
Although Your This Filter Works
```
jytechs.in,djxmaza.in,miuiflash.com,thecubexguide.com##html:not(:has(a[href^="https://devuploads.com/"]))
```
But #featuredimg, and one href ads remian

**Comment by JobcenterTycoon** [comment]
The Firefox issue is known already. Error output: `TypeError: 'get display' called on an object that does not implement interface CSS2Properties.` but gorhill also don’t know why this happens.

**Comment by Fatcavill** [comment]
@BlazeFTL bro can you fix `devuploads.com/vtxvu13fv7iy`
no one fix in shortner thread.if u can dropgalaxy also wont work pls fix

**Comment by BlazeFTL** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fb49de483fa92344d0bfb7ed1d1c349f4d949384
Test

**Comment by Fatcavill** [comment]
works
Tnx bro

**Pull request merged**
