### PR TITLE
Fix google-funding on globo.com

### PR DESCRIPTION
**Pull request by ryanbr**
### URL(s) where the issue occurs

`https://www.globo.com`  has google funding warning

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

globo

### Versions

- Browser/version: Brave
- uBlock Origin version: 1.29.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

### CODE REVIEW

**Comment by mapx-** [comment]
@ryanbr did you test chrome / FF (not only brave) ?

**Comment by mapx-** [comment]
it's brave => shields up but nothing it's blocked apparently (already happened if you remember and you reported with brave guys). If I turn off the shields no issue

image

**Comment by mapx-** [comment]
@ryanbr same behaviour for `latimes`, it's brave fault (but using us ip)

**Comment by Yuki2718** [comment]
I don't see the message neither on globo or latimes even with Brave + uBO double filtering, maybe regional matter? BTW https://github.com/uBlockOrigin/uAssets/pull/7305 was also Brave issue.

**Pull request closed without merging**
