### PR TITLE
Fix DG

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://dropgalaxy.com/drive/xx34excmo7jd`
Cant Maintain Exception Free Environment

### CODE REVIEW

**Comment by okiehsch** [comment]
Iam not against the use of exceptions, especially in cases like this but I fail to see the point of adding them if I still get detected.
That's the case here using chrome.

**Comment by okiehsch** [comment]
Many of the exceptions are for requests that are non-existing on my end, so no harm there. 😁 

````
dropgalaxy.*##+js(set, isAdblockActive, false)
dropgalaxy.*##+js(aeld, , loadScripts)
````
No, I still get detected.

> Seems To Be Region Specific.

If that is the case there is not much we or you can do about it.

**Comment by BlazeFTL** [comment]
@mapx- @JobcenterTycoon Could You Please Take A Look

**Comment by mapx-** [comment]
who wants to download:

```
@@*$script,domain=dropgalaxy.com
dropgalaxy.*##+js(nowoif, , 10)
```

**Comment by BlazeFTL** [comment]
I Missed In PR
```
dropgalaxy.*,financemonk.net##+js(nowoif)
```
If You Allow All Scripts Then This Is Required
```
||d1rp4yowwe587e.cloudfront.net^$script,domain=dropgalaxy.com,important
````

**Comment by JobcenterTycoon** [comment]
I still need `dropgalaxy.*##+js(set, window.isAdblockActive, false)` to get past the anti adblock alert but still getting detected at the end.

**Comment by BlazeFTL** [comment]
The Previous Filters Were Fine Just Needed To Remove This
```
dropgalaxy.*##+js(rpnt, script, iframe', div')
dropgalaxy.*##+js(rpnt, script, iframe", div")
dropgalaxy.*##+js(rpnt, script, iframe), div))
dropgalaxy.*##+js(rpnt, script, 'iframe, 'div)
```

But Site Owner Is Active So Thought About Exception Rules...As He Watches Our Commits & Then Makes A New Script

**Comment by mapx-** [comment]
if the cookies do not avoid downloading who cares ?

**Comment by okiehsch** [comment]
````
@@*$script,domain=dropgalaxy.com
dropgalaxy.*,financemonk.net##+js(nowoif)
||d1rp4yowwe587e.cloudfront.net^$script,domain=dropgalaxy.com,important
`````
Well, we wouldn't add that in any case.


> if the cookies do not avoid downloading who cares ?

They do, the banner is over the download button, if I remove the banner the download does not start after clicking I still get numerous popups, etc.

**Comment by okiehsch** [comment]
> The Previous Filters Were Fine Just Needed To Remove This
````
dropgalaxy.*##+js(rpnt, script, iframe', div')
dropgalaxy.*##+js(rpnt, script, iframe", div")
dropgalaxy.*##+js(rpnt, script, iframe), div))
dropgalaxy.*##+js(rpnt, script, 'iframe, 'div)
````

Well, let's do that then.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/12fcec6d6a6221243e7a78f27283891b24f161e0

Seems to work on my end.

**Comment by BlazeFTL** [comment]
> Seems to work

Wouldnt Work Tomorrow 😆

**Comment by okiehsch** [comment]
@BlazeFTL 
I know, we are thinking about maybe adding a new list dedicated to shorteners to uBO as a non default list, would you be interested in maintaining such a list.

**Comment by mapx-** [comment]
@BlazeFTL it would be easier for you committing directly how long you'd want to contribute

**Comment by JobcenterTycoon** [comment]
Wow they detect a "adblocker" sometimes even when the adblocker is off. But this is not my problem.

**Pull request merged**
