### PR TITLE
Fix: https://github.com/uBlockOrigin/uAssets/issues/20920

### PR DESCRIPTION
**Pull request by D4niloMR**

### CODE REVIEW

**Comment by D4niloMR** [comment]
Thanks

**Comment by okiehsch** [comment]
@D4niloMR would you be interested in getting commit rights to uAssets?

**Comment by D4niloMR** [comment]
@okiehsch yes.

**Comment by okiehsch** [comment]
Ok, I can only invite you if your github account has 2FA enabled, is that the case?

**Comment by D4niloMR** [comment]
I have 2FA enabled.

**Comment by okiehsch** [comment]
I will send you an invite and if you accept you will have access to [team discussions](https://help.github.com/en/articles/about-team-discussions), so if you have any questions you can ask there.

**Comment by D4niloMR** [comment]
I accepted, thank you!

**Comment by D4niloMR** [comment]
Thank you, I sended it.

**Comment by mapx-** [comment]
probably you already received the invitation

**Pull request merged**
