### PR TITLE
update mfly anti adb, fix https://github.com/AdguardTeam/AdguardFilters/issues/89566

### PR DESCRIPTION
**Pull request by thinksheiscool**

### CODE REVIEW

**Comment by Yuki2718** [comment]
badfiltered, it's simply not worth generic - the total of 4 hits in publicwww in which only 1 site actually have something to be blocked by the rule.

**Comment by uBlock-user** [comment]
Not to mention the entire PR is messed up, he brought in commits which have nothing to do with addressing anti-adb.

**Comment by thinksheiscool** [comment]
> Not to mention the entire PR is messed up, he brought in commits which have nothing to do with addressing anti-adb.

They were from a fork; I thought it would've been alright if I just fetched from this repository.

**Comment by uBlock-user** [comment]
Doesn't matter where there are from, PRs such as this won't get merged, it should only do what it says.

**Pull request closed without merging**
