### PR TITLE
Block ads on scnlog.me

### PR DESCRIPTION
**Pull request by moriakaice**
### URL(s) where the issue occurs

`https://scnlog.me/`

### Describe the issue

Ads weren't filtered on the page, resulting with new window being opened.

### Versions

- Browser/version: Chrome 88.0.4324.150
- uBlock Origin version: 1.33.2

### CODE REVIEW

**Comment by uBlock-user** [comment]
@moriakaice Does `scnlog.me##+js(acis, atob, 'shift')` work on Chrome ?

**Comment by moriakaice** [comment]
> @moriakaice Does `scnlog.me##+js(acis, atob, 'shift')` work on Chrome ?
It does, at least for me.

**Comment by moriakaice** [comment]
```
scnlog.me##+js(acis, atob, 'shift')
||gkirfipavwra.com^
```

Looks to be good enough for the page as well (the domain is yet another random characters domain used by the same ad network; that block doesn't do much for `scnlog.me` after the first line, but can save people elsewhere).

**Comment by uBlock-user** [comment]
Yes, because `scnlog.me##^script:has-text('shift')` will not work for Chromium/Chrome, so having a scriptlet would rather be preferable.

**Comment by moriakaice** [comment]
Cool, I had no idea. The original code did block it for me in Chrome, but maybe it was the 3rd party filter.

Do you want me to update the PR code?

**Comment by uBlock-user** [comment]
Yes, these filters are adequate --

```
scnlog.me##+js(acis, atob, 'shift')
*$3p,script,denyallow=google.com|gstatic.com|recaptcha.net|hcaptcha.com,domain=scnlog.me
||gkirfipavwra.com^
```

Also add the mention of the domain, like this --

`! scnlog,me popups/ads`

at the top.

**Pull request merged**
