### PR TITLE
Shareus Up

### PR DESCRIPTION
**Pull request by BlazeFTL**
https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-8501665

### CODE REVIEW

**Comment by BlazeFTL** [comment]
@D4niloMR Should This Be Added ? Your Call

**Comment by D4niloMR** [comment]
`@@||shareus.io^$ghide` works for you?

**Comment by BlazeFTL** [comment]
Yes...But Then Again The Test Cant Detect googlesyndication Not Loading...I Asked Bcz Just In Case For Future

**Comment by D4niloMR** [comment]
Then I will close this PR, `$ghide` is generic enough, in case of circumvention I doubt this script will be used

**Pull request closed without merging**
