### PR TITLE
upd game3rb. com

### PR DESCRIPTION
**Pull request by ButterVsMargarine**
`https://game3rb.com/the-complex-tragedy/`

- download ads
- vpn ad

### CODE REVIEW

**Comment by JobcenterTycoon** [comment]
These fake download buttons are known badware. Domains like `rarvinzp.click` which are pure malware/badware redirector should be hard blocked in the badware list with `$all` when they are not covered already.

**Comment by ButterVsMargarine** [comment]
maybe we could go more generic: `##a[href*=".click/?z="][href*="&n"]`

**Comment by JobcenterTycoon** [comment]
I saw this pattern already on multiply domains like `https://topkeygen.com/magix-samplitude/` -> `http://igluumars.click/?z=350&n=MAGIX%20Samplitude%20Pro%20X8%20Suite%2019.1.2.23428%20Crack%202024%20Download` 

@Yuki2718

**Comment by JobcenterTycoon** [comment]
And why is this our problem?

**Comment by ButterVsMargarine** [comment]
I'm not saying it is, but Brave uses uAssets resources

**Comment by JobcenterTycoon** [comment]
If brave doesn’t support `$all` its a brave issue not a uBlock Origin issue. `$all` is way to useful to drop it just to support a external adblocker.

**Comment by ButterVsMargarine** [comment]
@ryanbr https://github.com/uBlockOrigin/uAssets/pull/22494#issuecomment-1946844745

**Comment by stephenhawk8054** [comment]
Better to restrict to `a` in generic `[href*]`

**Comment by Yuki2718** [comment]
Brave does support `$all`.

**Pull request merged**
