### PR TITLE
Add recipe for Reddit

### PR DESCRIPTION
**Pull request by MrTimscampi**
This adds a recipe allowing Reddit (reddit.com) to work properly (Up/down votes and embedded media).

### CODE REVIEW

**Comment by zaphodbeebblebrox** [comment]
Things such as imgur images, imgur gifs, gfycat gifs, etc. are often embedded in reddit. Shouldn't they be part of the recipe as well?

**Comment by MrTimscampi** [comment]
Indeed, I hadn't looked close enough at the requirements for recipes. I'll amend this asap.

**Comment by gorhill** [comment]
> Things such as imgur images, imgur gifs, gfycat gifs, etc. are often embedded in reddit

They should be presented as separate 3rd-party recipes (ex. "Imgur as 3rd-party")

**Comment by MrTimscampi** [comment]
Ah, well, then this should be good to go, as it enables all Reddit-hosted content to work.

**Comment by gorhill** [comment]
Problem is that your ruleset recipe does not work for the strictest ruleset which must be supported: <https://github.com/gorhill/uMatrix/wiki/Ruleset-recipes#contributing-recipes>.

**Comment by MrTimscampi** [comment]
@gorhill This one should be good now.

**Pull request merged**
