### PR TITLE
https://forums.lanik.us/viewtopic.php?f=62&t=42174

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by okiehsch** [comment]
Site is down on my end.

**Comment by smed79** [comment]
https://i.imgur.com/R0tOGPv.png
https://i.imgur.com/C3gKJuU.png
https://i.imgur.com/rnRrqRG.png
https://pastebin.com/NSLJFb6C

**Comment by okiehsch** [comment]
Site is up for me now, but your fix does not work on my end, does 
````
linkspaid.com##+js(abort-on-property-read.js, app_vars.force_disable_adblock)
linkspaid.com##+js(set-constant.js, jQuery.adblock, false)
linkspaid.com##+js(setTimeout-defuser.js, anchor, 1000)
````
 work for you?

**Comment by smed79** [comment]
**Nn**, here a link for testing `https://linkspaid.com/25z`

**Comment by okiehsch** [comment]
````
linkspaid.com##+js(abort-on-property-read.js, app_vars.force_disable_adblock)
linkspaid.com##+js(set-constant.js, jQuery.adblock, false)
linkspaid.com##+js(setTimeout-defuser.js, (), 1000)
````

**Comment by smed79** [comment]
Yes, thank you.

**Comment by okiehsch** [comment]
Do you want to reopen the pull request or should I add the fix myself?

**Comment by smed79** [comment]
I will let you push the fix.
Thanks again.

**Comment by IThinkIAmCool** [comment]
Are there any obsolete filters for linkspaid.com?

**Pull request closed without merging**
