### PR TITLE
Import from Easylist Cookies

### PR DESCRIPTION
**Pull request by ryanbr**
Merging trusted-set-cookie into uBO

### CODE REVIEW

**Comment by krystian3w** [comment]
Maybe:

```adb
cineman.pl##+js(trusted-set-cookie, ARE_FUNCTIONAL_COOKIES_ACCEPTED, true, 1year)
cineman.pl##+js(trusted-set-cookie, ARE_MARKETING_COOKIES_ACCEPTED, true, 1year)
cineman.pl##+js(trusted-set-cookie, ARE_REQUIRED_COOKIES_ACCEPTED, true, 1year)
```

**Comment by ryanbr** [comment]
I don't see cineman.pl in the commit?

**Comment by krystian3w** [comment]
I meant address in this year.

**Comment by ryanbr** [comment]
Not against it, maybe any new commits be in its own PR

**Comment by krystian3w** [comment]
Well, I guess I will report them at some point and maybe someone will find set-constant.js instead of set-cookie.

**Comment by ryanbr** [comment]
If its just being set too "true", set-cookie.js (non-trusted) would be a better solution?

**Comment by stephenhawk8054** [comment]
Can you write more details about what cookies each scriptlet is targeting to and sample URLs so any others can review it more precisely later?

You can edit in either this PR's comments or the PR itself.

---

For sites with multiple TLDs, you can use `.*` for short.

**Comment by ryanbr** [comment]
Is there an easier way? I don't mind converting the domains too .* but describing each existing rules is time consuming.

**Comment by stephenhawk8054** [comment]
Ok, we will try to edit them later.

**Comment by stephenhawk8054** [comment]
@ryanbr Sorry I overlooked the filters. I think some can be handled without the need of `trusted-set-cookie`.

---

These sites just need normal scriptlets

- digitalfoundry.net
- eurogamer
- rockpapershotgun.com
- vg247.com
- vkmag.com

Basically when you open `view-source`, you can see the variable `BrockmanAllowedCookies`, in which if any sites need the cookie, you can use normal `set` for it. For example:

```adb
eurogamer.*,vg247.com##div#onetrust-consent-sdk
eurogamer.*,vg247.com##+js(set, BrockmanAllowedCookies.targeting, true)
```

since these sites just need `Targeting Cookie` to view embedded contents.

---

These sites might not need all cookies accepted? The cookies you are setting basically agrees to all cookies loaded

```adb
jku.at##+js(trusted-set-cookie, CookieConsent, required|webstatistics|marketing)
book-n-drive.de##+js(trusted-set-cookie, cookietypes, required.functional.performance)

formula1.com##+js(trusted-set-cookie, notice_preferences, 2:, 1year)
formula1.com##+js(trusted-set-cookie, notice_behavior, implied\,eu, 1year)
```

I think just a minimum amount of cookies are enough for them to function

```adb
jku.at##+js(trusted-set-cookie, CookieConsent, required, 1year)
book-n-drive.de##+js(trusted-set-cookie, cookietypes, required, 1year)

formula1.com##+js(trusted-set-cookie, notice_preferences, 1:, 1year)
formula1.com##+js(trusted-set-cookie, notice_behavior, implied\,eu, 1year)
formula1.com###cookie-banner
```

or do you have any other breakages that need extra cookies?

---

These sites might just need normal filters as I cannot reproduce any breakages:

- 1a-automarkt
- asialadies
- blaklader
- evaair.com
- howstuffworks.com
- gameinformer.com
- ofdb.de
- qastack.fr

Do you have any references for breakages on these sites?

**Comment by stephenhawk8054** [comment]
If it's too long, I will reorganize the file so you can know which sites / filters can be used in ELC without `trusted-set-cookie`.

**Comment by ryanbr** [comment]
Happy to implement non-trusted snippets where applicable

**Comment by stephenhawk8054** [comment]
These are the ones that might not need trusted scriptlets: https://github.com/uBlockOrigin/uAssets/blob/02dff0511deca725100e3ac4a97fcf05ec43121f/filters/annoyances-cookies.txt#L40-L60

Note that maybe it's because I cannot reproduce / cannot find information in the past about the breakages with these sites, so if you have any information, please tell me the broken links.

**Pull request merged**
