### PR TITLE
Add "Block access to LAN" filter list to uAssets repo

### PR DESCRIPTION
**Pull request by gwarser**
Source: https://github.com/gwarser/filter-lists

Original history was cleaned from other not related commits.

### CODE REVIEW

**Comment by Yuki2718** [comment]
> ! Expires: 30 days

😮

**Comment by gwarser** [comment]
`! Homepage:` will need to be changed too.

Can you guys try to merge this on your side and check if this work? This is merged with `--allow-unrelated-histories`, so I don't know how it will finally look. 

With final merging I will prefer for it to not be squashed, so classic merge commit (must be enabled back in repo settings) or rebase need to be used.

**Review by gorhill — APPROVED** [review]

**Comment by gorhill** [comment]
There is a "Rebase and merge" option above, is it what you want me to do?

**Comment by gwarser** [comment]
I'm not sure, I tried merging right now, but it failed.

**Comment by gwarser** [comment]
This not ended up how I imagined...

**Comment by gorhill** [comment]
Maybe create a diff patch for each commit and apply the patches in order?

**Comment by gwarser** [comment]
Ok, rebasing worked after all, but i force-pushed directly to the repo. 

@uBlockOrigin/ublock-issues-volunteers  sorry guys, please pull again if you worked on something.

**Pull request merged**
