### PR TITLE
linkshortify.in anti-adblocks and timers

### PR DESCRIPTION
**Pull request by stephenhawk8054**
### URL(s) where the issue occurs

`https://linkshortify.in/uzIOZntQ`

### Describe the issue

Anti-adblock overlays and countdown timers in next 3 domains: `studyranks.in,technoflip.in,financeflix.in`

### Screenshot(s)

<details><summary>studyranks.in</summary>

studyranks

</details>

<details><summary>technoflip.in</summary>

technoflip

</details>

<details><summary>financeflix.in</summary>

financeflix

</details>

### Versions

- Browser/version: Firefox 97.0
- uBlock Origin version: 1.40.8

### Settings

- ublock's default settings

### Notes

### CODE REVIEW

**Comment by uBlock-user** [comment]
@stephenhawk8054 Append PR issue link instead of long unecessary descriptions itself once you have opened a PR here as per https://github.com/uBlockOrigin/uAssets/blob/master/CONTRIBUTING.md#issue-number-association

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 Append PR issue link instead of long un-necessary descriptions itself once you have opened a PR here as per https://github.com/uBlockOrigin/uAssets/blob/master/CONTRIBUTING.md#issue-number-association

Got it, will do that next time 👍

**Comment by Yuki2718** [comment]
Also pls alphabetically sort domains in a filter.

**Comment by S0dV** [comment]
eventually encountered anti-out-of-focus on `https://linkshortify.site///uzIOZntQ`

**Pull request merged**
