### PR TITLE
address https://github.com/uBlockOrigin/uAssets/issues/9003

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by uBlock-user** [comment]
no filter ?

**Comment by IThinkIAmCool** [comment]
oops

**Comment by mapx-** [comment]
needing links and explanation

**Comment by IThinkIAmCool** [comment]
Isn't the website trying to sell stuff while impersonating a "Heart & Body Institute"?

**Comment by IThinkIAmCool** [comment]
Isn't the website trying to sell something illegally and immorally?
`https://health-articles.eu/fatfix-for-health-1-ro/news` has stuff which could mislead some people to think that this website is a news website, but upon clicking on different things (for example, the things below "CELE MAI INTERESANTE")

On `https://health-articles.eu/fatfix-heart-and-body-1-ro/centrum` some people could be mislead into thinking that the webpage is owned, operated and approved by a "Heart & Body Institute".

**Pull request closed without merging**
