### PR TITLE
Update https://github.com/uBlockOrigin/uAssets/pull/9649

### PR DESCRIPTION
**Pull request by shenzhiming88**

### CODE REVIEW

**Comment by mapx-** [comment]
explain the issue

**Comment by shenzhiming88** [comment]
@mapx- Provide longer term guarantee.
It is also possible to remove the above three lines of filters.
```txt
360doc.com##+js(aopr, document.oncontextmenu)
360doc.com##+js(aopw, document.body.oncopy)
360doc.com##+js(set, document.body.onmouseup, null)
```

**Comment by mapx-** [comment]
still working for anti copy

**Comment by shenzhiming88** [comment]
@mapx- Yes, but I think it's better to intercept iterative scripts so that the pages load faster. If you inject scripts, then access will be slowed down.

**Comment by mapx-** [comment]
maybe 
`360doc.com##+js(noeval-if, copy)`

**Comment by shenzhiming88** [comment]
> maybe `360doc.com##+js(noeval-if, copy)`

Why do we need to inject a script when we can intercept this script and be able to replicate it?

**Comment by krystian3w** [comment]
May break page in the future, maybe Fanboy Annoyances block script if allow unlock copy by this simple network filter.

**Pull request closed without merging**
