### PR TITLE
[Anti-copy] 360doc.com

### PR DESCRIPTION
**Pull request by shenzhiming88**
Address:`http://www.360doc.com/content/21/0720/00/65661269_987374075.shtml`

### CODE REVIEW

**Comment by shenzhiming88** [comment]
@uBlock-user @okiehsch I found that this is not completely fixed - still can't copy

**Comment by shenzhiming88** [comment]
@uBlock-user 
Hello!
Sorry, this Pull Request did not fix the problem completely, so you need to fix it again, thank you!

**Comment by uBlock-user** [comment]
what was not fixed ?

**Comment by shenzhiming88** [comment]
> what was not fixed ?

Pop-up window when you click Copy, which prevents copying

**Pull request closed without merging**
