### PR TITLE
update supervideo.tv

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

### CODE REVIEW

**Comment by okiehsch** [comment]
Any link?
I don't see it.

**Comment by ghajini** [comment]
i will provide wait

**Comment by ghajini** [comment]
`https://supervideo.tv/npikk7xl1pug`

**Comment by okiehsch** [comment]
Hm, I still don't see it, is this a mobile issue?

**Comment by ghajini** [comment]
yeah sometimes that popups kick in eg some embed sites where supervideo.tv is present

**Comment by okiehsch** [comment]
Thx.

**Pull request merged**
