### PR TITLE
Update for twitch.tv #5184

### PR DESCRIPTION
**Pull request by pixeltris**
This is an update to the twitch.tv ads workaround. Solution by @diglarboard

### CODE REVIEW

**Comment by llacb47** [comment]
Wrong. This is where it needs to be changed, and only gorhill can do it.

https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js

**Comment by pixeltris** [comment]
Oh right I wasn't aware of the change in location of this. Why does this file still exist?

**Comment by krystian3w** [comment]
for uBO Legacy or very old like 1.13.6

**Comment by gorhill** [comment]
Can you open a pull request for <https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js#L1329>?

**Comment by pixeltris** [comment]
https://github.com/gorhill/uBlock/pull/3781

**Comment by tigo9** [comment]
any update on this? it stopped working the last day or so

**Pull request closed without merging**
