### PR TITLE
Block counting copy-paste stackoverflow

### PR DESCRIPTION
**Pull request by paledega**
image
This dialog track my keyboard event so we must block **cdn.sstatic.net/Js/stub.en.js**

### CODE REVIEW

**Comment by uBlock-user** [comment]
Filter -- `stackoverflow.com##+js(aeld, copy, HTMLElement)`

**Comment by okiehsch** [comment]
The second logged "copy" event is sufficient enough on my end.

**Comment by uBlock-user** [comment]
yeah mine only removed the second notice that appeared after you used all your "free copy" events, that will do.

**Comment by lassekongo83** [comment]
This is an April fools joke. It will not be required tomorrow. `https://www.reddit.com/r/ProgrammerHumor/comments/mhjwyh/this_got_me_very_angry_for_a_few_seconds/`

**Pull request closed without merging**
