### PR TITLE
Update vidzi.tv (https://forums.lanik.us/viewtopic.php?f=62&t=33489)

### PR DESCRIPTION
**Pull request by SMed79**
https://pastebin.com/raw/0uHZ0Y6Q

### CODE REVIEW

**Comment by mapx-** [comment]
I tested `https://vidzi.tv/8r7idw7n5jkf.html` , I'll add other filters for popup / fake download 
```
vidzi.tv##script:inject(window.open-defuser.js)
vidzi.tv##a[href="https://vidzi.tv/download.html"]
```
but I see no `ww4`, `.date`

**Comment by okiehsch** [comment]
The `ww4` will eventually be called by the popup
vidz

I don't see any `.date`.

**Comment by SMed79** [comment]
> The ww4 will eventually be called by the popup

The `ww4` script is which open the popup
`https://ww4.vidzi.tv/e4/38/2f/e4382facab6bd7b04613bff3701e2573.js` (custom [admeasures](https://forums.lanik.us/viewtopic.php?f=62&t=33320) adserver).

For the `.date` requests I don't see them. I will comme report if this happens again.

**Comment by okiehsch** [comment]
`https://ww4.vidzi.tv/e4/38/2f/e4382facab6bd7b04613bff3701e2573.js`  they changed their popup-system, that's why 
````
vidzi.tv##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/, system.popunder)
```` 
did not prevent the popup, has t be changed to
````
vidzi.tv##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/, system.pops2.popunderCondition)
````

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/2dac35cbf7da35c3f155eb33fb1c91d188ca8951

**Pull request closed without merging**
