### PR TITLE
blocks ad on `https://urlhubber.technicalarp.com/`

### PR DESCRIPTION
**Pull request by IThinkIAmCool**

### CODE REVIEW

**Comment by IThinkIAmCool** [comment]
@ryanbr

**Comment by mapx-** [comment]
no, you cannot block that stuff, needing specific filters

**Comment by IThinkIAmCool** [comment]
Yes, you can. Shift + F5 to bypass caches.

**Comment by IThinkIAmCool** [comment]
image
image

**Comment by mapx-** [comment]
You didnt understand: **needing specific filters**
(using your filter will break lots of pages)

**Comment by IThinkIAmCool** [comment]
Isn't it an ad server?

**Comment by mapx-** [comment]
no

**Comment by IThinkIAmCool** [comment]
Then how come has it been used for at least 2 ads?

**Comment by uBlock-user** [comment]
blogspot is not an ad-server.

**Comment by uBlock-user** [comment]
People can upload ad-images to that domain to host it.

**Comment by IThinkIAmCool** [comment]
I meant `1.bp.blogspot.com`

**Comment by uBlock-user** [comment]
Yes, that domain is specific for images, can be anything and is owned by Google.

**Comment by IThinkIAmCool** [comment]
Oh, okay. Thanks for the information and sorry for wasting your time.

**Comment by llacb47** [comment]
Try to research what a domain is used for before PRing to block it.

**Comment by uBlock-user** [comment]
Same logic for `i.imgur.com`, if you see ad-images, make it domain specific.

**Pull request closed without merging**
