### PR TITLE
technicalatg,uploadrar,userupload up

### PR DESCRIPTION
**Pull request by BlazeFTL**
Fix `https://f.technicalatg.in/SNAnLfdZd`
Remove Obsolete hashhackers
`https://userupload.net/p8k2z2b475ks`
`https://uploadrar.com/fy1tog7m4uzr`

### CODE REVIEW

**Comment by ItsProfessional** [comment]
Why did you remove these?

```adb
hashhackers.com,katdrive.net,newsongs.co.in##+js(nano-sib, /verify_text|isCompleted/, *)
hashhackers.com,katdrive.net,newsongs.co.in##+js(nano-stb, document[_0x, *)
hashhackers.com,katdrive.net,newsongs.co.in###btnhide, #verify_button2, #verify_text, #getlink
hashhackers.com,katdrive.net,newsongs.co.in###verify_button:style(display: block !important;)
hashhackers.com,katdrive.net,newsongs.co.in###verify_button:upward(1) ~ #primary, #secondary
```

**Comment by BlazeFTL** [comment]
Not Used... Domains Dead

**Comment by ItsProfessional** [comment]
@ghajini why are you manually making commits instead of merging the PR?

**Comment by BlazeFTL** [comment]
@okiehsch Can You Check ?...Is This Normal ?

**Comment by BlazeFTL** [comment]
Uploadrar  empty placeholders,those styles are making name,file info visible which are hidden/half visible otherwise+ getpczone is a sperate website which he doesn't get why i used get.getpczone

Userupload show me where those cosmetics filters are needed

Technicalatg why you have to interfere when my filters work without any issue ?

**Comment by BlazeFTL** [comment]
These things are absolutely abnormal...no other maintainers thinks this is absolutely biased and he gets to do whatever he wants ?

**Comment by okiehsch** [comment]
> Can You Check ?

I checked the 3 example links with up to date filter lists, I can't download from the first link. 
The other two work without issue, or obvious ads, on my end.

**Comment by BlazeFTL** [comment]
See Okiehsch Comment Theres No Issue..Its Your Imaginary PC

**Comment by BlazeFTL** [comment]
Also why cant you add filters gor sites bad design? What would happen if you do so ?
https://github.com/uBlockOrigin/uAssets/pull/22528#issuecomment-1950496069
https://github.com/uBlockOrigin/uAssets/commit/24f20f97176b4a3a423323342e187cf9dc3002c6

**Comment by BlazeFTL** [comment]
I must you dont know what type of bully i am its just that you got lucky because you are here in github😆

**Comment by BlazeFTL** [comment]
> * we want stable filters

I would very much appreciate stable filters if you replaced others() and blocked some ads element but when i added others() long ago then i was pretty sure i was going maintain whatever issue would arise

**Comment by BlazeFTL** [comment]
@okiehsch Take A Desicion Bro..These Things Cant Continue...Should I Stop PR's ?..If You Say I Would...Tell Me @ghajini Was Always Right For What He Did

**Comment by okiehsch** [comment]
> Take A Desicion Bro

I won't, so please in the future ping someone else.

**Comment by BlazeFTL** [comment]
So things would continue like this ? Someone has to take a decision here..

**Comment by okiehsch** [comment]
I am retiring.

**Pull request closed without merging**
