### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by MasterKia**

### CODE REVIEW

**Comment by MasterKia** [comment]
The admin made an attempt to self-sabotaged his site.

**Comment by MasterKia** [comment]
@mapx- Do you know why `soft98.ir##[href*="sysban.ir"]:upward(2):remove()` doesn't remove this?
Screenshot_20220805_095329

`https://soft98.ir/software/17418-Display-Driver-Uninstaller.html`

**Comment by mapx-** [comment]
I'm on phone for a month, so..

**Comment by MasterKia** [comment]
Oh, I was wondering why you were inactive.

**Pull request merged**
