### PR TITLE
Update filters.txt

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

```
https://hexupload.net/rnj3vei9nh2e
https://hexupload.net/rnj3oei9nh2e
animetak.net
```

### Describe the issue

popups

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox a stable
- uBlock Origin version: 1.41.2

### Settings

- uBO's default settings

### CODE REVIEW

**Comment by okiehsch** [comment]
I will decline the hexupload changes,.
Thodr filters are still needed.

**Comment by okiehsch** [comment]
Example link
`https://hexupload.net/jiad05k6pn1v/ANSTOSS.3.Der.Fu%C3%9Fballmanager.v1.4.0.zip`

**Comment by ghajini** [comment]
so you get ads at chromium based browsers?
i don't see any?

**Comment by okiehsch** [comment]
No, but if I remove the filters like you propose I get a huge amount of - blocked - third-party requests, so those filters are not obsolete.
I will update the `animetak` as suggested by you.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/046f597b504291ca2e0474c107cbbd2930933718

**Comment by ghajini** [comment]
so apparently from your provided link it seems these are required

```
hexupload.net##+js(aopw, _pop)
hexupload.net##+js(acis, JSON.parse, break;case $.)
```

**Comment by okiehsch** [comment]
Atleast, yes I did not check of one of the blocked third-party scripts is a `Fingerprint2` popup script.
Though I suppose if we leave
````
*$script,3p,denyallow=bootstrapcdn.com|cloudflare.com|cloudflare.net|google.com|gstatic.com|hwcdn.net|jsdelivr.net|tawk.to|zencdn.net,domain=hexupload.net
````
in place `hexupload.net##+js(aopw, Fingerprint2)` can be safely removed.

**Comment by uBlock-user** [comment]
Should keep denyallow filters always, these are for life. Admin is not going to stop third-party abuse anytime soon.

**Comment by ghajini** [comment]
yes denyallow is a good filter but readjustment is required from time to time sometimes,you can go with your way(at least i haven't noticed revolving ads at this site from many days)

**Comment by uBlock-user** [comment]
> readjustment is required from time to time

Yes, that is to be expected when denyallow filters are added and you can always open a PR about adjustments as and when needed.

**Pull request closed without merging**
