### PR TITLE
Profitsfly Up

### PR DESCRIPTION
**Pull request by BlazeFTL**
`psa.btcut.io/7ozmM8ez?src=PSA`
`https://droplink.co/fVUapt`

### CODE REVIEW

**Comment by D4niloMR** [comment]
This works:

```
rezsx.xyz,ashrfd.xyz,poqzn.xyz,tpayr.xyz,tiktokcounter.net,sinonimos.de,antonimos.de,quesignifi.ca,tiktokrealtime.com##+js(rpnt, script, buttonLock = false;, buttonLock = false;(function() {const i = document.createElement('iframe');i.style = 'height:0;width:0;border:0;';i.id = 'a';document.body.appendChild(i);i.focus();})();)
```

**Comment by BlazeFTL** [comment]
I Am Pretty Site Owner Would Keep Updating The Words You Target

**Comment by D4niloMR** [comment]
Well, we don't need to allow all ad scripts because of that

**Review by D4niloMR — COMMENTED** [review]
nvm

**Comment by D4niloMR** [comment]
I wonder how long this will last

**Comment by BlazeFTL** [comment]
Allowed Scripts Would Be Good Old Ones
```
@@||googlesyndication.com^$script,xhr,domain=
@@||doubleclick.net^$script,xhr,domain=

**Pull request merged**
