### PR TITLE
Adding recipes for Shopify and reCaptcha

### PR DESCRIPTION
**Pull request by pwd-github**
reCaptcha credit goes to /u/ZaphodBeebblebrox from the /r/uMatrix Reddit community

Shopify is a popular store backend used on a lot of medium sized sites.

### CODE REVIEW

**Comment by ArchangeGabriel** [comment]
From my experience, reCaptcha also requires `xhr` for `google.com`.

**Comment by ArchangeGabriel** [comment]
And I have this for Shopify:
```
cdn.shopify.com script allow
checkout.shopify.com frame allow
checkout.shopify.com script allow
checkout.shopifycs.com frame allow
checkout.shopifycs.com script allow
elb.deposit.shopifycs.com xhr allow
```

**Comment by pwd-github** [comment]
My Shopify works well with what's in the patch. I've added the xhr to google.com though.

**Comment by ArchangeGabriel** [comment]
Well as long as checkout and payment is not concerned, I can live with only `script` for `cdn.shopify.com` (well `image` and `css` as well, but I have left the default enabled for all sites currently, though I might change that in the future).

**Comment by warnellw** [comment]
reCaptcha now requires web workers in some implementations:

recaptchawebworkers

**Comment by ArchangeGabriel** [comment]
The worker is not strictly required, in the sense that it works without it. I’m opening a separated PR for reCaptcha only.

**Comment by ArchangeGabriel** [comment]
https://github.com/uBlockOrigin/uAssets/pull/1997

**Pull request closed without merging**
