### PR TITLE
Update quick-fixes.txt

### PR DESCRIPTION
**Pull request by BlazeFTL**
`https://dropgalaxy.com/drive/xx34excmo7jd`

### CODE REVIEW

**Comment by okiehsch** [comment]
Sorry, but I won't add a blanket exception to a default list.

**Comment by okiehsch** [comment]
I know that this is frustrating and I appreciate all the work you put in it but circumventing at all costs is not worth it imo.

**Comment by BlazeFTL** [comment]
OR Accept PR & Remove That @@script Allow Rule

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3e6bcc44e18b0a711dd7135f0c0e3bc859cc2d22

**Pull request merged**
