### PR TITLE
Fix sh.st: anti-adblock message

### PR DESCRIPTION
**Pull request by Yuki2718**
### URL(s) where the issue occurs

`http://sh.st/iA5JK`

### Describe the issue

Unobtrusive anti-adblock

### Screenshot(s)

sh

### Versions

- Browser/version: Brave 1.8.86
- uBlock Origin version: 1.26.0

### Settings

- Default + Fanboy's Annoyances + uBlock Annoyances

### CODE REVIEW

**Comment by mapx-** [comment]
I cannot reproduce FF / chrome

**Comment by Yuki2718** [comment]
> 
> 
> I cannot reproduce FF / chrome

Reload several times.

**Comment by Yuki2718** [comment]
BTW it seems a rule in uBlock filters `sh.st##+js(acis, parseInt, tabunder)` is outdated, maybe.

**Comment by mapx-** [comment]
Did you disable brave protection (all of them) ?

**Comment by Yuki2718** [comment]
Sure, if it blocked sth or upgraded connection to https the counter should appear.

brave

Of note, it's not 100% reproducible on my end too. Only occasionally.

**Comment by mapx-** [comment]
Try a chrome portable installation too

**Comment by Yuki2718** [comment]
> 
> 
> Try a chrome portable installation too

Okay, I can't reproduce on Chrome.

**Comment by Yuki2718** [comment]
No idea, even with Brave's shields completely turned off and exactly the same entries on the logger, it only appears on Brave.

**Comment by mapx-** [comment]
similar issue here: https://forums.lanik.us/viewtopic.php?f=100&t=44571

but in that case even using brave I cannot reproduce the same issue.

**Comment by mapx-** [comment]
ok ... I tested now sh.st in brave and .. I get your same issue.

I watched the shields settings for the site (even if I disable globally like you any shields)
image

If I switch the orange button (disabling it) to grey then all is ok !

So, it seems brave has some other protections not explicitly listed in the global settings

**Comment by Yuki2718** [comment]
> 
> 
> ok ... I tested now sh.st in brave and .. I get your same issue.
> 
> I watched the shields settings for the site (even if I disabled globally like you all shields)
> image
> 
> If I switch the orange button (disabling it) to grey then all is ok !
> 
> So, it seems brave has some other protections not explicitly listed in the global settings

Thank you for confirmation, it's a finding. Maybe I should report to or ask for Brave.

**Pull request closed without merging**
