### PR TITLE
Moved & merged filters ae713f4

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by okiehsch** [comment]
I can't merge this, you have not incuded the latest commit, so this would revert the last fix.

**Comment by smed79** [comment]
Already fixed.

**Comment by okiehsch** [comment]
Oops, sorry I missed that.

**Comment by okiehsch** [comment]
Thx.

**Comment by smed79** [comment]
Instead of quickly close the PR (As here https://github.com/uBlockOrigin/uAssets/pull/3893) you can give us the chance to fix the conflict to avoid the noise.

**Pull request merged**
