### PR TITLE
update https://github.com/uBlockOrigin/uAssets/issues/11814

### PR DESCRIPTION
**Pull request by JobcenterTycoon**
### URL(s) where the issue occurs

`https://dropgalaxy.in/nb6mmby8r11t`

### Describe the issue

anti adb

### Versions

- Browser/version: firefox developer
- uBlock Origin version: 1.41.6

### Settings

uBlock Origin default + uBlock Origin annoyances

### Notes

fix https://github.com/uBlockOrigin/uAssets/issues/11814

### CODE REVIEW

**Comment by krystian3w** [comment]
Webmaster fix script after commit?

**Comment by JobcenterTycoon** [comment]
Thats the real question here. But i can add more fixes if needed i have time.

**Comment by JobcenterTycoon** [comment]
@krystian3w does the fix work for you? i still get rarely anti adb

**Comment by krystian3w** [comment]
I Mean maybe better mark domain as no worth to fix 12 times at day.

**Comment by JobcenterTycoon** [comment]
@krystian3w 

There can be a end. Look the examples below:

<details>

`https://github.com/uBlockOrigin/uAssets/issues?q=techpowerup`
`https://github.com/uBlockOrigin/uAssets/issues?q=elitepvpers.com`
`https://github.com/uBlockOrigin/uAssets/issues/6587`
`https://github.com/uBlockOrigin/uAssets/issues/10076`

</details>

filters for these sites still working fine

**Pull request merged**
