### PR TITLE
Update badware.txt

### PR DESCRIPTION
**Pull request by IThinkIAmCool**
Screenshot_20210605_191412_org mozilla firefox
Screenshot_20210605_191303_org mozilla firefox

### CODE REVIEW

**Comment by mapx-** [comment]
How (visiting what site) did you get that page ?

**Comment by IThinkIAmCool** [comment]
Screenshot_20210605_205803

**Comment by IThinkIAmCool** [comment]
Screenshot_20210605_210119

**Comment by mapx-** [comment]
waiting for a simple answer: link of the page.

**Comment by IThinkIAmCool** [comment]
`http://adsbtc.org/` may be it.

**Comment by IThinkIAmCool** [comment]
I remember clicking on 
image

**Comment by IThinkIAmCool** [comment]
image
@ryanbr

**Comment by IThinkIAmCool** [comment]
image

**Comment by IThinkIAmCool** [comment]
Attempting in a mobile envorinment may help. I'm not sure if I allowed the connection temporarily.

**Pull request merged**
