### PR TITLE
Remove no longer used third-party resources

### PR DESCRIPTION
**Pull request by gwarser**
Do not merge (yet), it's just a note.

Main fork already moved assets to different repo https://github.com/geekprojects/nuTensor/commit/e9274d6e3050ffec600706c2513740540554b101

<sub>Palemoon fork: https://gitlab.com/vannilla/ematrix</sub>

### CODE REVIEW

**Review by krystian3w — CHANGES_REQUESTED** [review]

**Comment by gwarser** [comment]
Ok, this should be merged. People still trying to make pull requests to uMatrix code. Forks stalled or improve very slow.

**Comment by gorhill** [comment]
Sorry, I wasn't aware of this pull request.

It says there are conflicts to resolve, seems it's you who must resolve them.

**Comment by gwarser** [comment]
Update script modified files removed by this commit. Rebased on current HEAD.

**Comment by uBlock-user** [comment]
missed  https://github.com/uBlockOrigin/uAssets/blob/master/filters/experimental.txt

**Comment by gwarser** [comment]
I focused on uMatrix related resources. Not sure what to do with this list.

**Comment by uBlock-user** [comment]
So remove it. All the filters listed there already present in the default lists + the list has been removed from uBO filter lists pane.

**Pull request merged**
