### PR TITLE
Apple Mapkit as 3rd-party

### PR DESCRIPTION
**Pull request by theel0ja**
Demo site: `https://developer.apple.com/wwdc/more/`

### CODE REVIEW

**Comment by gorhill** [comment]
Best to use:

    _ apple-mapkit.com * allow
    _apple-mapkit.com script allow

Instead of:

    _ apple-mapkit.com image allow
    _ apple-mapkit.com script allow
    _ apple-mapkit.com xhr allow

**Comment by theel0ja** [comment]
Done.

**Comment by gorhill** [comment]
I made a typo in my comment (fixed afterward), you copied the typo to the recipe.

**Comment by gorhill** [comment]
Thanks.

**Pull request merged**
