### PR TITLE
update filter

### PR DESCRIPTION
**Pull request by ghajini**
### URL(s) where the issue occurs

`https://beststremo.com/Sapphire-Duck/player2.php?link=lMPAFDFNWf9Tw5HVjP7nNrgOVfAVQId5RKpDzgNQWBRggFWSiYn1gANbSZMU/hcd1lTFD4oZU7LwstMe8abCmUGiWwjO04v@X/AEc5zVwpVbnLKEE42il9WpmpRWnqoNA4@dchVBHiVSrVuWlE2NyrNKgQAT4h8aW1EG0akVjpuiV@hOQk8XjVXTWh5GS4mCGN25XEteWkBLHlxcVhtV7xgDuEucVkVYV36KylSFQAACyg==`

### Describe the issue

Fix `beststremo.com##+js(aost, Math, /(?=^(?!.*(https)))/)` doesn't work at opera browser ,still popunders

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.41.8

### Settings

- uBO's default settings

### Notes

### CODE REVIEW

**Comment by mapx-** [comment]
- working fine in opera too
- does this filter work for you ?

`beststremo.com##+js(nostif, 0x)`

**Comment by ghajini** [comment]
yes work

**Comment by krystian3w** [comment]
Aost specific.

**Comment by ghajini** [comment]
`beststremo.com##+js(aopr, mm)`
much better, it make sure those requests don't come(`vene....`)

**Pull request closed without merging**
