### PR TITLE
Add google.com to anti click trackers list

### PR DESCRIPTION
**Pull request by BPower0036**
### URL(s) where the issue occurs

`https://www.google.com`

### Describe the issue

When clicking on search results, google.com redirects it via their own server. Try `https://www.google.com/search?q=example.com%252Ftest%253Fq%253Dtest` as a test

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: 116.0.2
- uBlock Origin version: 1.51.0

### Settings

None of them affects this problem.

### Notes
Maybe, the rule should be narrowed down to only `https://www.google.com/search?` since their are more outgoing links and we don't want to break other links of google

### CODE REVIEW

**Comment by stephenhawk8054** [comment]
There's `www.google.*##+js(set, rwt, noopFunc)` in annoyance list.

Does it work for you?

**Comment by BPower0036** [comment]
Yes, it works.
So there is no need to merge this PR.

**Comment by Yuki2718** [comment]
I don't.

**Comment by stephenhawk8054** [comment]
Hmmm... I checked google activity settings and it just shows `search history` (aka search terms used), but not links clicked.

**Comment by stephenhawk8054** [comment]
I mean without that filter. I don't see any settings in google settings that shows the clicked ones (or I haven't found it yet).

**Comment by stephenhawk8054** [comment]
Ok, I'll move it to privacy list. Due to the update gap of both lists, we can keep in both until next week.

**Pull request closed without merging**
