### PR TITLE
bing.com: breakage

### PR DESCRIPTION
**Pull request by hightower-web**
I see more than half the web results being blocked with these rules along with ads making results page unusable

### CODE REVIEW

**Comment by hightower-web** [comment]
Can someone please help review and get this checked in if no concerns

This is the current rule application blocking every web result
image

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site? Are you signed in?

**Comment by stephenhawk8054** [comment]
I only removed `bing.com##li.b_algo:has(> [class="b_caption"] > p[class*=" "])`. The other filter matches the sponsored posts correctly on my side.

**Comment by hightower-web** [comment]
Thank you for the push

**Pull request closed without merging**
