### PR TITLE
address metro.co.uk anti-adb

### PR DESCRIPTION
**Pull request by AlecBlance**
### URL(s) where the issue occurs

`https://metro.co.uk/`

### Describe the issue

Anti-adblock present

### Screenshot(s)

Before: 
image

After:
image

### Versions

- Browser/version: Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.37.2

### Settings

Default

### Notes

N/A

### CODE REVIEW

**Comment by Mennaruuk** [comment]
Can't reproduce. Should be taken care of with **uBlock filters** list.
Untitled(1)

**Comment by AlecBlance** [comment]
Hello, here's what I see. 

https://user-images.githubusercontent.com/17378596/131932938-04fc5a88-26f4-40d5-b508-02111e567569.mp4

**Comment by Mennaruuk** [comment]
Puzzling. I saw your video, and there, enabling **uBlock filters** list did nothing to block the anti-adblock warning. From my side, however, it's the exact opposite.

https://user-images.githubusercontent.com/52135169/131936070-0e4042c7-bc75-456e-9206-5e8b3e5de55a.mp4


I'm suspecting the culprit might be the _Trusted sites_ section. Do you happen to have exceptions there for anything related to `metro.co.uk`?

image

**Comment by AlecBlance** [comment]
My _Trusted sites_ section is in default list.

image

I also followed your attached video, here's the result. 

https://user-images.githubusercontent.com/17378596/131938900-5601928a-258f-4886-a274-0f29347f6a78.mp4

It has the same result with firefox on my end.

**Comment by uBlock-user** [comment]
Reset to default settings/lists + disable all other extensions and try again.

**Pull request closed without merging**
