### PR TITLE
Fix #881 fix #1275 fix #2054

### LINKED ISSUE #881: Avoiding the Cookie message showing on hardware.info
### URL(s) where the issue occurs
`https://nl.hardware.info/nieuws/54379/amd-bevestigt-raven-ridge-vega-11-en-stopzetting-productie-vega-referentiekaarten`

### Describe the issue

Wanting a uBo way to ignore the cookie file "cookiebar", so I can bypass in Cookiemonster. If you clear the cookies on the site manually, it will show a overlay when you refresh the site. Once you press the green button the site will insert "cookiebar" cookie name. Trying to figure a way to get around this.

### Versions

- Browser/version: Firefox Nightly
- uBlock Origin version: 1.14.20

### Settings

Just Easylist/Easprivacy/and various Fanboy subs.

### Notes

Looking at including uBo filters for sites we can't block normally in ABP into Cookiemonster.

### LINKED ISSUE #1275: marktplaats.nl cookiewall
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.marktplaats.nl`

### Describe the issue

Cookie warning shows up, can not block with cosmetic. All Annoyance filters are set. 
AdGuard works fine with it due to this rule:
marktplaats.nl#%#AG_onLoad(function() { var form = document.forms['track-accept']; if (form) { form.submit(); } });
But uBlock does not support AG_onLoad?

### Versions

- Browser/version: Firefox latest
- uBlock Origin version: latest

### LINKED ISSUE #2054: f1racing.pl
### URL(s) where the issue occurs

`f1racing.pl`

### Describe the issue
Cookies message

### Versions

- Browser/version: Vivaldi 1.14.1077.60
- uBlock Origin version: 1.16.0

### Settings

```
- "selectedFilterLists": [
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt",
    "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt",
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt",
    "https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt",
    "https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt",
    "POL-0",
    "plowe-0",
    "fanboy-social",
    "spam404-0",
    "malware-1",
    "malware-0",
    "disconnect-malvertising",
    "easyprivacy",
    "easylist",
    "awrl-0",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
    "nano-whitelist",
    "nano-timer",
    "nano-filters",
    "nano-defender",
    "user-filters"
  ],
```

### Notes
https://github.com/MajkiIT/polish-ads-filter/issues/7238
Only this cookie message is here and user must click „Dalej" to go to right page. So probably something new should be added to uBO to make auto click „Dalej" or redirect to `http://f1racing.pl/x-set-cookie/`.

### PR DESCRIPTION
**Pull request by jspenguin2017**
Add new scriptlet to auto-accept cookie notices. 

Fixes: 
https://github.com/uBlockOrigin/uAssets/issues/881
https://github.com/uBlockOrigin/uAssets/issues/1275
https://github.com/uBlockOrigin/uAssets/issues/2054

### CODE REVIEW

**Comment by mapx-** [comment]
@gorhill

**Comment by gorhill** [comment]
I want to think more about this, basically I want to figure what could go wrong by having filters which can automatically click stuff. These make me uncomfortable. My first thought is that this should at least apply **only** to visible elements. The question to answer is how could this be misused by either filter list maintainers or site owners.

**Comment by jspenguin2017** [comment]
Yea... I was hesitating about this for a while too, but since it only scan the DOM once and the click isn't `trusted`, I guess it's safe enough. I don't think this is any more dangerous than `set-constant.js`.

**Comment by jspenguin2017** [comment]
How do you like the idea of privileged filters? Scriptlets that are on the line of being too overpowered are guarded behind a privileged flag, so only trusted filters can use them.

**Comment by migueldemoura** [comment]
I haven't tested this, but having scriplets that can essentially execute requests sounds like a **really bad idea**.

Please correct me if I'm wrong, but from this example taken from the updated `annoyances.txt`:
`hardware.info##script:inject(nano-click-elements-onready.js, .cookiecontainer > .cookie > button#decision[name="accept"])`

What if I replace that button by a "delete account" button? Or any other with side-effects?

You can even chain requests with this, all bypassing request tokens and the like. This is potentially dangerous.

**Comment by jspenguin2017** [comment]
Yea... I'll mark the script snippet as privileged.

**Comment by jspenguin2017** [comment]
Actually, that was my proposal, @gorhill do you want a "privileged scriptlet" system in uBO? I can PR.

**Comment by migueldemoura** [comment]
Can you elaborate on how that'd work, @jspenguin2017? Those filters would have to come from uAssets?

**Comment by jspenguin2017** [comment]
Alright.

**Comment by migueldemoura** [comment]
Got it, thanks @jspenguin2017.

**Comment by DrIT2016** [comment]
@jspenguin2017 since these new scriptlets the cookiewall isn't blocked anymore on some sites (e.g marktplaats and hardware.info). Can you please have a look?
Still using uBlock with advanced userResourcesLocation "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt" and filter "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoAnnoyance.txt"

**Comment by jspenguin2017** [comment]
@DrIT2016 
Because uBO is not aware of privileged scriptlets, I can't allow them to run in uBO for security reasons.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2229

**Pull request closed without merging**
